### ISSUE TITLE
autosubmit not triggered by <input type="reset">

### ISSUE THREAD

**Issue by stefanfisk** [unpoly/unpoly#101]
Here's a minimal example, in the console one can see that the text input triggers autosubmit while the reset input clears the text input but does not trigger autosubmit.

https://codepen.io/stefanfisk/pen/JjjwGdB

My use case was for clearing a filter form without additional JS, but as a workaround I'm currently using a small snippet to autosubmit on reset.

**Comment by triskweline** [comment]
It looks like resetting a form triggers neither `change` nor `input` events on affected fields. We would need to listen for a [`reset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event) event on the form, even if we're only observing a single field.

**Comment by pfw** [comment]
Additionally to this the reset event is documented as being sent before the values are reset so a setTimeout is required after receiving the event before doing the autosubmit so empty values are sent.
