### ISSUE TITLE
Mimic "data-disable-with" with Unpoly

### ISSUE THREAD

**Issue by robinvdvleuten** [unpoly/unpoly#104]
One of the in Rails UJS I still use in almost every "Unpoly" project is the `data-disable-with` functionality when submitting a form. Would it be an idea to have such functionality in the core of Unpoly as well? Maybe something like `up-disable-with`. I could make even a PR for it, if you like.

**Comment by triskweline** [comment]
Sorry that I didn't respond to this earlier.

I think this would be a good addition to get feature parity with Rails UJS. Other than Rails we would also need re-enable the button after the server has responded to the form submission. The updated fragment might not include a fresh copy of the disabled button.

**Comment by triskweline** [comment]
The Turbo folks are [making a point for using `[aria-disabled="true"]` instead of `[disabled]`](https://github.com/hotwired/turbo/pull/386#issuecomment-945161995).

**Comment by triskweline** [comment]
> The Turbo folks are making a point for using [aria-disabled="true"] instead of [disabled].

This would require additional JavaScript to prevent interaction with the form.
