### ISSUE TITLE
Modals do not respect the autofocus attribute

### ISSUE THREAD

**Issue by nicola-zen** [unpoly/unpoly#109]
Hi guys,

first of all thanks for all the great work devoted in building `unpoly`. It is a very cool concept and I love how it made easy to add interactivity to my small flask side project.

I have a possible improvement proposal. One thing that I noticed is that modals do not respect the `autofocus` attribute on textareas (and likely on normal inputs as well).

I have the following html component, in a page loaded by a modal

```html
<div class="mx-auto max-w-2xl" id="edit-log">
    <div class="w-full clearfix">
        <form action="{{ url_for('logbook.update_log_content', log_id = log_id) }}" method="post"
            up-target="#logs-list">
            <textarea class="input w-full " type="msg" name="text" autofocus>{{ content }}</textarea>
            <button class="float-right button button-primary" type="submit">
                Update Log
            </button>
        </form>
        <form action="{{ url_for('logbook.delete_log_entry', log_id = log_id) }}" method="post">
            <button class="float-left button button-danger transition-all" type="submit">
                Delete Log
            </button>
        </form>
    </div>
</div>
```

loaded by a modal as follows:

```html
<a class="text-gray-600 text-sm font-semibold hover:text-blue-800 transition-text"
    href="{{ url_for('logbook.update_log_content', log_id = item.id) }}" up-dash
    up-modal="#edit-log">EDIT
</a>
```

I would have expected the `textarea` to be focused on modal load, but that is not the case.

I managed to get the desired behavior with a simple js event listener

```javascript
document.addEventListener("up:modal:opened", event => {
  const el = document.querySelector("textarea[autofocus]");
  el.focus();
});
```

The proposal is: would it be a good idea to add this behaviour to the default unpoly package?

Cheers!

**Comment by triskweline** [comment]
Hi Nicola. I'm glad you're having success with Unpoly.

The modal implementation is currently getting a rewrite for the next major version (branch [hk/layers](https://github.com/unpoly/unpoly/tree/hk/layers)). Proper `[autofocus]` handling as you suggested in this issue has already been implemented in that branch.

The new implementation will also focus the layer area when opened (if there is no `[autofocus]` element), and restore focus to the opening link when the modal is closed again. This is relevant for accessibility and screen readers.

**Comment by nicola-zen** [comment]
Good afternoon Henning,

great! I will close this issue as it was an improvement idea, but it is already in the works.

Thanks!
