### ISSUE TITLE
up.response type on up.replace

### ISSUE THREAD

**Issue by keyurshah** [unpoly/unpoly#113]
Hello,

I'm seeing if there is any way to retrieve the value of a custom header on up.replace()? 

Situation:

I am trying to create a chain of ajax requests to break up a very long running script into multiple requests. 

I'm dong so by using up.replace to submit the POST and append the results to a div on the page.

With the result, I am also returning a custom header that contains the url for the next AJAX request.

It seems that up.request returns a up.response which allows response.getHeader(), but up.replace does not return a similar response object.

Wondering if this is possible or if there is a better way to do this? 

Thanks!

Code:

``` javascript
  up.on('submit', '#js-form', function(event, element) {
    event.preventDefault();

    var initial_url = '/upload-data';
    chainRequest(initial_url)
  });

  function chainRequest(url) {
    up.replace('#results:after', url, {method: 'POST', history: false})
        .then(function(response) {
          //would like to do the following
          //var nextPageURL = response.getHeader('X-NEXT-PAGE-URL')
          //chainRequest(nextPageUrl)
        })
  }
```

**Comment by triskweline** [comment]
I'm afraid `up.replace()` does not give you access to the `response` object.

A workaround for your case could be to embed the next URL in the updated fragment, e.g. `<div id="results" data-next-page-url="...">`). This way you could queue up the next request without needing to access headers.
