### ISSUE TITLE
Multiple Transitions Supported?

### ISSUE THREAD

**Issue by KinneyDaniel** [unpoly/unpoly#114]
I note that one can have multiple `up-target`s, which is handy. But I would like to apply a different transition to each target. Is that possible? The documentation doesn't suggest that it is, and trying the format used to apply multiple `up-target`s also doesn't work.

If this is not natively supported, is there a way to work around it?

Thanks for a *wonderful* tool!!

**Comment by triskweline** [comment]
Hi @KinneyDaniel. I'm afraid this is not currently possible.
