### ISSUE TITLE
how use up-hungry?

### ISSUE THREAD

**Issue by nikolaokonesh** [unpoly/unpoly#115]
After creating a new post it doesn't show up on the list of the created  ones. How to refresh the list without reloading a page?

**Comment by triskweline** [comment]
You may assign the `up-hungry` attribute to elements that should be updated, even if they aren't explicitely targeted with an `up-target` attribute.

If you have a specific issue with `up-hungry` not working as expected, I recommend that you prepare a Codepen with a minimal example and ask on the [Unpoly mailing list](https://groups.google.com/group/unpoly).
