### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by bigtunacan** [unpoly/unpoly#116]
I just came across this project, really interesting approach you are taking here; I love the idea.

I noticed in the install documentation that there are some optional helper files for people using bootstrap 3 with Unpoly.  I was wondering if there is something similar available or coming soon for Bootstrap 4?

**Comment by triskweline** [comment]
Yes, the upcoming Unpoly 0.70 will contain an optional script that configures compatiblity with Bootstrap 4 classes.

It's only a few lines, so you might as well just copy it into your project now:
<https://github.com/unpoly/unpoly/blob/hk/layers/lib/assets/javascripts/unpoly-bootstrap4.coffee>
