### ISSUE TITLE
[up-validate] Full form validation causes unexpected behavior of submitting the form

### ISSUE THREAD

**Issue by KD6-3** [unpoly/unpoly#119]
A form with `up-target` and input field(s) with `up-validate` causes unexpected behavior during submitting the form under special circumstances (full form validation and only one input field is changed).

**How to reproduce**

You have a form like this:

```
= form_with(model: @person, html: {'up-target': '.main'}, local: true) do |form|
  - errors = form.object.errors

  .fieldset
    .label
      = form.label(:first_name)
    .input
      = form.text_field(:first_name, 'up-validate': '')
    .error
      = errors[:name].join(', ')
  .fieldset
    .label
      = form.label(:last_name)
    .input
      = form.text_field(:last_name, 'up-validate': '')
    .error
      = errors[:last_name].join(', ')

  = form.submit('Submit', class: 'button')
```

If you fill in or change `first_name` with some valid input and click `Submit` then it triggers a request with the request header `X-Up-Validate: person[first_name]`. If I submit the form again, the request is send without this header and the model is created as expected.

**Expected**

Manually submitting the form should send a request without the request header `X-Up-Validate: person[first_name]` .

**Comment by triskweline** [comment]
This is fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0), which was released today.
