### ISSUE TITLE
Prevent stripping trailing slash

### ISSUE THREAD

**Issue by SebCorbin** [unpoly/unpoly#12]
Hello, I'm giving unpoly a test ride on a Django application, so far, so good.
Except that it strips the trailing slash by default, how can I set the `stripTrailingSlash` to false by default?

**Comment by triskweline** [comment]
@SebCorbin Can you give a minimal example where Unpoly strips a trailing slash that you would like to have preserved?

**Comment by SebCorbin** [comment]
When I visit my login form, url is `/login/?next=/`, once unpoly is in place and executed, url is transformed to `/login?next=/` via HistoryAPI (no reload), but my form has the attribute `action=""` hence when submitted it goes to `/login?next=/` which is not existing on the Django side.

**Comment by triskweline** [comment]
Should be fixed in version `0.34.1`.
