### ISSUE TITLE
Convert a codebase to ES6/TypeScript

### ISSUE THREAD

**Issue by hason** [unpoly/unpoly#124]
Today is CoffeeScript completely dead on the market. For better involvement of multiple contributors, it would be a good idea to convert the code to es6/typescript.

**Comment by EugeneDae** [comment]
I second this.

**Comment by boxxxie** [comment]
typescript seems like a big ask

**Comment by boxxxie** [comment]
would running the project through something like https://decaffeinate-project.org/repl/ be an option?

**Comment by boxxxie** [comment]
also, i notice that a lot of code in the project is tied to rails, maybe this could be broken out into a separate app/repo

**Comment by triskweline** [comment]
CoffeeScript is currently being removed file-by-file in `master`.
