### ISSUE TITLE
FR: up-on attribute

### ISSUE THREAD

**Issue by keyurshah** [unpoly/unpoly#125]
Hello,

Is it possible to have the functionality of `up.on()` be available as an attribute, `up-on`?

I'd like to basically have an element be reactive to an event, in this case, `load` without having to declare a separate up.on() function or a compiler. The need is mainly for code simplification in handling triggers.

```
<a href="front.html" class="one" up-target=".one" up-on="load">
  Flip
</a>
```

Thank You!

**Comment by triskweline** [comment]
There's no existing functionality for that. I think the syntax in your code example would need to be reworked to cover more than just this one case. In particular the user would also need to be able to define what to do when the event is observed (here it is implicit: follow the link) and on which element to listen for the event (here it is implicit: the `window` object).

What you can do right now is define a new attribute `[follow-on-load]` that works for your case:

```html
<a href="front.html" class="one" up-target=".one" follow-on-load>
  Flip
</a>
```
You can define new attributes using a [compiler](https://unpoly.com/up.compiler):

```javascript
up.compiler('[follow-on-load]', (link) => {
  if (document.readyState == 'complete') {
    up.follow(link)  
  } else {
    window.addEventListener('load', () => up.follow(link))
  }
})
```
