### ISSUE TITLE
Modal flicker

### ISSUE THREAD

**Issue by adam12** [unpoly/unpoly#13]
First off, thanks for Unpoly - it's been a joy to use thus far.

I'm dealing with a strange flickering issue with Unpoly modals, and originally I thought it was related to other project CSS, but I can reproduce it without any other stylesheets loaded, which makes me believe it's more specific to Unpoly.

I've included a video demonstrating this - has anybody seen this before?

http://adamdaniels.ca/i/screencast_2017-03-03_16-40-01.mp4

**Comment by triskweline** [comment]
Hi @adam12, thanks for the video.

I'm afraid I cannot reproduce the flickering modal in this minimal example: http://unpoly.com/examples/modal/preview.html

Are you sure that no other CSS or inline `style` attributes are present?

Could you provide two minimal HTML files that expose this issue?

**Comment by adam12** [comment]
Thanks for the response. Indeed, it doesn't occur on that example for me either.

> Are you sure that no other CSS or inline style attributes are present?

It occurred without any other CSS on the page.

> Could you provide two minimal HTML files that expose this issue?

I will see if I can do this. It could be my app specific (but I don't think it is, TBH).

Due to the random nature of it (usually the first few clicks, and then random afterwards), it's been a bit hard to debug, but I have found that adding the `up-animation="none"` property to the selector, the flicker never happens.

Alternatively, adding an `up-animation="move-from-top"` or similar animation, the issue is even more pronounced.

What I suspect is happening is some sort of styling occurring out of order - the backdrop appearing without animations, then disappearing/reappearing with the specific animation.

**Comment by triskweline** [comment]
If you manage to attach a minimal use case to this issue, please also let me know your browser and OS.

How I would debug this further: Choose a really long duration of the opening animation (e.g. using `up-delay="6000"`, then use the browser inspector to see if anything looks funny during the animation.

**Comment by adam12** [comment]
> Choose a really long duration of the opening animation (e.g. using up-delay="6000"

That helped - I saw the modal immediately open and then close, and after the delay, it opened normally.

> please also let me know your browser and OS

Chrome on macOS, but I can reproduce it with Safari on macOS as well.

**Comment by triskweline** [comment]
I think what happens is that the modal enters the DOM and is visible for one frame before the animation (fading in from opacity 0 to 1) begins.

The issue might be between these two lines:
https://github.com/unpoly/unpoly/blob/93f988ab9646532be2760f10493fa1fbf22212bd/lib/assets/javascripts/unpoly/modal.coffee#L473
https://github.com/unpoly/unpoly/blob/93f988ab9646532be2760f10493fa1fbf22212bd/lib/assets/javascripts/unpoly/modal.coffee#L476

We're using promises to chain "server response has been received" and "start animating". However, a browser might insert a rendered frame between those two actions [because of reasons](https://makandracards.com/makandra/42088-your-browser-might-silently-change-settimeout-f-0-to-settimeout-f-5).

**Comment by adam12** [comment]
I think you're right.

I'm able to prevent the flicker with the following CSS, but I don't care for it and I am not sure if all the animations use an `opacity` style attribute, or just the default.

```css
.up-modal > * {
  opacity: 0;
}
```

Would it make sense for the `createFrame` function to hide the modal by default (with an inline style maybe?)?

**Comment by triskweline** [comment]
Unfortunately I cannot reproduce this issue on my machines, even when I provoke timeout clamping.

I went ahead and implemented your idea of hiding the modal before starting the opening animation. Could you please check if the issue is solved in version 0.34.2?

**Comment by adam12** [comment]
> I went ahead and implemented your idea of hiding the modal before starting the opening animation. Could you please check if the issue is solved in version 0.34.2?

Fix worked! Thanks.
