### ISSUE TITLE
Support development through GitHub Sponsorships?

### ISSUE THREAD

**Issue by stevebauman** [unpoly/unpoly#131]
Hi @triskweline! I love Unpoly ❤️ . This is something I've been wanting for a *very* long time.

Is there a way I (or the community) can support development? Maybe through GitHub sponsorships? I'd be happy to sponsor!

**Comment by triskweline** [comment]
Hi Steve! That's a very generous offer. Right now the only way to help fund Unpoly is to purchase consulting hours or sponsor development of a particular feature (both through [makandra](https://makandra.com/)).

Github sponsorships look very interesting, I will need to find out how to deal with such income tax-wise.

**Comment by stevebauman** [comment]
Dang! Okay -- I'll keep in mind purchase of consulting or sponsoring a feature.

If you're able to work out GitHub sponsorships, I'll be first in line! 👍
