### ISSUE TITLE
Prevent scroll/jump when navigating to a fragment

### ISSUE THREAD

**Issue by johndwells** [unpoly/unpoly#132]
Is it possible to disable the "scroll to fragment" sort of behavior when following a up link to a specific target element?

Unless I'm doing something wrong, when I use `up-target="#some-container"`, the browser seems to jump down to that container. I'm currently using up-target to filter a container of elements, so the container's height is changing as a result, and it causes a lot of jumping as I go from a filtered to unfiltered state.

**Comment by adam12** [comment]
You're liking looking for [`up-reveal`](https://unpoly.com/a-up-target#up-reveal).

**Comment by johndwells** [comment]
@adam12 Yes! I knew I was missing something in the docs. Thanks a bunch.
