### ISSUE TITLE
up-target="main" autoscrolls

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#133]
work around is to use a different tag, but according to the docs https://unpoly.com/up.reveal
i don't expect scrolling behaviour for this tag.
i don't see "main" in the codebase, though, so possibly this is being directed by the browser?

**Comment by adam12** [comment]
Can you make an example using something like Codepen?

You mention `up-target` but link to `up-reveal`. A naked `up-target="main"` will auto reveal without setting `up-reveal="false"` on the same element.

**Comment by boxxxie** [comment]
sorry, i think i got confused a bit. 

i started using links in a nav bar, and i guess i was expecting that they would behave well if i used up-nav.

however, maybe it would be worth while to add some tips to the up-nav or scrolling-viewports docs to cover navigation bar issues.
