### ISSUE TITLE
Drawer closes unexpectedly

### ISSUE THREAD

**Issue by MattApril** [unpoly/unpoly#137]
I noticed a slightly unexpected behaviour when using the up-drawer component. If I click anywhere on the modal and then hold and release (mouse up) outside of the drawer component it will close. This came up for me when I used my mouse to select the text inside an input element in the drawer, and it closed unexpectedly. I think the drawer should only close when the mouse down and mouse up events are both on the overlay. Because in this case I was clearly interacting with the elements inside the drawer, but my cursor strayed slightly out of the drawer bounds and it closed.

**Steps to re-create**
1. Open a drawer element
2. click on the drawer element without releasing (mouse-up)
3. move cursor outside of the drawer (onto the grey overlay) and let go

**Comment by triskweline** [comment]
This is fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0), which was released today.

**Comment by MattApril** [comment]
Oh awesome, I will check it out. Thanks.
