### ISSUE TITLE
Hyperlinks frontpage

### ISSUE THREAD

**Issue by guettli** [unpoly/unpoly#144]
I already clicked on this place several times during the week :-) 

It would be nice if this would be a hyperlink.

![image](https://user-images.githubusercontent.com/414336/100359800-58043e00-2ff8-11eb-9ccb-29e0f6d010bf.png)

**Comment by triskweline** [comment]
The code for this page is here: https://github.com/unpoly/unpoly-site/blob/master/source/index.html.erb

A quick fix would be to assign the container the [`[up-expand]`](https://unpoly.com/up-expand) attribute.

**Comment by guettli** [comment]
Thank you. Looking again at this, my personal feeling is that the modal is not the simplest solution.

From a naive user perspective I think it would make sense that the <div> (pink circle in the image above) would be a normal hyperlink to http://192.168.178.80:4567/up.form (instead of a model pop-up).

**Comment by adam12** [comment]
@guettli are you still interested in submitting a patch for this?

I think for consistency, all the icons should be clickable if one is; but with that said, what URL should be used when the description contains more than one?

**Comment by guettli** [comment]
Yes, that's where I stopped. Since there is no clear image-->page relationship, I was unsure how to proceed.

Should I close it, since I won't work on it any more?

**Comment by adam12** [comment]
> Should I close it, since I won't work on it any more?

Let's close it for now.
