### ISSUE TITLE
Configuration format

### ISSUE THREAD

**Issue by sirinath** [unpoly/unpoly#145]
Instead of specifying the configuration through JS API can we have configuration in a file using JSON, YAML, TOML which can be specified in a `link` tag.

This way no JS needs to be used.

**Comment by adam12** [comment]
What's your objection to using JavaScript here?

**Comment by sirinath** [comment]
This will be more cleaner as you can still reduce the need of user  written JS.

**Comment by adam12** [comment]
I think that writing _some_ JavaScript shouldn't be frowned upon; to integrate support for anything other than JSON would require a dependency for parsing. And using JSON alone would require strange hacks to support things such as extending Array's.

I'm going to close this issue to keep tracker noise down, but I've tagged it as an enhancement in case we want to revisit in the future.

Cheers.
