### ISSUE TITLE
up.submit params not always submitted without `history: false`

### ISSUE THREAD

**Issue by mfazekas** [unpoly/unpoly#146]
We've used `submit` to implement basic autosave.

The logic is something like this:

```
up.observe(element, 
   throttle(
      () => up.submit(element, {target: '#autosave-output', params: {autosave: true}})
    )
)
```

this worked fine from `GET new` but it did not work for when rails create returned with validation error, so original request was a POST. 

We've obviously missed the `history: false` option from submit, but it might be a good idea to log some error message to console in such case. It took a bit time to find out why the `autosave` params was missing in such case.

https://github.com/unpoly/unpoly/blob/5f37100845adcf072407b35ec94d051c552628cf/lib/assets/javascripts/unpoly/form.coffee.erb#L253-L256

https://github.com/unpoly/unpoly/blob/5f37100845adcf072407b35ec94d051c552628cf/lib/assets/javascripts/unpoly/browser.coffee.erb#L65-L82

**Comment by adam12** [comment]
> log some error message to console

When it falls back to using `form.submit()`?

I'm inclined to say this is fixed in Unpoly 2.

https://github.com/unpoly/unpoly/blob/7fd79c9a0b5ba49f82dbe075e2d8c04154e1711e/lib/assets/javascripts/unpoly/classes/request/form_renderer.coffee#L39-L44

**Comment by mfazekas** [comment]
> When it falls back to using form.submit()?

Yes in that case.

I guess this issue can be closed.

**Comment by adam12** [comment]
> I guess this issue can be closed.

Let's keep it open for now, and close once Unpoly 2 gets cut.

**Comment by triskweline** [comment]
This should be fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0). If the issue persists, please re-open.
