### ISSUE TITLE
localstorage values disappear on link follow

### ISSUE THREAD

**Issue by mithereal** [unpoly/unpoly#15]
i have form vars stored in localstorage ie address:xxxxxxx
when i follow a link like 
   var $link = $('#start_quote'); 
      up.follow($link);
all that is left is the keys the values are nulled

**Comment by triskweline** [comment]
I'm afraid I cannot reproduce the issue.

Unpoly is not using `localStorage`.

Can you provide a minimal example to reproduce?

**Comment by mithereal** [comment]
sorry disregard i fixed the issue, however i have one that might be related or at least not documented i need to attach event handelers to a modal created with up-modal  the html which is loaded as a partial via vanilla  ajax  looks like this
<a href="/step4" up-modal="#room">
        <div class="room_block">
            <img src="">
            <label>Bed Room</label>
        </div></a>
the modal works but i cannot attach event handelers 
the modal thats inserted is 

<div id="move_editor" up-source="http://127.0.0.1:4000/editor">

<div id="current_rooms_block">
<div><label>My House</label></div>
        <div class="room_block grid">
            <img src="">
            <label>Living Room</label>
        </div>


            <div class="room_block">
                <img src="">
                <label>Bed Room</label>
            </div>


            <div class="room_block">
                <img src="">
                <label>Bed Room</label>

            </div>

            <div class="room_block">
                <img src="">
                <label>Bed Room</label>

            </div>
</div>

<div id="available_rooms_block grid">
    <div><label>Available Rooms</label></div>
    <div class="room_block">
        <img src="room.image">
        <label>Kitchen</label>

    <div class="room_block">
        <img src="room.image">
        <label>Bedroom</label>
</div>
</div>
    </div>
  </div>
</div>

the js i have tried is 
$(document).on("click",'.room_block', function(){
        alert('clicked');
    });
however it never fires
all my scripts are on a layout page the only thing i am changing is the content block with ajax

**Comment by triskweline** [comment]
Although the canonical way to hook up scripts in Unpoly is using [compilers](http://unpoly.com/up.compiler), I see no reason why your event handler wouldn't fire.

Are you sure the line `$(document).on(...)` is executed?
