### ISSUE TITLE
up-validate="selector" for radios and checkboxes not working

### ISSUE THREAD

**Issue by flihub** [unpoly/unpoly#150]
Hi using Version 0.62.1,

up-validate ignore selector element and replace whole .Inputfield content. Users cant not check fast checkboxes.

also set : 
up.form.config.validateTargets.unshift('.Inputfield:has(&)');

![image](https://user-images.githubusercontent.com/16720735/107808339-76b5dd80-6d7a-11eb-9638-644d2619a45c.png)

**Comment by adam12** [comment]
Can you enable logging and paste the log output here? `up.log.enable()` in your browser console.

**Comment by flihub** [comment]
![image](https://user-images.githubusercontent.com/16720735/107811731-af0bea80-6d7f-11eb-932d-3d1cd7b3256e.png)

**Comment by adam12** [comment]
> can we set up-delay with up-validate?

Not that I'm aware of, but you could probably build your own with `up.validate()` and a debounce mechanism (such as Lodash's `unbounce`).

**Comment by flihub** [comment]
ok thank you. fixed with remove up-validate parent div (think behave like form) and add up-validate to all checkboxes.
