### ISSUE TITLE
Prevent page update on back button event

### ISSUE THREAD

**Issue by aleh-z** [unpoly/unpoly#153]
Hello, I'm dealing with infinite scroll, when new items are appended to the feed on "more" button is pressed. Clicking on the item opens a modal window with new location hash. Then when I use back button whole page restore its state (with no extra items loaded). 
So here is the question, is it possible to prevent such behavior and NOT reloading the whole page on back button is pressed? Thanks.

**Comment by adam12** [comment]
Do you know if the infinite scroll is creating history items? Is there any cache invalidation headers being sent?

Unpoly will try to use the history API to pull pages from the cache (IIRC) but if it wasn't in the history API then there's a chance it has to be re-fetched.

**Comment by aleh-z** [comment]
Invisible scroll doesn't create history entries, here is the code: 
`<button up-href="@url" up-target="media-grid:after, .media__more" up-history="false" up-scroll-behavior="smooth">Load more</button>`

I've record video showing the problem: [link](https://monosnap.com/direct/2WKeO99FdnaomE52mjlx6vmIc43nJV)

Any ideas how to overcome this page reloading?

**Comment by adam12** [comment]
Can you enable debugging and then share the debug output? `up.log.enable()` in your browser console.

**Comment by aleh-z** [comment]
Here are captured logs: 
`Some messages have been moved to the Issues panel.
unpoly.js:7839 [UP] Framework booted (up:framework:booted)
unpoly.js:7900  __ _____  ___  ___  / /_ __
/ // / _ \/ _ \/ _ \/ / // /  0.62.1
\___/_//_/ .__/\___/_/\_. / 
        / /            / /

Call `up.log.disable()` to disable logging for this session.
unpoly.js:7839 [UP] Booting user application (up:app:boot)
unpoly.js:7868 [UP] Compiling fragment <body up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2" class=​"pace-running pace-running ">​…​</body>​
unpoly.js:7868 [UP] Compiling 'body' on 1 element(s)
unpoly.js:7868 [UP] Compiling '.ps-event-media__link' on 5 element(s)
unpoly.js:7839 [UP] Inserted fragment <body up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2" class=​"pace-running pace-running ">​…​</body>​ (up:fragment:inserted ({origin: undefined}origin: undefined__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()))
unpoly.js:7839 [UP] User application booted (up:app:booted)
unpoly.js:7839 [UP] Following link (up:link:follow)
unpoly.js:7839 [UP] Loading GET http://localhost:8080/events/peter-maffay-hamburg-2/media?next-page=0000000000000009900-66 (up:proxy:load ({request: o}))
unpoly.js:7839 [UP] Server responded with HTTP 200 (5834 bytes) (up:proxy:loaded ({request: o, response: i}))
unpoly.js:7868 [UP] Extracting .ps-event__media-grid:after, .ps-event__media__more from 5834 bytes of HTML
unpoly.js:7868 [UP] Swapping fragment .ps-event__media-grid
unpoly.js:7868 [UP] Compiling fragment <div class=​"row">​…​</div>​
unpoly.js:7868 [UP] Compiling '.ps-event-media__link' on 5 element(s)
unpoly.js:7839 [UP] Inserted fragment <div class=​"row">​…​</div>​ (up:fragment:inserted ({origin: button.ps-btn.ps-btn--gray.up-active}))
unpoly.js:7868 [UP] Swapping fragment .ps-event__media__more
unpoly.js:7868 [UP] Compiling fragment <div class=​"ps-event__media__more row" up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2/​media?next-page=0000000000000009900-66">​
    
  ​</div>​
unpoly.js:7839 [UP] Inserted fragment <div class=​"ps-event__media__more row" up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2/​media?next-page=0000000000000009900-66">​
    
  ​</div>​ (up:fragment:inserted ({origin: button.ps-btn.ps-btn--gray.up-active}))
unpoly.js:7839 [UP] Ignoring a state not pushed by Unpoly (null)
unpoly.js:7839 [UP] Opening modal (up:modal:open ({url: undefined}))
unpoly.js:7868 [UP] Extracting .ps-instagram-media-modal from 4012 bytes of HTML
unpoly.js:7868 [UP] Swapping fragment .ps-instagram-media-modal
unpoly.js:7868 [UP] Compiling fragment <div class=​"ps-instagram-media-modal" up-source=​"undefined">​…​</div>​
unpoly.js:7839 [UP] Inserted fragment <div class=​"ps-instagram-media-modal" up-source=​"undefined">​…​</div>​ (up:fragment:inserted ({origin: undefined}))
unpoly.js:7839 [UP] Modal opened (up:modal:opened)
unpoly.js:7839 [UP] Restoring location http://localhost:8080/events/peter-maffay-hamburg-2 (up:history:restore ({url: "http://localhost:8080/events/peter-maffay-hamburg-2"}))
unpoly.js:7839 [UP] Closing modal (up:modal:close)
unpoly.js:7839 [UP] Loading GET http://localhost:8080/events/peter-maffay-hamburg-2 (up:proxy:load ({request: o}))
unpoly.js:7839 [UP] Server responded with HTTP 200 (10813 bytes) (up:proxy:loaded ({request: o, response: i}))
unpoly.js:7868 [UP] Extracting body from 10813 bytes of HTML
unpoly.js:7868 [UP] Swapping fragment body
unpoly.js:7868 [UP] Compiling fragment <body up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2">​…​</body>​
unpoly.js:7868 [UP] Compiling 'body' on 1 element(s)
unpoly.js:7868 [UP] Compiling '.ps-event-media__link' on 5 element(s)
unpoly.js:7839 [UP] Inserted fragment <body up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2">​…​</body>​ (up:fragment:inserted ({origin: undefined}))
unpoly.js:7868 [UP] Restoring scroll positions for URL http://localhost:8080/events/peter-maffay-hamburg-2 to {html: 530}
unpoly.js:7839 [UP] Restored location http://localhost:8080/events/peter-maffay-hamburg-2 (up:history:restored ({url: "http://localhost:8080/events/peter-maffay-hamburg-2"}))
unpoly.js:7839 [UP] Modal closed (up:modal:closed)
`

**Comment by aleh-z** [comment]
Modal window is opened using up.modal.extract function with already defined html, because there is no need to make an AJAX call in my scenario.

**Comment by adam12** [comment]
This line is somewhat odd and stands out:

> unpoly.js:7839 [UP] Ignoring a state not pushed by Unpoly (null)

I'd have to build an example of this app to provide a better answer, but my immediate suggestion would be to see why Unpoly isn't using the page cache. This would be checking the headers for the page content returned. There is an event that you can listen on (`up:proxy:load`) that you could try preventing to see if it helps.

**Comment by aleh-z** [comment]
> This line is somewhat odd and stands out:

This is because I use history.pushState or window.loaction.hash to open modal window with new url. But using of unpoly functions to push new history entry doesn't change the situation, I've got the same result: back button returns me initial state of the page. 

Is far as I understand cache is used, but it just caches http response, not state of a page with appended extra data 
`unpoly.js:7839 [UP] Re-using cached response for GET http://localhost:8080/events/peter-maffay-hamburg-2`

Here are full logs:
```
unpoly.js:7839 [UP] Following link (up:link:follow)
unpoly.js:7839 [UP] Loading GET http://localhost:8080/events/peter-maffay-hamburg-2/media?next-page=0000000000000009900-66 (up:proxy:load ({request: o}))
unpoly.js:7839 [UP] Server responded with HTTP 200 (5834 bytes) (up:proxy:loaded ({request: o, response: i}))
unpoly.js:7868 [UP] Extracting .ps-event__media-grid:after, .ps-event__media__more from 5834 bytes of HTML
unpoly.js:7868 [UP] Swapping fragment .ps-event__media-grid
unpoly.js:7868 [UP] Compiling fragment <div class=​"row">​…​</div>​
unpoly.js:7868 [UP] Compiling '.ps-event-media__link' on 5 element(s)
unpoly.js:7839 [UP] Inserted fragment <div class=​"row">​…​</div>​ (up:fragment:inserted ({origin: button.ps-btn.ps-btn--gray.up-active}))
unpoly.js:7868 [UP] Swapping fragment .ps-event__media__more
unpoly.js:7868 [UP] Compiling fragment <div class=​"ps-event__media__more row" up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2/​media?next-page=0000000000000009900-66">​
    
  ​</div>​
unpoly.js:7839 [UP] Inserted fragment <div class=​"ps-event__media__more row" up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2/​media?next-page=0000000000000009900-66">​
    
  ​</div>​ (up:fragment:inserted ({origin: button.ps-btn.ps-btn--gray.up-active}))
unpoly.js:7839 [UP] Opening modal (up:modal:open ({url: "/modal"}))
unpoly.js:7839 [UP] Re-using cached response for GET http://localhost:8080/modal
unpoly.js:7868 [UP] Extracting .ps-page from 3263 bytes of HTML
unpoly.js:7839 [UP] Adding history entry for http://localhost:8080/modal (up:history:push ({url: "http://localhost:8080/modal"}))
unpoly.js:7839 [UP] Advanced to location http://localhost:8080/modal (up:history:pushed ({url: "http://localhost:8080/modal"}))
unpoly.js:7868 [UP] Swapping fragment .ps-page
unpoly.js:7868 [UP] Compiling fragment <div class=​"ps-page" up-source=​"http:​/​/​localhost:​8080/​modal">​…​</div>​
unpoly.js:7839 [UP] Inserted fragment <div class=​"ps-page" up-source=​"http:​/​/​localhost:​8080/​modal">​…​</div>​ (up:fragment:inserted ({origin: undefined}))
unpoly.js:7839 [UP] Modal opened (up:modal:opened)
unpoly.js:7839 [UP] Restoring location http://localhost:8080/events/peter-maffay-hamburg-2 (up:history:restore ({url: "http://localhost:8080/events/peter-maffay-hamburg-2"}url: "http://localhost:8080/events/peter-maffay-hamburg-2"__proto__: Object))
unpoly.js:7839 [UP] Closing modal (up:modal:close)
unpoly.js:7839 [UP] Re-using cached response for GET http://localhost:8080/events/peter-maffay-hamburg-2
unpoly.js:7868 [UP] Extracting body from 10813 bytes of HTML
unpoly.js:7868 [UP] Swapping fragment body
unpoly.js:7868 [UP] Compiling fragment <body up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2">​…​</body>​
unpoly.js:7868 [UP] Compiling 'body' on 1 element(s)
unpoly.js:7868 [UP] Compiling '.ps-event-media__link' on 5 element(s)
unpoly.js:7839 [UP] Inserted fragment <body up-source=​"http:​/​/​localhost:​8080/​events/​peter-maffay-hamburg-2">​…​</body>​ (up:fragment:inserted ({origin: undefined}))
unpoly.js:7868 [UP] Restoring scroll positions for URL http://localhost:8080/events/peter-maffay-hamburg-2 to {html: 547}
unpoly.js:7839 [UP] Restored location http://localhost:8080/events/peter-maffay-hamburg-2 (up:history:restored ({url: "http://localhost:8080/events/peter-maffay-hamburg-2"}))
unpoly.js:7839 [UP] Modal closed (up:modal:closed)
```

**Comment by aleh-z** [comment]
Here is live example: [Glitch live site](https://unpoly-back-btn-showewcas.glitch.me), and the code: [Glitch code](https://glitch.com/edit/#!/unpoly-back-btn-showewcas)

Steps to reproduce:
1. click "load more" button
2. click on "item 2" 
3. use browser back button

Expected result: "item 2" remains on the page (as if we click on modal closing cross)
Real result: "item 1" only is shown (back to page initial state)

**Comment by adam12** [comment]
Your example was helpful. I tweaked it to listen on proxy events to prevent loading, which appears to work: https://snapdragon-functional-snapper.glitch.me/

But I'm not sure if it's only working because of the JavaScript error 🙃 I'd need to build locally with source so I could look further and I may not be able to do that for some time.

**Comment by adam12** [comment]
I'm going to close this. If this is still an issue for you, it might be worth exploring the new Unpoly 2 release candidate and see if your issue persists.
