### ISSUE TITLE
`up-cache="false"` combined with `up-dash=".something"` results in two HTTP requests

### ISSUE THREAD

**Issue by scottwoodall** [unpoly/unpoly#154]
Potentially a bug; potentially working as intended but I wanted your thoughts. Given the following HTML markup:

```
<html lang="en">
    <head>
        <link rel="stylesheet" href="/static/unpoly/unpoly.min.css">
        <script src="/static/unpoly/unpoly.js"></script>
    </head>

    <body>
        <a href="/someurl/" up-cache="false" up-dash=".something">some link</a>
    </body>
</html>
```
This ends up making two HTTP requests; one during the mouse-over and then one on the actual click.

The initially caught me off guard; but after thinking a bit it's probably working as designed.

Should the click use the results from the mouse-over HTTP request or the results from the click?

**Comment by triskweline** [comment]
Sorry that this surprised you, but caching is required for preloading to work.
