### ISSUE TITLE
Close mobile navigation on click

### ISSUE THREAD

**Issue by radosslav** [unpoly/unpoly#156]
Hello. I read the whole documentation and cannot find how to close the mobile navigation panel on the standard Bootstrap 4 Navbar element after a click on any of the menu items.

**Comment by adam12** [comment]
I haven't tried it, but could you listen for the `up:link:follow` event and then close the navigation panel?

```javascript
up.on('up:link:follow', e => {
  const click = Event('click')

  document.querySelector('.navbar button').dispatch(click)
})
```

You might need to only listen on links followed from that navbar and not everything, or figure out a nicer way to hide the navbar without simulating a click.

**Comment by radosslav** [comment]
I will try it. Thank you!  For now, I just put two sets of links and hide one of them on mobile and vice versa.
