### ISSUE TITLE
i would suggest a feature to disable console banner...

### ISSUE THREAD

**Issue by okliv** [unpoly/unpoly#157]
hi.

https://github.com/unpoly/unpoly/blob/92330b52203f34fc3de50ac65fe8e1adbb761aa1/lib/assets/javascripts/unpoly/log.coffee#L203

it can be helpful to disable this noisy banner (if it is not a core feature to make things work)

thanks

**Comment by triskweline** [comment]
This could be a new option `up.log.config.banner = false`.

Would you like to make a PR for this?

**Comment by hfjallemark** [comment]
I added a PR for this: https://github.com/unpoly/unpoly/pull/159

**Comment by flihub** [comment]
import 'unpoly';

up.log.config.banner = false

not working banner still in console

![image](https://user-images.githubusercontent.com/16720735/117415917-8714c900-af21-11eb-9814-4215d77e0b68.png)

**Comment by adam12** [comment]
> not working banner still in console

Looks like the config is set too late.
