### ISSUE TITLE
CSS animasyonlarını kullanma

### ISSUE THREAD

**Issue by onur-km** [unpoly/unpoly#158]
**Does Unpoly support the use of CSS animations in page transitions?**

In short, can we listen to the "animationEnd" event and make transition effects between pages by preparing special animations with CSS?

Or do we have to use the animations defined in `Unpoly.js`?

**Comment by triskweline** [comment]
The predefined animations all use CSS transitions, not CSS animations.

You can however implement a transition effect using CSS animations by registering a custom transition function as described here:
https://unpoly.com/up.transition
