### ISSUE TITLE
Typo: Use jQuery instead of $

### ISSUE THREAD

**Issue by perifer** [unpoly/unpoly#16]
I think there is a typo in https://github.com/unpoly/unpoly/blob/master/lib/assets/javascripts/unpoly/util.coffee#L2099.  It should be `jQuery` and not `$` to make unpoly work with `jQuery.noConflict()`.

**Comment by triskweline** [comment]
You're right, good catch.

**Comment by triskweline** [comment]
Fixed in `master`.
