### ISSUE TITLE
Unknown Animation

### ISSUE THREAD

**Issue by ionurboz** [unpoly/unpoly#161]
This is how I defined following animations.

```js
...
}).call(this);
(function() {
  up.framework.boot();
}).call(this);

// --------- After up

(function() {
  up.animation('fade-in-move-from-top', function(element, options) {
    options = up.util.merge(options, {duration: 1250});
    element.style.opacity = 0;
    element.style.transform = 'translateX(-10px)';
    up.animate(element, { opacity: 1, transform = 'translateX(0)' }, options);
  });
  up.animation('fade-out-move-to-bottom', function(element, options) {
    options = up.util.merge(options, {duration: 1250});
    element.style.opacity = 1;
    element.style.transform = 'translateX(0)';
    up.animate(element, { opacity: 0, transform = 'translateX(-10px)' }, options);
  });
}).call(this);
```
Link is also like this,

```html
<a href="/" up-target="main" up-transition="fade-out-move-to-bottom/fade-in-move-from-top">Go</a>
```

And I am getting this error.

![image](https://user-images.githubusercontent.com/5174447/116086105-22977580-a6a8-11eb-836d-19f479617ec1.png)

Where am I making a mistake?

**Comment by triskweline** [comment]
This looks correct.

**Comment by ionurboz** [comment]
> This looks correct.

If turning on debug mode will help you, I can share a log like that :)

**Comment by triskweline** [comment]
I may be able to help if you provide a glitch.com app that reproduces the issue.

**Comment by ionurboz** [comment]
@triskweline 

First of all, thank you for your interest, I found the problem I mentioned above. A typo!

Animation is currently running, but it only has an effect on "`newElement`". It has no effect on "`oldElement`" because it cannot create the element named "`.up-bounds`".


In this case I still seem to be making a mistake somewhere. Here is a working live demo and a repository where you can review codes.

- https://unpoly.netlify.app/
- https://github.com/bozdev-tempspace/unpoly.temp

**Comment by triskweline** [comment]
@ionurboz Your transition function should `return` the `Promise.all(...)` expression.
