### ISSUE TITLE
Trigger factor of "up:proxy:{*}" events

### ISSUE THREAD

**Issue by ionurboz** [unpoly/unpoly#162]
### Trigger factor of `up:proxy:{*}` events

The following events are triggered by many factors such as `up-preload, up-autosubmit, up-validate, up-target, up-follow`.

```js
up:proxy:load
up:proxy:loaded
up:proxy:slow
up:proxy:recover
```

But for example

- If we want to show a feature such as a progress bar only when the user clicks on links and the "up:proxy:slow" event occurs,
- If we show a rotating flat loader when the user submits a form.

I cannot make this distinction.

Even worse, when I show and hide a progress bar with the "up:proxy:load" and "up:proxy:loaded" events. The user sees this progress bar even though he did not click along with the "up-preload".

This is what I want to say:

```js
up.on(document, 'up:proxy:slow', function(event){
   if(event.factor == 'up-target') progress.show();
   if(event.factor == 'up-validate') circleLoader.show();
   if(event.factor == 'up-preload') // free as a baby
});
up.on(document, 'up:proxy:loaded', function(event){
   if(event.factor == 'up-target') progress.hide();
   if(event.factor == 'up-validate') circleLoader.hide();
});
```

**Comment by triskweline** [comment]
I don't see this happening for `up:proxy:slow`, since multiple requests with different "factors" may be slow and we only emit the event once until the queue has cleared up again. It may be possible for `up:proxy:load`, `up:proxy:loaded` and `up:proxy:fatal` events to expose their `{ origin }` element (link or a form) so a developer can build a similar behavior themselves.

BTW, preload events never trigger `up:proxy:slow`.

**Comment by ionurboz** [comment]
> It may be possible for up:proxy:load, up:proxy:loaded and up:proxy:fatal events to expose their { origin } element (link or a form) so a developer can build a similar behavior themselves.

💯 👍 

Thank you for your interest. I will be looking forward to this.

**Comment by flihub** [comment]
u can use up:proxy:load event and catch by request header.
i only need target or validate difference so my code like this.

```javascript
up.on('up:proxy:load', function (event) {
    var targets = event.request.target;
    var validate = event.request.headers["X-Up-Validate"];

    if (!targets) return;

    targets.split(", ").forEach(el => {
        var element = document.querySelector(el);

        if (element) {
            element.classList.add(validate ? 'up-validating' : 'up-loading');
        }
    });
})
```

**Comment by ionurboz** [comment]
@flihub 
Good solution. thanks i will try.

**Comment by triskweline** [comment]
This is an old issue. The `up:request:load` and `up:request:loaded` events now have many properties like `event.origin` or `event.request.headers` that should help with getting more context in a listener.
