### ISSUE TITLE
Missing up-switch radio button documenation

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#163]
targets for `up-switch` using radio buttons need to have the name of the radio buttons.

example (works, tested on codepen)

```html
  <input type="radio" name="flag" value="active"   up-switch=".target">
  <input type="radio" name="flag" value="disabled" up-switch=".target">
  <input type="radio" name="flag" value="inactive" up-switch=".target">

  <div class="target" name="flag" up-show-for="active">
    active
  </div>

   <div class="target" name="flag" up-show-for="disabled">
    disabled
  </div>
  
  <div class="target" name="flag" up-show-for="inactive">
    inactive
  </div>
```

i'm using `name="flag"` on the target divs, but i don't see this in the documentation, if i remove the `name` on the targets, then `up-switch` never hides my targets.
i discovered this via reading the source, specifically `switcherValues = function(field) {` line (i'm just reading the compiled js, not coffee).

**Comment by adam12** [comment]
I wasn't able to reproduce. I removed the `name="flag"` from all `div` elements and it still seems to function correctly.

Can you confirm my pen looks correct? https://codepen.io/adam12/pen/OJWeGBK

**Comment by boxxxie** [comment]
https://codepen.io/boxxxie/pen/abpgxaE

**Comment by adam12** [comment]
I'm going to close this for now. If you can create a reproducible example that would be great.
