### ISSUE TITLE
A repository of interesting unpoly compilers

### ISSUE THREAD

**Issue by philippejadin** [unpoly/unpoly#171]
... would be great!

For instance this compiler : https://makandracards.com/makandra/52361-unpoly-loading-large-libraries-on-demand
-> It could be reworked a bit, and made into an "official" compiler from an official repository of compilers. 

The repository could simply be a github repository where unpoly maintainer would accept pull request from others.

I think it would help and ease adoption.

**Comment by adam12** [comment]
Interestingly, I'd almost prefer your example to ship with Unpoly. It seems common enough to be copied to multiple projects.

`up.loadScript` or something.

**Comment by philippejadin** [comment]
Yes my example is not that good, and would not even be a good candidate for a compiler, but I still guess that there are a lot of good compilers out there that would benefit everyone.

**Comment by adam12** [comment]
I like the concept of this. I think an open source demo app would help a bit here too (but that's probably another issue).

Here's a search across most of the projects I'm using Unpoly on, with duplicate compiler selectors eliminated.

```
up.compiler('#segment-identity') // Trigger Segment analytics
up.compiler('#segment-page') // Trigger Segment analytics
up.compiler('[data-badge]') // Tinycon badge (bubble icon in favicon)
up.compiler('[data-chart]') // c3 chart setup
up.compiler('[datepicker]') // Self explanatory
up.compiler('[pinnable]') // Dragula drag/drop
up.compiler('[range-datepicker]') // Self explanatory
up.compiler('[track-click]') // Trigger Segment event tracking
up.compiler('[up-copy-to-clipboard]') // Self explanatory
up.compiler('[up-csrf-token]') // Steal CSRF token from meta tag
up.compiler('[up-fetch]') // Load via Unpoly and replace element
up.compiler('[up-nav]') // I believe this sets ARIA attributes if I remember correctly
up.compiler('[up-refresh]') // v1 up-poll
up.compiler('[up-reload]') // v1 up-poll
up.compiler('[up-replace]') // up-fetch as above
up.compiler('[up-sticky-pins]') // Dragula drag/drop
up.compiler('button#test') // Does up-validate
up.compiler('button[up-confirm]') // window.confirm
up.compiler('select[up-nav]') // I don't remember
```

At least 4 of those are probably the same or so similar they could be the same. I'm not sure how great of examples the rest would make, but I authored almost all of those, so it would be hard for me to gauge interest on something I already completed :)

Did you want to post this to [the group](https://groups.google.com/g/unpoly)? Maybe get feedback there, and then we can see what Henning thinks.

**Comment by philippejadin** [comment]
just posted :-)

**Comment by adam12** [comment]
> just posted :-)

Great. I'm going to close this for now and we can figure out later if it needs re-opening or an action item. Cheers.
