### ISSUE TITLE
Gloval xhr event

### ISSUE THREAD

**Issue by jmmendivil** [unpoly/unpoly#172]
Hi there, great work on this lib, thanks

I would like to implement a loading indicator and I wonder if there's a public way to get the _onprogress_ event of the xhr or what would be the recommended way to do it with unpoly?

**Comment by adam12** [comment]
Hello!

Unpoly publishes events for it's XHR requests. You can display a loading indicator for all of them using something like `up:proxy:load` and `up:proxy:loaded`, or only fire for slow requests using `up:proxy:slow` and `up:proxy:recover`. The [up:proxy:slow](https://unpoly.com/up:proxy:slow) event has an example.
