### ISSUE TITLE
Can't set a fail-target different to target for validation

### ISSUE THREAD

**Issue by pfw** [unpoly/unpoly#174]
We have some forms which are using server side validation which works very nicely - mostly...

For individual fields we are using `up-validate="& + .errors"` to populate an error next to the input when validation on that field fails.

For the form itself we have `up-fail-target=".system-error"` which shows the error in a banner if something 'bad' happened.

However, if something 'bad' happens during validation the only place for an error to go is into the error text next to a field which isn't ideal. This appears to happen due to this:

in master:
    # The protocol doesn't define whether the validation results in a status code.
    # Hence we use the same options for both success and failure.
    options.fail = false

and in v1:
      options.failTarget = options.target;

<img width="302" alt="Screen Shot 2021-06-03 at 9 43 57 pm" src="https://user-images.githubusercontent.com/92163/120639561-d3b5da80-c4b4-11eb-89af-1c9e9f8f7bc8.png">

Is there a way to work around this, I can't see one but reaching, or could it be made to be possible?

**Comment by adam12** [comment]
Can you use `up-hungry` on your `.system-error` element? I haven't tried it personally but it seems like it would work.

On v2 (master), I think you can set the fail target. `up.fail_target =  [up.fail_target, ".system-error"].join(",")` possibly. Again, untested. I'd probably still prefer `up-hungry` in this case.

**Comment by pfw** [comment]
Great - thanks Adam - that looks like it will do the trick. I've not used up-hungry before either but it does fit nicely in not having to use any Javascript. 

I'll have a look at some text additions on the validate docs that might mention this as something to be aware of.

**Comment by adam12** [comment]
Cool! Let's close this for now. Additions to docs are definitely appreciated! :+1:
