### ISSUE TITLE
Updating <title> element and inline SVG icons

### ISSUE THREAD

**Issue by Dodger77** [unpoly/unpoly#18]
If the source of a requested site contains inline SVG with `<title>` elements, unpoly does not fetch the content of the `<title>` element in `<head>` but the one of the first inline SVG.

**Comment by triskweline** [comment]
This is related to #14 and already fixed in `master`. Will be released soon.

**Comment by Dodger77** [comment]
Thanks for the quick response!

**Comment by triskweline** [comment]
Fixed in `0.35.0`.
