### ISSUE TITLE
Unpoly replace events?

### ISSUE THREAD

**Issue by onur-km** [unpoly/unpoly#182]
Any request has been fulfilled and after the server has responded,

- Dom will change
- Dom has changed

events should be. I couldn't find it?

**Comment by adam12** [comment]
The closest events in v1 would be [`up:fragment:inserted`](https://unpoly.com/up:fragment:inserted) and [`up:fragment:destroyed`](https://unpoly.com/up:fragment:destroyed), but they both fire after the DOM has been changed.

Unpoly v2 has an event for `up:fragment:loaded`.

What are you looking to do?

**Comment by onur-km** [comment]
@adam12 thank you I'll try it
