### ISSUE TITLE
upgraded to 2.0.0, having problems with up-transition

### ISSUE THREAD

**Issue by minkoonim** [unpoly/unpoly#187]
when following a link with transition, 
erros happens and old layer doesn't get destroyed.
new and old one exists at the same time.

`<main>i'm new layer with new contents</main>`
`<up-bounds style="left: 0px; top: 0px; width: 1077.78px; height: 1363.33px;">`
`<main id="main" up-main="" class="up-destroying" aria-hidden="true" style="position: relative; inset: auto; width: 100%;height: 100%;"></main>`
`</up-bounds>`

log:

unpoly.js:5 up:app:boot Booting user application
unpoly.js:5 up.hello() Compiling fragment <body up-source=​"/​">​…​</body>​
unpoly.js:5 up.hello() Compiling "[upflw]" on 11 element(s)
unpoly.js:5 up.hello() Compiling "aside" on 1 element(s)
unpoly.js:5 up.hello() Compiling ".floating" on 1 element(s)

unpoly.js:5 up:fragment:inserted Inserted fragment <body up-source=​"/​">​…​</body>​
unpoly.js:5 up:link:follow Following link
unpoly.js:5 up:request:load Loading GET /collection/
unpoly.js:5 up:request:loaded Server responded HTTP 200 to GET /collection/ (5350 characters)
unpoly.js:5 up:fragment:loaded Loaded fragment from successful response to GET /collection/
unpoly.js:5 up.render() Updating "[up-main='']" in root layer
unpoly.js:5 up:location:changed Advanced to location /collection/
unpoly.js:5 up:fragment:keep Keeping fragment <header up-keep>​…​</header>​
unpoly.js:5 up:fragment:keep Keeping fragment <aside up-keep>​…​</aside>​
unpoly.js:5 up:fragment:keep Keeping fragment <div class=​"sub_sidenav" up-keep>​…​</div>​
  
  flex

unpoly.js:5 up.morph() Morphing <main id=​"main" up-main class=​"up-destroying" aria-hidden=​"true" style=​"position:​ relative;​ inset:​ auto;​ width:​ 100%;​ height:​ 100%;​">​…​</main>​ to <main id=​"main" up-main up-source=​"/​collection/​" tabindex=​"-1" class=​"up-focusable-content">​…​</main>​ with transition move-left
unpoly.js:5 up:fragment:kept Kept fragment <header up-keep>​…​</header>​
unpoly.js:5 up:fragment:kept Kept fragment <aside up-keep>​…​</aside>​
unpoly.js:5 up:fragment:kept Kept fragment <div class=​"sub_sidenav" up-keep>​…​</div>​
  
  flex

unpoly.js:5 up.hello() Compiling fragment <main id=​"main" up-main up-source=​"/​collection/​" tabindex=​"-1" class=​"up-focusable-content">​…​</main>​
unpoly.js:5 up.hello() Compiling "[upflw]" on 2 element(s)
unpoly.js:5 up.hello() Compiling ".floating" on 1 element(s)
unpoly.js:5 up:fragment:inserted Inserted fragment <main id=​"main" up-main up-source=​"/​collection/​" tabindex=​"-1" class=​"up-focusable-content">​…​</main>​

unpoly.js:5 Uncaught (in promise) TypeError: l(...).then is not a function

**Comment by minkoonim** [comment]
after looking at script, tried 'up-scroll': false, and it works fine.
maybe problem with morphing function's restore scroll option?

**Comment by triskweline** [comment]
This is fixed in 2.0.1.
