### ISSUE TITLE
Upgrading to Unpoly 2 compilers are not initialising on fresh page load

### ISSUE THREAD

**Issue by tmbenhura** [unpoly/unpoly#189]
Compilers are not running on fresh load of a page, but will run after fetch clicking a link. 
The debug log shows: 
```
up.hello() Compiling fragment <BODY CONTENT>
up:fragment:inserted <BODY CONTENT>

```
the compilers for nested DOM elements are not executed.

The application doesn't require the migration shim. If I use the migration shim.
```
import 'unpoly/unpoly.css'
import 'unpoly/unpoly.js'
import 'unpoly/unpoly-migrate.js'
```

an error is logged in the console:

Uncaught TypeError: up.link.targetMacro is not a function, referencing the corresponding line given below:
```
  up.migrate.renamedEvent('up:popup:close', 'up:layer:dismiss');

  up.migrate.renamedEvent('up:popup:closed', 'up:layer:dismissed');

  up.link.targetMacro('up-popup', {
    'up-layer': 'new popup'
  }, function() {
    return up.migrate.deprecated('[up-popup]', '[up-layer="new popup"]');
  });

```

**Comment by adam12** [comment]
It works fine on v1?

What does the `script` tag look like when rendered to the HTML? and in what element is it? `head`? or is it in the body at the somewhere (where?).

**Comment by triskweline** [comment]
> Compilers are not running on fresh load of a page, but will run after fetch clicking a link.

Are you loading your compilers asynchronously after the page was loaded?

Please provide a page on CodePen or glitch.com with a minimal setup that reproduces the issue.

> Uncaught TypeError: up.link.targetMacro is not a function, referencing the corresponding line given below:

This is a bug in the migration shim which affects all `[up-popup`] links.

There will be a bugfix release in the next days. Until then a workaround is to run the following code **after** `unpoly.js` was loaded but **before** `unpoly-migrate.js` is loaded:

```
Object.defineProperty(up.link, 'targetMacro', { get: function() { return up.migrate.targetMacro } })
```

**Comment by tmbenhura** [comment]
I was originally using version 0.62.1 and have realised that even if I
downgrade from 2.0.0 to 1.0.0 the same behaviour occurs, save for the error
in the logs.

The tag is rendered in head.

**Comment by adam12** [comment]
> The tag is rendered in head.

Does it have an `async` or `defer` attribute? If it does, I'd try to reproduce the issue without them. I'm thinking you might be affected by [this change](https://github.com/unpoly/unpoly/commit/889fb68379ec14e09768095716fdc8f0881db4cc).

**Comment by tmbenhura** [comment]
Great catch! The whole script was deferred. U2 is now working correctly.
