### ISSUE TITLE
How do i get unpoly-migrate.js

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#194]
### Bug description

https://unpoly.com/changes/upgrading
https://unpoly.com/changes/2.0.0

these links talk about upgrading using `migrate.js` ,  

https://unpoly.com/install doesn't give links to the files, and doesn't mention migrate.js

my only guess is that i can get it from the CDN, but the install page makes me think there are some compiled resources somewhere, though i can't find them.

maybe npm contains these files, but it seems like a very heavyweight solution to put 3 files in my project.

**Comment by adam12** [comment]
I remember having to append `-migrate` to the CDN URL a few weeks ago, and meant to bring it up. Here's a URL where you can download: https://unpkg.com/unpoly@2.0.1/unpoly-migrate.min.js

I think we should add this to the CDN docs, so I'm going to label it as such.

**Comment by boxxxie** [comment]
turns out npm does contain the distribution files. I think it would be a great convince to add these files to the /dist folder in the project

i personally don't use npm for projects/build. i'm sure many devs don't (not everyone is a backend nodejs dev who spends their life reading about how to configure webpack). for now i'm just manually moving these npm files to my forked unpoly dist folder.

**Comment by boxxxie** [comment]
i can confirm that the CDN works with migrage.min.js
