### ISSUE TITLE
form[method="patch/delete/etc..."] not respected

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#195]
### Bug description

forms seem like they only allow for POST and GET

<https://unpoly.com/a-up-follow#up-method>
```
[up-method='get'] OPTIONAL
The HTTP method to use for the request.

Common values are get, post, put, patch and delete. `The value is case insensitive.

The HTTP method may also be passed as an [data-method] attribute.
```

i know the up-method is on links, but i think it should be on form as well.

when using `<form mthod="patch">` POST is made, same with delete and i assume all the other http methods cept GET/POST
`<form up-method="patch">` does POST too, and sends some `_method` data in my payload, which is interesting and something i can use as a workaround, but not what i expected.

**Comment by boxxxie** [comment]
seems like this may be a browser issue, my `<form method>` without unpoly isn't being respected either.

**Comment by adam12** [comment]
This is a browser limitation.

As you noticed, the `_method` form value is used to get around this, which is seemingly become a standard among many web frameworks. It's [overridable](https://unpoly.com/up.protocol.config#config.methodParam) on Unpoly's side should the default not work for you. 

I'm not sure there's much more Unpoly can do here, so I'm going to close for now.

**Comment by boxxxie** [comment]
documentation could be updated.

**Comment by adam12** [comment]
> documentation could be updated.

Sounds good to me. Any interest in submitting a PR for this? Maybe we could expand `up-method` docs to discuss how it uses the `_method` form value to simulate verbs other than `GET` and `POST`.
