### ISSUE TITLE
Use of eval

### ISSUE THREAD

**Issue by OvermindDL1** [unpoly/unpoly#22]
Added unpoly directly to my bundler however it is failing minification due to use of eval in multiple scopes, thus it is not able to minimize properly.

The eval's are *all* of the form of:
```javascript
knife: eval(typeof Knife !== "undefined" && Knife !== null ? Knife.point : void 0),
```
8 of them specifically.

There is no `Knife` defined anywhere in the output code nor does the `knife` in the returned object seem to be used anywhere in the output code.  It does not seem to be referenced in the documentation anywhere either.

What is the point of `knife` or `Knife` in the dist code as it does not seem to be used in any form, and could it be removed in the distributed code as the `eval`'s are wrecking havoc with minification.

**Comment by triskweline** [comment]
We're using `Knife` in our [tests](https://github.com/unpoly/unpoly/tree/master/spec_app/spec/javascripts/up). It allows us to [mock symbols in closures](https://makandracards.com/makandra/34917-pierce-through-javascript-closures-and-access-private-symbols).

The code above should return `undefined` if there is no `Knife` in the current scope. Why does it break your minifier? We have successfully minified this code using both Sprockets and Webpack.

**Comment by OvermindDL1** [comment]
> The code above should return undefined if there is no Knife in the current scope. Why does it break your minifier? We have successfully minified this code using both Sprockets and Webpack.

I'm using google closure, it is causing issues in it.

Specifically, since the `Knife` can be defined at global scope before including unpoly it cannot optimize it out, and since it cannot be optimized out then it cannot assume what will be passed in to eval, and since it cannot assume what will be passed in to eval, since eval lives inside the functions then it has to assume that the local environment is available to the eval, which means that it cannot remove, condense, and inline lines of code.

There is a similar issue with the eval for handling strings as well of:
```javascript
      if (u.isString(rawCallback)) {
        callback = function(value, $field) {
          return eval(rawCallback);
        };
```
Since that eval is run in that scope then everything at that point is passed by the javascript VM as the environment into when `rawCallback` is run, which is causing reduction and renaming issues as well since it cannot assume what is used in that callback.  This problem is solvable (and I've done so) by hoisting the eval call to the global scope, just changing the start of unpoly.js from being:
```javascript
/**
@module up
 */

(function() {
  window.up = {
    version: "0.36.2",
...
```
To being:
```javascript
/**
@module up
 */
var global_eval = eval;
(function() {
  window.up = {
    version: "0.36.2",
...
```
Will capture the environment for the eval at that scope, then you can change the above eval code to be:

```javascript
      if (u.isString(rawCallback)) {
        callback = function(value, $field) {
          return global_eval(rawCallback);
        };
```
And it solves that issue as well thus allowing renaming and minification to happen at full bore.
You can also use the Function constructor like it is an `eval` but it always runs in global scope.  This is usually preferable nowadays and is what I'm doing:
```javascript
        callback = function(value, $field) {
          return (new Function(rawCallback))();
        };
```

Also, `(this)` should not be called at global scope, as it is done in a *large* number of places in the output `unpoly.js` file, I replaced all these with `window` as I'm guessing that is what would be assumed from what I'm looking at in the code (even though that is not what would happen, it would have become `undefined` at run-time).

Although all of this is not an issue if there is a file output that is ES6 modules instead of ES5 that I've been unable to find.  ^.^

> We're using Knife in our tests. It allows us to mock symbols in closures.

Since it is only being used in tests, then this code definitely should not be included in the final output at all.  ^.^;

&nbsp;

Also some other notes, there is a duplicate `isDetached: isDetached` in the object started at line 2365 of version `0.36.2`, this is invalid in strict mode and is throwing an error at this point, I had to comment out the second copy of the line (one is near the start of the object, the other is nearer to the end).

Also there, is a *HUGE* amount of invalid JSDoc tags, it is causing my build system to throw a rather monstrous fit (thousands of lines of warnings spewed out), of the form of (but of a large variety of selectors):
```javascript
Input_0:11518 (JSC_PARSE_ERROR)
Parse error. illegal use of unknown JSDoc tag "selector"; ignoring it
    is removed and the [`up-current`](/up-current) class is added:

        <a href="/foo" up-follow class="up-current">Foo</a>

    @selector .up-active
    ^
    @stable
     */

    /**

Input_0:11519 (JSC_PARSE_ERROR)
Parse error. illegal use of unknown JSDoc tag "stable"; ignoring it

        <a href="/foo" up-follow class="up-current">Foo</a>

    @selector .up-active
    @stable
    ^
     */

    /**
    Marks the given element as no longer loading, by removing the CSS class [`up-active`](/up-active).

Input_0:11531 (JSC_PARSE_ERROR)
Parse error. illegal use of unknown JSDoc tag "internal"; ignoring it

    @function up.feedback.stop
    @param {jQuery} event.$element
      The link or form that has finished loading.
    @internal
    ^
     */
    stop = function(elementOrSelector) {
      var $element;
      $element = findActionableArea(elementOrSelector);
```

For note, the system is ncompilable in V8 high strict modes due to a extra errors of:
```javascript
Input_0:14 (JSC_UNDEFINED_VARIABLE)
variable up is undeclared
(function() {
  window.up = {
    version: "0.36.2",
    renamedModule: function(oldName, newName) {
      return typeof Object.defineProperty === "function" ? Object.defineProperty(up, oldName, {
                                                                                 ^
        get: function() {
          up.log.warn("up." + oldName + " has been renamed to up." + newName);
          return up[newName];
        }

Input_0:592 (JSC_UNDEFINED_VARIABLE)
variable jQuery is undeclared
    @return {Boolean}
    @stable
     */
    isJQuery = function(object) {
      return object instanceof jQuery;
                               ^
    };

    /**
    Returns whether the given argument is an object with a `then` method.

Input_0:4711 (JSC_UNDEFINED_VARIABLE)
variable jasmine is undeclared
        return replace(currentUrl(), {
          force: true
        });
      };
      if (typeof jasmine !== "undefined" && jasmine !== null) {
                 ^
        register();
      } else {
        setTimeout(register, 100);
      }

Input_0:9108 (JSC_UNDEFINED_VARIABLE)
variable $element is undeclared
      });
      if (switcher) {
        return $(switcher);
      } else {
        return u.fail('Could not find [up-switch] field for %o', $element.get(0));
                                                                 ^
      }
    };

    /**
```

For the various issues I decorated the `up`'s with `window.up`, changed `jQuery` to `window.jQuery`, and I have no clue wtf jasmine is so I just removed that entire if statement and replaced it with just it's else branch.  A proper way to handle these would be linking them in via ES6 modules as they could then be used in any scope and would have defined linkages instead of being unknown, but there is no sign of ES6 anywhere that I can find here, so I left that be to minimize my necessary edits.

As for that `$element` undeclared, I'm not sure what code that was supposed to be, I really cannot find `$element` that should be in scope for it, so I just replaced it with `switcher` and changing it to take the string.

After a lot of fixing up of the source I finally got it compiling in high strict mode.

For note, these are the sizes of the files at various times:
379K unpoly.js - without jQuery
87K unpoly.min.js - without jQuery
2.1M unpoly.js - with jQuery 3.2.1 included
172K unpoly.gcc.js - with jQuery 3.2.1 included (jQuery is quite well made, it minimizes wonderfully)
150K unpoly.gcca.js - with jQuery 3.2.1 included - high strict - (jQuery has no issues with high strict mode)

And loading time is measurably less after going through closure as well.

I can send my copy if you are curious and you can diff it to see my changes (I changed some comments too because I was too lazy to clean up my `sed` changes), but it would be significantly better if this were a proper ES6 module so it could be linked in properly (plus there is plenty of things that can translate from ES6 to ES5, but by not using ES6 to start then a lot of performance and minification enhancements are lost)

**Comment by OvermindDL1** [comment]
And for note, there is coffeescript -> ES6 transpilers out, would be nice to have a, say, es6 directory with all of those transpiled in the npm distribution.  ^.^

Still need things like the global jQuery access (even window.jQuery is fine, although `import jQuery from 'jquery'` would be best for ES6), invalid $element, and 'this's and such fixed or it will not be valid ES6.

**Comment by triskweline** [comment]
> but it would be significantly better if this were a proper ES6 module so it could be linked in properly

I'm planning to convert the codebase to ES6 eventually, but there's a mountain of work required for that. Aside from converting the source itself, it will require major changes to the way we run tests and build releases.

> Also there, is a HUGE amount of invalid JSDoc tags

We're not documenting with JSDoc. Any attempt to parse it at such will fail.

> As for that $element undeclared, I'm not sure what code that was supposed to be, I really cannot find $element that should be in scope for it, so I just replaced it with switcher and changing it to take the string.

That should be `$target`. It's now changed in `master`.

> there is a duplicate isDetached: isDetached in the object started at line 2365 of version 0.36.2, 

Thanks, that's now changed in `master`.

**Comment by OvermindDL1** [comment]
> We're not documenting with JSDoc. Any attempt to parse it as such will fail.

The google closure compiler uses JSDoc tags to 'type' the arguments and returns of functions so it can better optimize, it is gcc that is complaining there.  :-)
Here is the documentation on all this for GCC:
https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler
https://github.com/google/closure-compiler/wiki/Using-JSDoc-Annotations-with-Closure-compiler
https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System

The JSDoc style comments are also used by other things for various purposes as well.  Perhaps just changing all `/**` to just `/*` would fix it as they would then be normal comments and not JSDoc comments (and thus stop tens of thousands of lines of gcc output ^.^).

> That should be $target. It's now changed in master.
> Thanks, that's now changed in master.

Whoo, those were the big big things breaking things, from here it is simple replacements that I can deal with now.  Thanks much!

**Comment by triskweline** [comment]
No one seems to want to tackle the remaining points in this issue, so I'm closing.

**Comment by triskweline** [comment]
Unpoly 0.54.1 ships build files without `eval` and uses a different kind of documentation comment.
