### ISSUE TITLE
V1: Polling method bug

### ISSUE THREAD

**Issue by bozdevs** [unpoly/unpoly#236]
I applied the below answers to my project.

- https://github.com/unpoly/unpoly/issues/63#issuecomment-419403770
- https://github.com/unpoly/unpoly/issues/63#issuecomment-645093468

```js
    <script>
      up.compiler('[poll]', (element) => {
        let interval = parseInt(element.getAttribute('poll') || 5000);

        let timer = setInterval(() => {
          // Don't reload when document is hidden.
          if (!document.hidden) {
            up.reload(element);
          }
        }, interval);

        return function () {
          clearInterval(timer);
        };
      });
    </script>
```

- When we open any "layer" (Modal, Pop-up), it closes these layers when it makes a new request to poll.
- After that the relevant modal trigger will not work and will cause an error like the image below.

![image](https://user-images.githubusercontent.com/5174447/125857926-a02659b7-ccaa-4611-9d58-14a644689ef1.png)

```
[UP] Missing { parent } option
```
- As a result, every time we click on the modal button from now on, it adds a copy of the polls content below.
![image](https://user-images.githubusercontent.com/5174447/125857268-12aed2a7-f912-43c8-880e-97efa1895dd8.png)

#### Here is the link you can check

- Live site: https://past-bird-firefly.glitch.me
- Code: https://glitch.com/edit/#!/past-bird-firefly

> There is probably a solution to this problem. I know V2 has this feature built in. But I need to stay in v1.

-------

> I added the "up-poll" feature in v2 to the "up.radio" module one by one. The situation is still the same (It works fine, but this error persists). It even starts making a request in 10ms (if the modal opens) even if I set 1000ms this time, probably because of (Promise)! I think it's because the number of queries increases for each <element up-poll> added below.

**Please help. How do we solve this?**

**Comment by adam12** [comment]
Not ideal, but forcing the layer causes it to function correctly.

```javascript
up.reload(element, { layer: "page" });
```

**Comment by bozdevs** [comment]
> Not ideal, but forcing the layer causes it to function correctly.
> 
> ```js
> up.reload(element, { layer: "page" });
> ```

Yes that definitely worked. "Why is this not ideal?" So could it cause other problems in the future? Or can I use it with peace of mind?

Yardımınız için teşekkürler. Mükemmelsin @Unpoly.

**Comment by adam12** [comment]
> "Why is this not ideal?"

It presumes that the element being reloaded is on the `page` layer, which works for your example but might break if you used `poll` in a modal. So I'm sure it would work for many cases but isn't guaranteed.

You might be able to fix this by applying the current layer to the element through `up.macro`, if you ran into any issues. Or just be aware of the caveat that inside modals it might be broken. Could possibly look back up through the DOM to see if the current element is inside an `.up-modal` element as well. I didn't test either solution tho.

**Comment by triskweline** [comment]
Thank you @bozdevs for providing the Glitch project and @adam12 for suggesting a workaround.

Inconsistent behavior when updating fragments with multiple layers was one of the motivation for the Unpoly 2 rewrite. An update is recommended. We provide [`unpoly-migrate.js`](https://unpoly.com/changes/upgrading) to assist with the switch.

Closing this issue now.
