### ISSUE TITLE
Browser back does not use the same target as the link to the current page

### ISSUE THREAD

**Issue by tmbenhura** [unpoly/unpoly#237]
### Browser back does not use the same target as the link to current page

This is noticeable when using 2 drastically different page layouts, for example A (a general layout) and B (a minimalist layout). Linking from A to B using the body element as the target, correctly updates the page, but when you use the browser back button the [up-main] of B is updated with content of the previous fragment instead of updating the body tag.

### Reproduction project

Use https://cat-grandiose-wolfberry.glitch.me/index.html to try it. And, https://glitch.com/~cat-grandiose-wolfberry to remix.

### Expected behaviour

Since body was the target from A to B, the body should be the target back from B to A.

**Comment by adam12** [comment]
Thank you for providing a reproduction!

I'm really not sure if this is a bug, so I'll leave it to Henning to determine that, but just as an FYI, you can fix this by changing the restore targets with `up.history.config.restoreTargets.unshift('body')`. Here's [my remix](https://glitch.com/edit/#!/impartial-amused-liquid). I'm not sure if this is a great idea tho :joy:

**Comment by tmbenhura** [comment]
Thanks Adam, the workaround works quite well.

With regards to it being a bug or a "feature", I am of the belief that hitting back should result in the visitor seeing exactly what they saw previously. I cannot think of any UX scenario, where a user would expect to see otherwise.

Thanks again!

**Comment by triskweline** [comment]
The current default target for history changes is [`:main`](https://unpoly.com/main). I agree that `body` is a safer choice here.
