### ISSUE TITLE
Make unpoly ignore up-layer if already in root

### ISSUE THREAD

**Issue by tomhillgreyridge** [unpoly/unpoly#242]
### Bug description
I really like the fact that Unpoly allows you to reuse existing pages in layers.  However I have found one thing that I think might be a nice enhancement.

At the moment, if you have up-layer="parent" on a link which is not actually in an overlay, the link doesn't work at all.  This makes it hard to reuse a page where you think it might be used in a modal or not.  What might be nice would be for Unpoly to assume that parent == root if there is no parent.

### Reproduction project
As an example, I have a page for creating an entry in a lookup table.  This might, in theory be used from a number of places, including in modals (which could potentially be nested).  I started off with the "raw" html for a non-modal version

```html
<form action="/url_to_do_the_save" method="POST">
  <!-- fields go here -->
  <button type="submit">Save</button>
  <a href="/previous_page_url">Cancel</a>
</form>
```
So without using Unpoly, you go to that URL and you can either save, or cancel where cancel is just a link to the previous page.

Now, I then wanted to make that work in an Unpoly modal, so I added an up-target to the link to this page.  Problem is that the cancel link now opens in the modal as well, so I added up-layer="parent", giving me

```html
<form action="/url_to_do_the_save" method="POST">
  <!-- fields go here -->
  <button type="submit">Save</button>
  <a href="/previous_page" up-layer="parent">Cancel</a>
</form>
```
This works fine in the popup **but now the cancel link doesn't work if you don't open it in a modal**.  

I realise I can use up-layer="root" which will work for a single layer of overlays but means that it wouldn't work in nested modals. 

### Expected behavior
If I try to open a link in a parent, when there is no parent, it goes to the root since that is the "ultimate" parent.

**Comment by tomhillgreyridge** [comment]
PS.  Seriously good work on the library, particularly how well documented it is

**Comment by adam12** [comment]
You can list multiple layer identifiers and Unpoly should fallback. Have you tried `up-layer="parent root"`?

**Comment by tomhillgreyridge** [comment]
I wasn't aware of that option.  You have kind of thought of everything!

**Comment by adam12** [comment]
For reference it's documented here: https://unpoly.com/layer-option under 'Matching in Multiple Layers' near the bottom. But getting to the page means clicking on a link in a paragraph.

I wonder if this page (and I think there are a few others) could/should be listed in the sidebar to make them more discoverable.

**Comment by triskweline** [comment]
See [`a[up-dismiss]`](https://unpoly.com/a-up-dismiss) for a second technique to implement such a "cancel" button.
