### ISSUE TITLE
Support a strict CSP for unpoly

### ISSUE THREAD

**Issue by apollo13** [unpoly/unpoly#246]
### Bug description

I am currently trying to add unpoly JS to an app that has a rather strict content security policy. For all intents and purposes it's `script-scr` can be considered to be set to 'self'. Most notably this excludes 'unsafe-eval' which is required for `up-on-*`.

### Reproduction project

I tried setting up a glitch project but failed horribly. Anyways this is easily reproducable on the unpoly demo by setting a `Content-Security-Policy: srcipt-src 'self'` header on responses and trying to delete a project (https://github.com/unpoly/unpoly-demo/commit/3f66d8a0d7b7173b704d90cea78935548bcf7ed8 -- which calls `up-on-dismiss`)

### Expected behavior

It would be great if there were a way to register some functions in advance and only be able to call those. I am not sure how a good approach to this would look like. Ideas welcome :) Or is there a way to register an `up-on-*` handler from js somehow?

### Browser version

 - OS: all
 - Browser: all supporting content-security-policy (basically every modern browser)

### Additional context

Error shown:
![Screenshot from 2021-08-08 19-37-09](https://user-images.githubusercontent.com/81547/128640633-b8262541-f06e-4f3c-b47f-9209ccff2735.png)

Please don't hesitate to ask if there are any questions and sorry for not providing a full reproducer project, but I couldn't figure out how to do this via glitch.

**Comment by apollo13** [comment]
I found some tips in http://triskweline.de/unpoly2-slides/#143 -- maybe the docs could also add a section about this?

**Comment by adam12** [comment]
Adding a section for CSP would probably be useful, but the question is where to put it? Would it be suitable for on the [up.event](https://unpoly.com/up.event) page?

**Comment by apollo13** [comment]
I think I would add it to all `up-on-*` attributes and link to a canonical page from there. Maybe add an explicit security section like HTMX did (https://htmx.org/docs/#security)?

**Comment by triskweline** [comment]
> I think I would add it to all up-on-* attributes and link to a canonical page from there. Maybe add an explicit security section like HTMX did (https://htmx.org/docs/#security)?

I think that's the way to go.

The page should contain the workarounds from http://triskweline.de/unpoly2-slides/#142 and http://triskweline.de/unpoly2-slides/#143 .

**Comment by triskweline** [comment]
The CSP guide is now here: https://unpoly.com/csp

Unpoly 2.3 lets you work with strict CSPs by prefixing your callback with a [script nonce](https://content-security-policy.com/nonce/):

```html
<a href="/path" up-follow up-on-loaded="nonce-kO52Iphm8B alert()">Click me</a>
```

Users of the [unpoly-rails](https://github.com/unpoly/unpoly-rails) gem can insert the nonce using the `up.safe_calback` helper:

```erb
<a href="/path" up-follow up-on-loaded="<%= up.safe_callback('alert()') %>'">Click me</a>
```
