### ISSUE TITLE
up-restore-scroll

### ISSUE THREAD

**Issue by dirkholzapfel** [unpoly/unpoly#25]
We tried to update from 0.30.0 to 0.36.1.

After the update - when clicking an `up-dash` with `up-restore-scroll="true"` unpoly fails with the attached log.
The error occurs in `restoreScroll()`.

The commit that introduced changed code to this function was: https://github.com/unpoly/unpoly/commit/e673b2e9e034cb0fb09e2c7ef93a057bb5e3dc30#diff-c5eb160fb78f4fa757becb6f4a4ade82R435

     __ _____  ___  ___  / /_ __
    / // / _ \/ _ \/ _ \/ / // /  0.36.1
    \___/_//_/ .__/\___/_/\_. / 
            / /            / /

    Call `up.log.enable()` to enable logging for this session.
    up.log.enable()
    true
    unpoly.js:2831 [UP] Preloading link jQuery.fn.init(1)
    unpoly.js:2831 [UP] Re-using cached response for GET http://ypsilon.dev:4000/en/hwm/updates
    unpoly.js:2831 [UP] Re-using cached response for GET http://ypsilon.dev:4000/en/hwm/updates
    unpoly.js:2831 [UP] Extracting .js-publication_page_content from 10200 bytes of HTML
    unpoly.js:2831 [UP] Saving scroll positions for URL http://ypsilon.dev:4000/en/hwm (Object)
    unpoly.js:2831 [UP] Adding history entry for http://ypsilon.dev:4000/en/hwm/updates (up:history:push (Object))
    unpoly.js:2831 [UP] Advanced to location http://ypsilon.dev:4000/en/hwm/updates (up:history:pushed (Object))
    unpoly.js:2831 [UP] Updating .js-publication_page_content
    unpoly.js:2831 [UP] Destroying fragment <div class=​"test-publication_landing_page js-
    publication_page_content              up-destroying" style=​"display:​ none;​">​…​</div>​ (up:fragment:destroy)
    unpoly.js:2831 [UP] Compiling fragment <div class=​"js-publication_page_content" up-source=​"http:​/​/​
    ypsilon.dev:​4000/​en/​hwm/​updates">​…​</div>​
    unpoly.js:2831 [UP] Compiling '.sticky' on 1 element(s)
    unpoly.js:2831 [UP] Compiling '.sticky' on <div class=​"publication_funding_status__wrapper sticky
            publication_funding_status__wrapper--no_items">​…​</div>​
    unpoly.js:2831 [UP] Inserted fragment <div class=​"js-publication_page_content" up-source=​"http:​/​/​
    ypsilon.dev:​4000/​en/​hwm/​updates">​…​</div>​ (up:fragment:inserted (Object))
    unpoly.js:2831 [UP] Restoring scroll positions for URL http://ypsilon.dev:4000/en/hwm/updates to undefined
    unpoly.js:5264 Uncaught TypeError: Cannot read property 'document' of undefined
    at HTMLDocument.<anonymous> (unpoly.js:5264)
    at Function.each (jquery.js?27d9:365)
    at jQuery.fn.init.each (jquery.js?27d9:137)
    at unpoly.js:5260
    at Object.group (unpoly.js:3775)
    at restoreScroll (unpoly.js:5259)
    at Object.revealOrRestoreScroll (unpoly.js:5283)
    at skipMorph (unpoly.js:7117)
    at unpoly.js:7096
    at Object.group (unpoly.js:3782)

**Comment by dirkholzapfel** [comment]
This quickfix solves the problem for me (made directly in the JS file for testing):
https://github.com/steady-media/unpoly/commit/2c2a0f44cc7155855eef478b5a161159b1e098b6

**Comment by triskweline** [comment]
This is fixed with the 0.50.0 release. Sorry it took a while!
