### ISSUE TITLE
up-back sets up-href but href is followed

### ISSUE THREAD

**Issue by j4mie** [unpoly/unpoly#254]
### Bug description

The [docs for `up-back`](https://unpoly.com/a-up-back) say that it

> will set the link's `[up-href]` attribute to the actual, previous URL.

And also

> If no previous URL is known, the link will not be changed.

This does appear to work as expected, my link ends up looking like this:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/6988/129731769-60b09ba3-f4bc-4910-a44e-e7c052527c18.png">

But when I actually click the link, Unpoly seems to prefer the `href` attribute to the `up-href` attribute, so the `up-back` behaviour doesn't actually work: the link just goes to `/accounts/login/` rather than the previous page.

I'm not familiar enough with the codebase so I'm not exactly sure how to debug this, but it looks like this may be the culprit:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/6988/129733686-d6daab78-e332-443f-9da4-634c600dd182.png">

(in `src/unpoly/link.js`)

If I'm reading that correctly, it seems like Unpoly prefers to use the `href` attribute over the `up-href` attribute.

### Reproduction project

https://waiting-substantial-cinnamon.glitch.me/

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Click on "Click here to go to the second page"
3. Click on "This link should go back to index.html" (this link links to `third.html` but has the `up-back` attribute)
4. You end up at `third.html` instead of `index.html`

### Expected behavior

The link on `second.html` should take the user back to `index.html`.

### Browser version

 - OS: macOS
 - Browser: Firefox
 - Version 92.0b4

**Comment by adam12** [comment]
Remix URL: https://glitch.com/edit/#!/waiting-substantial-cinnamon

Thanks for the reproduction. I agree this is a bug.

**Comment by triskweline** [comment]
This will be fixed in the upcoming version 2.3.

**Comment by j4mie** [comment]
> This will be fixed in the upcoming version 2.3.

Thank you!
