### ISSUE TITLE
Clear (pun intented) up X-Up-Cache docs

### ISSUE THREAD

**Issue by apollo13** [unpoly/unpoly#259]
### URL where to find the error

https://unpoly.com/X-Up-Cache

### Which section should be improved

First section.

### How should this section be improved?

I am not exactly sure. It probably depends on what `X-Up-Cache` is supposed to do. According to the docs it's value can be set to `clear` (and only that). The rails unpoly gem also allows for setting a special pattern and from what I can read from the JS code this should work. So what is actually supported?

Maybe something like:

```
The server may send this optional response header to clear the cache via a pattern or completely clear it by sending `clear`
```

**Comment by triskweline** [comment]
Good catch.

There is no `X-Up-Cache: clear` header. Before the 2.0 release this was replaced with the `X-Up-Clear-Cache` header that has many more options.
