### ISSUE TITLE
Unpoly documentation up-data invalid JSON

### ISSUE THREAD

**Issue by denzelem** [unpoly/unpoly#26]
The unpoly documentation says something like this:

```
<div class="google-map" up-data="[
  { lat: 48.36, lng: 10.99, title: 'Friedberg' },
  { lat: 48.75, lng: 11.45, title: 'Ingolstadt' }
]"></div>
```

But isn't this an invalid JSON?

```
var test = [
  { lat: 48.36, lng: 10.99, title: 'Friedberg' },
  { lat: 48.75, lng: 11.45, title: 'Ingolstadt' }
]
JSON.parse(test)

Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at <anonymous>:1:6
```

For me something like this (different data) was working:

```
<div class="google-map" up-data='[
  { "lat": 48.36, "lng": 10.99, "title": "Friedberg" },
  { "lat": 48.75, "lng": 11.45, title: "Ingolstadt" }
]'></div>
```

**Comment by triskweline** [comment]
You're right! I fixed all `[up-data]` examples.

It's really easy to contribute fixes to the docs by the way. All docs are Markdown in comments above the code like [here](https://github.com/unpoly/unpoly/blob/master/lib/assets/javascripts/unpoly/syntax.coffee).
