### ISSUE TITLE
`Cache()` requests are not logged

### ISSUE THREAD

**Issue by apollo13** [unpoly/unpoly#261]
### Bug description

The `Cache()` class only logs when when `this.config.logPrefix` is set for the class. This doesn't seem to happen in network.js and as such one doesn't easily see when a request is retried because there is no cache or because the entry is expired…

### Expected behavior

Cache log lines should show up :D Not sure if the default logging should show it, or whether there should be a loglevel or so.

**Comment by triskweline** [comment]
This is intentionally disabled as it makes the log hard to read for any other purpose.

**Comment by apollo13** [comment]
Makes sense, thanks!
