### ISSUE TITLE
Compiler destructors not called on up-follow

### ISSUE THREAD

**Issue by adam12** [unpoly/unpoly#28]
I just noticed that my compiler destructors are not being called on `<a>` elements that use `up-follow`, but are when called with `up-target`, provided `up-target` is _not_ `body`.

I've looked through the code but it's not obvious where the issue might lie.

Thoughts?

(Unpoly 0.36.2, jQuery 2.2.4)

**Comment by triskweline** [comment]
I will have a look.

**Comment by triskweline** [comment]
It was a subtle issue about jQuery cleaning up data properties when an element is detached from the DOM. In the case of `<body>` replacements, this happened before destructors were called, causing jQuery to clean up the constructor callbacks too early.

Fixed in 0.37.0.

**Comment by adam12** [comment]
Tested and working great. Much thanks :)
