### ISSUE TITLE
Unpoly 2: Navigation feedback does not work on the root page 

### ISSUE THREAD

**Issue by FLeinzi** [unpoly/unpoly#280]
### Bug description

Navigation elements won't get the active classes from Unpoly (default: `up-current`) when you are on the root page of your app. It worked with Unpoly 0.61.0.

### Reproduction project

https://broken-unpoly-navigation.glitch.me/

### Steps to reproduce the behavior:

1. Go to reproduction project linked above, both navigation links will have a red background.
2. Click on 'Other'
3. See the green background of the 'Other' element.
4. Click on "Home"
5. See the error: 'Home' will have a red background instead of a green one.

### Expected behavior

The 'Home' element should also get a green background when being on that page.

### Versions
 - happens on all browsers
 - Unpoly: 2.3.0

### Additional context

I found out, that there are different ways to normalize URLs. The navigation uses the method `up.feedback.normalizeURL`, which normalizes `'/'` to `''`, so the URLs do not match.
```javascript
> up.util.normalizeURL('/')
=> '/'
> up.history.normalizeURL('/')
=> '/'
> up.feedback.normalizeURL('/')
=> ''
```

This is the method that determines the active state:
```javascript
LinkFeedbackURLs.prototype.isCurrent = function (normalizedLocation) {
  // It is important to return false instead of a falsey value.
  // up.feedback feeds the return value to element.toggleClass(), which would use a default for undefined.
  return this.isSafe && !!((this.href && (this.href === normalizedLocation)) ||
    (this.upHREF && (this.upHREF === normalizedLocation)) ||
    (this.aliasPattern && this.aliasPattern.test(normalizedLocation, false)));
};
```

I don't know, what's the best solution. Maybe it works when you adapt the `stripTrailingSlash` option in the base implementation of `normalizeURL` to NOT strip the slash for `'/'`. But this could have some side effects.

**Comment by triskweline** [comment]
> Maybe it works when you adapt the stripTrailingSlash option in the base implementation of normalizeURL to NOT strip the slash for '/'. 

Since `up.util.normalizeURL()` is supposed to return an absolute URL, we should make this change.

I'm not sure that this is the only issue, since `isCurrent()` is supposed to compare two normalized URLs. Two empty strings are still equal.

**Comment by FLeinzi** [comment]
> I'm not sure that this is the only issue, since `isCurrent()` is supposed to compare two normalized URLs.

This would be another solution. The parameter `normalizedLocation` has to be normalized the same way as `this.href` (in LinkFeedbackURL) before the call.

> Two empty strings are still equal.

Yes, but `this.href && (this.href === normalizedLocation)` evaluates to `''` and an empty string is falsey. So `isCurrent()` returns false.
