### ISSUE TITLE
up-current class on link when URL has hash fragment

### ISSUE THREAD

**Issue by triskweline** [unpoly/unpoly#284]
### Discussed in https://github.com/unpoly/unpoly/discussions/277

<div type='discussions-op-text'>

<sup>Originally posted by **thetutlage** September  2, 2021</sup>
So, I have a situation where the `up-current` class is not added to an anchor tag when the URL has hash fragment. Lemme share a screenshot that may explain it better

![up-current](https://user-images.githubusercontent.com/1706381/131875500-5b381e86-f90d-44dc-8ec8-60b17c2dbc7a.png)

- Unpoly version - 2.3.0

I can use `up-alias` as well, but that has the risk of adding the same class to another anchor. For example:

- Link 1 ( url = /database ) ( up-alias = /database/* )
- Link 2 ( url = /database/query-builder )

Now, link 1 and 2 both will have the active class</div>

**Comment by thetutlage** [comment]
That was pretty quick. Thanks for tracking the issue and fixing it :)
