### ISSUE TITLE
audio[up-keep] elements lose their playback state when rendering the body

### ISSUE THREAD

**Issue by triskweline** [unpoly/unpoly#294]
A playing `<audio up-keep>` element stops playback when rendering the `<body>` element with new HTML. The element is preserved, it just stops playing.

The element does keep playing if any other container element is rendered.

Discussed in https://github.com/unpoly/unpoly/discussions/293

**Comment by thetutlage** [comment]
Hey 👋

Just wanted to check and see if you are planning to work on this fix or is it something deeper and will take more time?

**Comment by triskweline** [comment]
I'm afraid this is not currently a priority for me.

If you need a quick workaround you can configure Unpoly to replace any other container (like your app layout):

```js
up.fragment.config.mainTargets.unshift('.container')
up.history.config.restoreTargets.unshift('.container')
```

**Comment by thetutlage** [comment]
I think 2.5.0 fixes this?

**Comment by triskweline** [comment]
Unfortunately not, this is still an open issue.

**Comment by triskweline** [comment]
Preserving of playback state in media elements was recently revised 5dae584b08fae36f1c90c5103efb9fa9332a56f7. Unfortunately we cannot preserve media elements that are direct children of `<body>` without lots of extra code, so we decided to not support this case.
