### ISSUE TITLE
Native Android/iOS adapter

### ISSUE THREAD

**Issue by kirantpatil** [unpoly/unpoly#30]
Hi,

Does it support Native [Android](https://github.com/turbolinks/turbolinks-android)/[iOS](https://github.com/turbolinks/turbolinks-ios) adapter as done in Turbolinks ?

Thanks.

**Comment by triskweline** [comment]
Sorry, we're focusing exclusively on the web platform right now.

If you want to implement Basecamp's hybrid approach, Turbolinks is the best tool there is right now!

**Comment by kirantpatil** [comment]
Thanks.
