### ISSUE TITLE
up-submit="false" & up-target="false" should be unified, or better documented

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#304]
### Bug description

`<form>` with `up-target="false"` is not respected, but it is where the documentation leads to.

docs https://unpoly.com/form-up-submit
```
Modifying attributes
All attributes for a[up-follow] may be used.
```

i was only able to discover that `up-submit="false"` should be used by reading `up.form.config.noSubmitSelectors`

so, it would be good if this is clearly documented, but i feel the documentation is ok and that the code should be updated to reflect the docs, in which case forms should respect `up-target="false"`

## platform
using unpoly ver 2.4.1

**Comment by triskweline** [comment]
There is now a doc section regarding [boolean attributes](https://unpoly.com/attributes-and-options#boolean-attributes).
