### ISSUE TITLE
No <up-bounds> is created when using a custom transition

### ISSUE THREAD

**Issue by DoomyCrystal** [unpoly/unpoly#309]
### Description

I'm creating a page transition where a fragment should be transitioned with a custom transform animation. When I use the predefined transitions e.g. ```'cross-fade'``` or ```'move-left'```, the old element is cloned and inserted into an ```<up-bounds>``` element, the transition works as expected. However if I use my own transition (see below), the ```<up-bounds>``` doesn't exist and only the new element is transitioned.

``` js
up.animation('flip-left', function(element, options) {
  element.style.transform = 'rotateY(0)'
  element.style.transformOrigin = 'right center'
  up.animate(element, {
    transform: 'rotateY(180deg)'
  }, options)
})

up.animation('appear', function(element, options) {
  element.style.opacity = '0'
  up.animate(element, {
    opacity: 1
  }, options)
})

up.transition('flip', ['flip-left', 'appear'])
```

### Basic reproduction

https://glitch.com/edit/#!/custom-page-transition

### Expected behavior

The oldElement should be cloned and inserted thanks to the ```absolutize``` function and transtitioned with the custom ```'flip-left'```animation.

Unpoly version 2.2.1

Any help with this issue is appreciated 😊

**Comment by triskweline** [comment]
Your animations must return a `Promise` for when the animation ends. To do so, return the promise returned by `up.animation()`:

```js
up.animation('flip-left', function(element, options) {
  element.style.transform = 'rotateY(0)'
  element.style.transformOrigin = 'right center'
  return up.animate(element, { // <== return here
    transform: 'rotateY(180deg)'
  }, options)
})
```

See result in this remix of your Glitch:
https://glitch.com/edit/#!/sulfuric-responsible-clove

Also note that there is a predefined "appear" animation called `fade-in`.
Also links navigate by default, so you don't need `[up-navigate=true]`.

**Comment by DoomyCrystal** [comment]
Works like a charm, thanks a lot 👍
