### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by obsidienne** [unpoly/unpoly#31]
Hi,

Do you accept jQuery depency removing patch ?

**Comment by triskweline** [comment]
I will be happy to accept such a patch with passing tests.

If you'd like to take this on, be aware that it will be a very large change.

For the past two months I've been working on migrating away from jQuery deferreds to native promises (Branch https://github.com/unpoly/unpoly/commits/hk/jquery3-use-native-promise) which is the first of many steps this would require.

**Comment by spaghetticodr** [comment]
Hurry up. Just copy paste the deferreds part out of jquery into your framework if it's so hard to move away. Introducing some random dependency just because it made you write a bit shorter code is unprofessional as fuck.

**Comment by triskweline** [comment]
@spaghetticodr Your tone is not welcome here.
