### ISSUE TITLE
Load javascript files along with template fragments

### ISSUE THREAD

**Issue by deepakmn** [unpoly/unpoly#32]
Is it possible to load page specific javascript files when I fetch a new page fragment ? For example:

I've page-a.html:
```
<html>
<head>
<script src="page-a.js"></script>
<body>
<a href="page-b.html" up-target=".page-content">Click here to load page B</a>
<div class="page-content">Content of page A</div>
</body>
</head>

```
And, there is page-b.html:
```
<html>
<head>
<script src="page-b.js"></script>
<body>
<a href="page-a.html" up-target=".page-content">Click here to load page A</a>
<div class="page-content">Content of page b</div>
</body>
</head>

```
When .page-content of page-b.html is inserted, I would lose page-b.js. How can I prevent this from happening ? Do I have to pre-load all scripts on all pages ?

**Comment by triskweline** [comment]
I personally simply pre-load all scripts on all pages.

If you want to load `<script>` tags in new fragments you can configure:

    up.dom.config.runLinkedScripts = true

See [up.dom.config docs](https://unpoly.com/up.dom.config).

Note that if you do this, your script fragments need to detect whether they have been loaded before. Otherwise the browser will request and eval them again and again when the fragment is swapped in multiple times.

**Comment by deepakmn** [comment]
Thank you for pointing this out. Would this config parameter help to run inline scripts too ?

**Comment by triskweline** [comment]
Inline scripts are controlled with `up.dom.config.runLinkedScripts`, but that's already `true` by default.

**Comment by sfusato** [comment]
I can't see `runLinkedScripts  `or  `runInlineScripts `options on [up.dom.config docs](https://unpoly.com/up.dom.config)

Have the docs changed since this was brought up ? If so, how would one achieve what the OP inquired about ?

**Comment by triskweline** [comment]
The information in this closed issue is out of date.

Unpoly will no longer execute `<script>` tags that were inserted by a fragment update. They are still executed during the initial page load.

If you need to dynamically load additional libraries after the initial page load, I recommend [this technique](https://makandracards.com/makandra/52361-unpoly-loading-large-libraries-on-demand).
