### ISSUE TITLE
Support "a-wrapped" button[type=button] Items

### ISSUE THREAD

**Issue by micahasmith** [unpoly/unpoly#327]
### Bug description

It's recommended to always specify a `type` attribute on `<button>`

The following link will work as expected-- performing XHR and updating the info in `#content`:

```html
<a href="/hb/test2/" up-target="#content" rel="nofollow">Linkypoo</a>
```

This will also work

```html
<a href="/hb/test2/" up-target="#content" rel="nofollow"><button>Linkypoo</button></a>
```

The following link _will not_:

```html
<a href="/hb/test2/" up-target="#content" rel="nofollow"><button type="button">Linkypoo</button></a>
```

### Reproduction project

https://glitch.com/edit/#!/rigorous-nebula-crepe

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Click the different types of buttons to observe behavior

### Expected behavior

`<button type="button" />` that is wrapped in `<a>` should work with link-following.

**Comment by adam12** [comment]
This part of the W3C spec seems incredibly divisive. According to MDN, a `<button>` can have a `<a>` parent, but the W3C HTML5 validator says it cannot.

> The a element can be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g., buttons or other links)

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

Do we know if a `<button>` inside an `<a>` is actually valid markup? if we establish that it is, then it might be worth seeing if this is an Unpoly issue or not.

**Comment by micahasmith** [comment]
hmmm,,, seems like you're totally right about [that not being valid](https://stackoverflow.com/a/6393863)

i'll close this out. ty for your time @adam12!
