### ISSUE TITLE
How to compile $.xxx plugins

### ISSUE THREAD

**Issue by deepakmn** [unpoly/unpoly#33]
How can I use up.compiler with plugins which directly invoke the $ symbol (example, $.validate() ) without using any selector ?

**Comment by triskweline** [comment]
I'm afraid I don't understand your example. What is $.validate()? What are you trying to do?

**Comment by deepakmn** [comment]
I'm using a validator plugin (http://www.formvalidator.net/#configuration) which recommends configuring it with aforementioned syntax.

**Comment by triskweline** [comment]
You should always look for a way to activate plugins on the compiled element only.

E.g. with the validator plugin:

```
up.compiler('form.with-validation', function($form) {
  $.validate({ form: $form });
})
```

If a plugin cannot be told to activate on a single element, it's not a good fit for Unpoly.
