### ISSUE TITLE
Headers X-Up-Events replay issues with caching

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#349]
### Bug description

X-Up-Events headers cause duplicate events to fire when unpoly uses the cache for up-follow or it's other directives.
I'm not sure that this is intended behaviour or not, maybe i'm not using events in the way envisioned by rails or unpoly.

what i've done to provide intuitive behaviour for events is have my server include a X-Up-Clear-Cache header whenever it sends events as well.

assuming the event playback from cache is intended behaviour, could you give an example of what UI this makes sense for.

**Comment by triskweline** [comment]
I have never used `X-Up-Events` for a `GET` request, which is the only kind of request that is being cached.

**Comment by triskweline** [comment]
I'm going with *intended behavior* here.
