### ISSUE TITLE
Ability to Cancel Pending XHR Requests?

### ISSUE THREAD

**Issue by jakedowns** [unpoly/unpoly#35]
Say you're making a type-ahead search field which uses `up.replace` to grab a results fragment, as the user types.

I've debounced and throttled the call to `up.replace` but there are still some scenarios where requests might start stacking up. (when the server takes longer than expected, or network conditions change, for example)

Is there any way to cancel all pending XHR requests? or at least to clear the current proxy queue prior to firing off the next request?

I've tried tweaking `up.proxy.maxRequests` but it's not _quite_ what i need.
I thought `up.proxy.clear()` might be what i'm looking for, but that just clears cached results

maybe i need to add my own queue layer to prevent sending multiple requests when one is still outstanding. but ideally i'd like to just be able to cancel/supercede a given request that was taking too long and just say "never mind, user changed their mind anyway, load this instead now..."

Any help would be much appreciated, thanks.

**Comment by triskweline** [comment]
The the use case of a type-ahead search field, you probably want to use [`up.observe`](https://unpoly.com/up.observe). It has a built-in queue that guarantees that only a single XHR request is in flight at any moment.

**Comment by jakedowns** [comment]
ah perfect, thanks for the quick response. sorry i overlooked that.
