### ISSUE TITLE
Unpoly isn't parsing boolean attributes properly

### ISSUE THREAD

**Issue by ijcd** [unpoly/unpoly#36]
I'm using some html generation libraries that generate boolean attributes using the k=k format. According to this, it seems that boolean attributes should be parseable in a few ways that are considered equivalent:

http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes

I have a library that is producing this format:

```
<div up-keep="up-keep"> 
```

This should be recognized as boolean inclusion of `up-keep` but it seems that unpoly fails to pick it up.

I understand the brevity argument from https://github.com/unpoly/unpoly/issues/11 but this is generated markup, so brevity isn't important and the output format isn't configurable, unfortunately.

**Comment by triskweline** [comment]
I wasn't aware this form was still in common use.

This should be a very small change:

https://github.com/unpoly/unpoly/blob/1dad1f3e66f0186e6fb1db5c62826895873265b2/lib/assets/javascripts/unpoly/util.coffee#L1133
https://github.com/unpoly/unpoly/blob/650a2a02f3c8e4c81e85133e830563e4d82d9dcb/spec_app/spec/javascripts/up/util_spec.js.coffee#L311

**Comment by ijcd** [comment]
Hmm. The specs there seem to test counter to the HTML5 spec, in general.

Great library, btw.

**Comment by triskweline** [comment]
Fixed in 0.50.1.
