### ISSUE TITLE
How to change browser url with redirect after form submission?

### ISSUE THREAD

**Issue by deepakmn** [unpoly/unpoly#37]
I'm setting the response header to X-Up-Location while sending the redirect page, but the browser url is not changed. How do I achieve this behavior ?

```
//Spring code
@GetMapping("/expert-types")
	public String viewPage(WebRequest request, HttpServletResponse response) {
		response.setHeader("X-Up-Location", request.getContextPath() + "/expert-types");
		return "expert-types.html";
	}

@PostMapping("save-expert-type")
public String update(ExpertType entity) {
//Do db save here
return "redirect:/expert-types";
}
```

But the url still remains at contextPath/edit-expert-type?id=1

**Comment by triskweline** [comment]
When you set `X-Up-Location` you should also send `X-Up-Method: GET`. Otherwise Unpoly will assume that the new location is also a POST, and URLs are only updated for GET requests.

The next version will assume `X-Up-Method: GET` if it is missing.
