### ISSUE TITLE
Modal window has "full height"

### ISSUE THREAD

**Issue by szabeszg** [unpoly/unpoly#370]
### Modal window has "full height"

On the demo site, a modal window's height (such as a Company modal) fits the height of its content. However, using the current version of unpoly.css the modal's height stretches to the height of the viewport.

### Steps to reproduce the behavior:

Just open a modal and observe its height.

### Expected behavior

The old behavior was preferable since that is how most of the time a modal window should look, I think.

### Additional context

The issue is probably here, as far as I can tell:
```
up-modal-viewport, up-drawer-viewport, up-cover-viewport {
  position: absolute;
  overflow-y: scroll;
  overflow-x: hidden;
  overscroll-behavior: contain;
  display: flex;
  justify-content: center; }
```

Since `display: flex;` was added as opposed to the demo site where it is "missing", the modal grows because of `position: absolute;` also being present.

While `drawer` and `cover` need to be full height, I think `modal` does not.

I've applied `position: static;` to the modal's viewport like this
```
up-modal up-modal-viewport {
  position: static;
}
```
but I think that this should be the default.

**Comment by adam12** [comment]
I presume it must be from this commit: 1c89eaabfc8d1bae0003ebabf87cba968aceead6

> ```
> up-modal up-modal-viewport {
>   position: static;
> }
> ```

Unfortunately, this breaks if the content overflows the modal so I don't think this would be the entire solution.

I have a simple reproduction [here](https://glitch.com/edit/#!/cedar-candy-boar?path=index.html%3A17%3A0), but not sure if I have any suggestions on how to proceed with a fix.

**Comment by triskweline** [comment]
Sorry about that. Your analysis helped fixing this.

Fixed in 2.5.3.

**Comment by szabeszg** [comment]
@triskweline  Thank you for fixing it!

BTW, will you please update some references to Unpoly on this page https://unpoly.com/install as they still point to 2.5.2 
I have not checked all but these point to the old version:

- https://unpoly.com/install/cdn
- https://unpoly.com/install/download

**Comment by triskweline** [comment]
I updated the site.
