### ISSUE TITLE
elementFromPoint(): "The provided value is non-finite"

### ISSUE THREAD

**Issue by MattApril** [unpoly/unpoly#372]
### Bug description

**TypeError: The provided value is non-finite**

I am getting this error in production from a handful of different users, all on **Safari 15.x** so far.

### Steps to reproduce the behavior:

I have not been able to personally reproduce this issue.

### Browser version

 - OS: iOS 15.4.1, iOS 15.3.1
 - Browser: Mobile Safari 15.4 and 15.3
 - Version 2.5.3 

### Additional context

The error is coming from `elementFromPoint` in `wasHitByMouseEvent`. So clientX and/or clientY must not be numeric.

**Comment by adam12** [comment]
Confirm the version of Unpoly you're using?

**Comment by MattApril** [comment]
2.5.3

Fixed the OP

**Comment by triskweline** [comment]
Needs reproduction.

There is a [test ensuring we don't crash](https://github.com/unpoly/unpoly/commit/b2014c7e4038d95a92e85030e0044c560f5f5b73) with undefined `clientX` and `clientY`, but that one passes on Safari 15 and Mobile Safari 15.

**Comment by MattApril** [comment]
I logged another instance of the error from Firefox 99.0 on MacOS 10.15 over the weekend:

`Document.elementFromPoint: Argument 1 is not a finite floating-point value`

**Comment by triskweline** [comment]
Closing this as we couldn't achieve reproduction in over a year.
