### ISSUE TITLE
unpoly doesn't update targets when some are missing (also could have better error message for this situation)

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#412]
when doing a form submit using something like the below, and my server response is missing one of the targets (conditional rending in this case), unpoly says that it fails to find any of the targets and falls back to updating :main.

```html
 <button
    formaction="?accept={{member.member/uuid}}"
    up-transition="cross-fade"
    up-target="#pending_list, #members_list"
  >
    Accept
</button>
```

it may be worth while to output an error message that says which selectors didn't match, and update the ones that did match.

**Comment by adam12** [comment]
I don't remember what the v1 implementation did, but this is planned for improvement in Unpoly 3, via the `:maybe` target selector.

**Comment by boxxxie** [comment]
@adam12 sorry, i forgot to update the title of the issue when i learned more about what error was occuring.

the error message makes it look like targets are not being split, but they are being split, it's just when there is a missing target from the server the error report looks wrong.

**Comment by triskweline** [comment]
Providing details about a partial match is not trivial, as Unpoly will usually attempt multiple fallback targets in multiple layers. We used to log about every attempt, which flooded the log with a page of information for every render pass.

Closing this until there is a more specific idea about how logging can be improved.
