### ISSUE TITLE
Allow [up-emit] on buttons

### ISSUE THREAD

**Issue by triskweline** [unpoly/unpoly#416]
### Discussed in https://github.com/unpoly/unpoly/discussions/411

<div type='discussions-op-text'>

<sup>Originally posted by **outcassed** August  9, 2022</sup>
Would it be possible to have unpoly either honor `up-emit` on `<button>`s or expose the up-emit click event handler so that it can be easily extended?

```
--- unpoly.js
+++ unpoly-patch.js
@@ -11642,6 +11642,7 @@
     //    abort = -> up.emit(signal, 'abort')
     //    [abort, signal]
     on('up:click', 'a[up-emit]', executeEmitAttr);
+    on('up:click', 'button[up-emit]', executeEmitAttr);
     on('up:framework:reset', reset);
     return {
         on,
@@ -11654,7 +11655,8 @@
         halt,
         isUnmodified,
         fork,
-        keyModifiers
+        keyModifiers,
+        executeEmitAttr
     };
 })();
 up.on = up.event.on;
```</div>

**Comment by triskweline** [comment]
This should also work on an `input[type=button]`.

We could just drop the element type from the selector and emit events on anything with an `[up-emit]` attribute. This is how we already do it for `[up-dismiss]` and `[up-accept]`.

**Comment by alexandergitter** [comment]
Here is another example: I have a table where I would like to be able and emit an event when a row is clicked. Currently I could add an `<a>` in every `<td>`, or use `<a>`s for the rows and set `display: table-row` on them.
At the moment I use Alpine.js with an `x-on:click` attribute, that in turn calls an Unpoly function. It would be nice to be able to do this with Unpoly directly.
