### ISSUE TITLE
Bug with instantSelectors not working?

### ISSUE THREAD

**Issue by tomhillgreyridge** [unpoly/unpoly#418]
### Bug description
When I set Unpoly to follow all links using followSelectors as described here

https://unpoly.com/handling-everything

it works fine.  However, if I try to use instantSelectors instead using 

```up.link.config.instantSelectors.push('a[href]')```

then all links on the page stop working entirely.

### Reproduction project

https://glitch.com/edit/#!/necessary-cumbersome-chasmosaurus

### Steps to reproduce the behavior:

1. Try to click on the link in the project above in Chrome.  Nothing happens
2. Go into scripts.js and comment out the instant selectors and comment in the follow selectors instead
3. Retry the page and the links should be working again

### Expected behavior

Either I am misunderstanding the documentation, or all links on the page should be followed on mousedown.  The only thing I could think of is that I am supposed to add both followSelectors and instantSelectors in which case that should probably be made clear in the documentation.

### Browser version

 - OS: Windows
 - Browser : Chrome
 - Version : 104

**Comment by adam12** [comment]
Indeed, looks like a bug as far as I can tell at a glance. As a workaround, you could use a macro here. See [my remix](https://glitch.com/edit/#!/lime-silicon-orangutan?path=scripts.js%3A10%3A2).

```javascript
up.macro('a[href]', (el) => {
  el.setAttribute('up-instant', '')
})
```

**Comment by tomhillgreyridge** [comment]
That's fine.  I'm not actually using it for anything production yet, I just thought you'd want to know.  Great work on the library by the way - makes life very clean for server-rendered applications

**Comment by triskweline** [comment]
An instant link must also by [followable](https://unpoly.com/up.link.isFollowable), usually by giving it an `[up-follow]` attribute or by configuring `up.link.config.followSelectors`.

To follow all links on `mousedown`:

```js
up.link.config.followSelectors.push('a[href]')
up.link.config.instantSelectors.push('a[href]')
```

If you only configure `instantSelectors` you just take away the link's `click` event, and neither Unpoly nor the browser will do anything with the link.

**Comment by tomhillgreyridge** [comment]
Hi @triskweline 

Can I suggest a minor update to

https://github.com/unpoly/unpoly/blob/master/src/unpoly/pages/handling-everything.md

in that case to make it clear that if you want all links to be "instant" you also need to add them to the followSelectors

I read through that page when I was creating the test case to see if I had missed anything and didn't spot anywhere it mentioned this - it does mention that links which are not followable will still activate on click rather than instant, but I don't think it says they won't work *at all* unless you also either add [up-follow] or adding them to the followSelectors
