### ISSUE TITLE
X-Requested-With header missing

### ISSUE THREAD

**Issue by foobear** [unpoly/unpoly#42]
Frameworks [like jQuery](https://github.com/jquery/jquery/blob/3.2.1/src/ajax/xhr.js#L64-L66) add a HTTP header `X-Requested-With: XMLHttpRequest`.
It is used to detect XHRs on the server side, for example in [Rack](https://github.com/rack/rack/blob/2-0-stable/lib/rack/request.rb#L221-L223).

Unpoly should maybe add this header by default. I understand that adding a non-standard header by default might be subject to heated discussions. :wink: 
Alternatively, we could allow configuring default headers like this via `up.proxy.config` or similar.

For the time being, I'll be using this workaround:

```javascript
up.on('up:proxy:load', function(event) {
  event.request.headers['X-Requested-With'] = 'XMLHttpRequest';
})
```

**Comment by triskweline** [comment]
Fixed in 0.50.1.

**Comment by jartaud** [comment]
`X-Requested-With` is still not being sent.  @foobear workaround still works.

**Comment by triskweline** [comment]
This is a very old issue.

It has later been decided to not send `X-Requested-With` because server-side frameworks tend to change their behavior based on that header. If you want to test if a request was made by Unpoly you can check the [`X-Up-Version`](https://unpoly.com/X-Up-Version) header.
