### ISSUE TITLE
`up.submit()` javascript call sometimes performs a full reload

### ISSUE THREAD

**Issue by mfazekas** [unpoly/unpoly#430]
### Bug description

```js
await up.submit(element, {target:"#autosave-logs", params: {autosave: "true"})
```

will sometimes cause a full page refresh in unpoly 2.0 or later.
We're using this method for autosave so a full page reload is not desired.

### Reproduction project

https://jazzy-different-rocket.glitch.me

See the form, if you change something it does send a request for autosave with `up.submit` if you simulate a POST requested page, next `up.submit` will cause a full page reload.

### Expected behavior

Quote from documentation:

https://unpoly.com/up.submit

> Instead of loading a new page, the form is submitted via AJAX. The response is parsed for a CSS selector and the matching elements will replace corresponding elements on the current page.

### Browser version

 - OS: MacOS
 - Browser Chrome
 - 105.0.5195.125

### Additional context

In log I do see: 
>Loading content in new page to restore history support

Which is coming from here:

https://github.com/unpoly/unpoly/blob/9abca12a4ee078146485da5d986b89ea671c88f6/src/unpoly/classes/change/from_url.js#L62-L64

This seems to be caused by this commit.
https://github.com/unpoly/unpoly/commit/da5f3e8efaacbafea27d8a86f18d6aefae7cbdce

**Comment by mfazekas** [comment]
As a workaround I can do:

```js
    // await up.submit(element, {target:"#autosave-logs", params: {autosave: "true"})
    let options = up.form.submitOptions(element, {target: '#autosave-logs', params:{autosave:"true"}});
    let response = await up.request(options.url, {params: options.params, method: options.method});
```

So i guess adding a note to docs about, the possibility that unpoly sometimes might do a fun page reload should be a good enough fix for this.

**Comment by boxxxie** [comment]
i just finished making a page that has 100s of inputs that use autosubmit, and avoiding page reloads is 100% up to my server behaving well (replying with HTML in posts as opposed to redirects).

**Comment by boxxxie** [comment]
can you enable logging in your bug example.

the button you have to set requests to POST doesn't seem to work for me. (i don't see any POSTs in my network log)

is up.submit supposed to work with async functions?

I don't think autosubmit should do full page reloads... nothing in unpoly should do that unless you explicitly ask for it like with `up-follow=false`. adding a note in the docs to say that "unploy sometimes does a full page refresh" does not seem like a fix for this issue.

**Comment by mfazekas** [comment]
So what you should see with the example is that if you change the field it does submit to changed data to server, using `up.submit` then "simulate POST request" adds a mock to unpoly internals so it believes the it was loaded from a POST request. Then the next `up.submit` will perform a full page reload.


https://user-images.githubusercontent.com/52435/195696088-dac0f8fa-09df-4c15-8853-98bf85f8f971.mov

The "simulate POST request" doesn't actually perform a POST request just changes unpoly internals so it believes the request is coming from a POST. (In our rails app it happens if the form was submitted using a POST request, and there is a validation error, so we render the form)

```js
function simulatePostRequest() {
  up.protocol.initialRequestMethod = function() { return 'POST' }
}
```

I was too lazy to write a full example with backend, I guess I can set up a simple rails app on heroku if you prefer that.

**Comment by triskweline** [comment]
Unpoly cannot function when it was booted from a `POST` response. In this state history entries cannot be added.

For a long time Unpoly simply refused to boot when the initial request method was anything other than `GET`. This was later changed to perform a full page load on the next render, so at least compilers would run on the initial response.

When you let Unpoly [handle all links and forms](https://unpoly.com/handling-everything) this entire issue goes away, as Unpoly only adds history entries for `GET ` responses.

Closing this issue as this is working as designed, and cannot be fixed in code.
