### ISSUE TITLE
Add up:request:before-send event which emits right before XHR send

### ISSUE THREAD

**Issue by iaddict** [unpoly/unpoly#435]
Currently, there seems to exist no option to receive progress events from the running XHR.
It would be helpful if the request would emit an up:request:before-send event.
The event should contain a reference to the original XHR before send is called.

Background: Form file uploads benefit from a live progress bar, which should reflect the real upload progress.
This can be achieved by registering a progress event handler on [xhr.upload](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload).

https://github.com/unpoly/unpoly/blob/6f5a0aa28d6426d3f5640ee4d1543b7fc3e75e8b/src/unpoly/classes/request/xhr_renderer.js#L59-L60

**Comment by triskweline** [comment]
I think the [`up:request:load`](https://unpoly.com/up:request:load) event could have an `{ xhr }` property, pointing to a new, unsent `XMLHtttpRequest` instance. This instance would need to be passe to `up.XHRRenderer`.

**Comment by triskweline** [comment]
> What scarred me to suggest it, was that the XHRRenderer would not be the owner of the XMLHttpRequest anymore, but the Request. Right?

Yes, it's not optimal. But I think we could change `up.Request#load()` and the `up.Request.XHRRenderer` constructor so it takes an optional `{ xhr }` option with an existing `XMLHttpRequest` instance. If that option is given, the object is reused by the renderer. Otherwise it makes a new instance.

> I'll give it a try on my fork.

Let me know if you need any help with the code or tests.

**Comment by iaddict** [comment]
I now created a pull request. Many thanks for your suggestions!

**Comment by iaddict** [comment]
@triskweline Many thanks for helping me on this and merging the pull request. It was a joy! 🎉

**Comment by triskweline** [comment]
This is now released as version 2.7.1.
