### ISSUE TITLE
Using both up-hide-for and up-show-for for the same element with up-switch

### ISSUE THREAD

**Issue by denzelem** [unpoly/unpoly#44]
I had an issue where `up-hide-for` and `up-show-for` behaves different on those two actions:

```
<select name="advancedness" up-switch=".target">
  <option value="basic">Basic parts</option>
  <option value="advanced">Advanced parts</option>
  <option value="very-advanced">Very advanced parts</option>
</select>
```

```
<div class="target" up-show-for="advanced very-advanced" up-hide-for="basic">
  Some example
</div>
```

1. When switching between `basic` and `advanced` the target shows and hides correctly.
2. When loading a page, where advanced is already selected, the target was not shown, even it should be.

The fix was to simply use `show-for` and remove `hide-for` (it clearly makes no sense to use both).

Do you think it makes sense to highlight this in the documentation, that not both can be used? Or maybe output some warning on the console. I'm also okey with just closing this issue.

**Comment by triskweline** [comment]
I think we should throw an error when both attributes are present on a switchee element. 

A good place would probably be https://github.com/unpoly/unpoly/blob/2d7bd0432e08f04b00ce6bc7f8d9c4cbe090c2ba/lib/assets/javascripts/unpoly/form.coffee#L404 .

**Comment by triskweline** [comment]
Closing stale issue.
