### ISSUE TITLE
Documentation on up-observe's "this" incorrect

### ISSUE THREAD

**Issue by foobear** [unpoly/unpoly#442]
### URL where to find the error

https://unpoly.com/input-up-observe

### Which section should be improved

Documentation says that `this` is the observed form field element, while it actually is a `FieldObserver`.
We can read its `fields` property to access the observed field(s), so it's not really broken, but the documentation is misleading.

### How should this section be improved?

I'm not sure if the current behavior is intended. `this` being a `FieldObserver` feels a bit weird, but it offers more information that a singel field (or list of fields) would offer.

So, either:
* Documentation needs to be updated.
* If it's a bug in the API of `up-observe`, we should to fix that. :)

**Comment by triskweline** [comment]
`FieldObserver` (now `FieldWatcher`) is private API, so we don't want to expose that. It should be whatever element has the `[up-observe]` (now `[up-watch]`) attribute.
