### ISSUE TITLE
Click event handlers added via `up.on` to a disabled button fire when clicking on its child element in Chrome/Safari

### ISSUE THREAD

**Issue by angelikatyborska** [unpoly/unpoly#443]
### Bug description

I have a button with a click event handler. The button can be temporarily disabled. The button also contains some span elements as children. If I add a click event handler to the button with `up.on('click', 'selector', ...)`, in Chrome and Safari, the click event handler is going to fire when clicking on the button's children, but not on the button itself. In Firefox, the button behaves as expected - you cannot fire click events at all on a disabled button, not even on its children. If I add a click event handler to the button using `up.compile` + `element.addEventListener`, the button behaves as expected in all browsers - you cannot fire click events on it at all, not even on its children.

### Reproduction project

Code pen project: https://codepen.io/angelikatyborska-the-bold/pen/qBKqzqY

### Steps to reproduce the behavior:

1. Go to reproduction project linked above in Chrome or Safari
2. Click on the green span in the button "Disabled button with a span with a click handler added via Unpoly"
3. See an alert opened by the click event handler - this should not have happened, the button is disabled.

I am attaching a video at the bottom that shows this behavior.

### Expected behavior

When using `up.on('click', ...)`, you should not be able to trigger click events on disabled buttons at all, in any browser, even when clicking its children.

### Browser version

 - OS:  macOS 12.6
 - Browsers: with the bug: Chrome Version 107.0.5304.87, Safari Version 16.0 (17614.1.25.9.10, 17614). Without the bug: Firefox 107.0b9 (64-bit)

### Additional context

Unpoly version 2.6.1 (current highest), I didn't test in other versions.

https://user-images.githubusercontent.com/7852553/200774202-3f77b98e-dd5e-4720-ab57-fcd793c71bce.mov

**Comment by adam12** [comment]
Confirmed on Unpoly 3.2.0 as well.
