### ISSUE TITLE
Forms won't submit when form ID contains a slash

### ISSUE THREAD

**Issue by foobear** [unpoly/unpoly#46]
Unpoly will not submit `<form>` tags with an `id` attribute that contains a slash.

The request is never made, and there is no error message in the browser console.
Enabling Unpoly logging also does not print any information.

Examples:

- Works: [id="test"](https://jsfiddle.net/4ud8emfx/2/)
- Fails: [id="/test"](https://jsfiddle.net/4ud8emfx/1/)
- Fails: [id="test/test"](https://jsfiddle.net/4ud8emfx/3/)

I'd expect Unpoly to behave as it would without any slashes inside the ID.
If that is not possible, an error should be thrown.

**Comment by OvermindDL1** [comment]
That might be because `/` is [invalid](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) in HTML4 and earlier (although the restriction was lifted in HTML5).  Initially (and if you want to be sure it works in all browsers) the HTML `id` attribute is restricted to the set of `[a-zA-Z0-9_-]`

**Comment by triskweline** [comment]
I'm assuming submitting such a form would trigger a replacement for `form#test/test`, which is an invalid CSS selector.

@foobear What's your use case for using slashes in IDs?

**Comment by foobear** [comment]
Good point. While `form#test/test` is an invalid CSS selector, the form ID would still be valid HTML5.

Maybe Unpoly could transform its "default" selector generated by the form ID to something that works, like `form[id="test/test"]`. However, I am not sure if this could cover all cases and if Unpoly would need to do it.
Throwing an error would be fine for me. Since jQuery or `document.querySelector` cause an error, I'd have expected to see one, too.

The slashes in IDs already existed in the application "because of reasons". In this case I could change the application to not use slashes in IDs.

**Comment by triskweline** [comment]
I've seen one other case where slashes where used (inlining templates in AngularJS).

If it is valid HTML5 we should make some effort to support it with the `[id="test/test"]` approach.

I believe this could be a small change here:
https://github.com/unpoly/unpoly/blob/d007155a5c0f0a7cec14c7501c3e03d937f723b1/lib/assets/javascripts/unpoly/util.coffee#L191
https://github.com/unpoly/unpoly/blob/d007155a5c0f0a7cec14c7501c3e03d937f723b1/spec_app/spec/javascripts/up/util_spec.js.coffee#L277

**Comment by OvermindDL1** [comment]
> If it is valid HTML5 we should make some effort to support it with the [id="test/test"] approach.

Maybe only do that if it is an invalid `#...` selector as I think doing it that way is slightly slower?

**Comment by triskweline** [comment]
Yeah, definitely only when there's a weird character in the ID.

**Comment by triskweline** [comment]
Will be fixed in the next release.
