### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History'

### ISSUE THREAD

**Issue by okliv** [unpoly/unpoly#461]
I have this weird bug on production for particular `up` links (for most `up` links it works like expected). Production server has `https` enabled. Locally on development without ssl - everything works fine... can't reproduce it because i suggest there is something in domain name ad/or protocol parsing.

![image](https://user-images.githubusercontent.com/884634/222922341-2cf92c85-5335-4c8a-9c72-34607b085667.png)

I tried 2.6.1, 2.7.2 and even 3.0.0-rc2 versions - no luck

different browsers - all the same, except Safari gives slightly different error

    SecurityError: Blocked attempt to use history.pushState() to change session history URL

can provide more specific information but do not know what exactly can be helpful in advance

**Comment by adam12** [comment]
That indeed is interesting. I wonder if it's CSP related somehow? Do you set a `Content-Security-Policy` header in any of your responses?

**Comment by okliv** [comment]
that is all of Response Headers

![image](https://user-images.githubusercontent.com/884634/222924377-fb6a20d1-5fc3-4565-92f8-ae3d223da20a.png)

Request Headers

![image](https://user-images.githubusercontent.com/884634/222924509-fcd6d5ee-4590-44fb-abe2-6310d61d9aa9.png)

**Comment by adam12** [comment]
Your `x-up-location` is missing `https`, so I wonder if that's causing the havoc. What's software are you using on the backend? It looks like nginx is the reverse proxy, are there any others?

You want to likely ensure that `X-Forwarded-Proto` is being pushed all the way to your application, and it knows what to do with it.

**Comment by okliv** [comment]
true. thanks! i have added

    proxy_set_header X-Forwarded-Proto https;

to nginx conf and current error disappeared. but i got new ones :). i need to study it if it is mine. to be continued... or not

thanks again

**Comment by okliv** [comment]
i returned to 2.7.2 and all errors disappeared completely. not sure if such strict headers processing can be omitted by `unpoly` (regular http(s) requests went flawlessly for my webserver without `X-Forwarded-Proto`)  but my current issue has been solved. thanks again.
