### ISSUE TITLE
`HTMLWrapper#wrap` can break previously valid HTML

### ISSUE THREAD

**Issue by makmic** [unpoly/unpoly#462]
### Bug description

I encountered a strange behavior where `up.layer.open({ content: someElement.innerHTML })` resulted in a new modal with a partially broken DOM.  It turns out that [HtmlWrapper#wrapMatch](https://github.com/unpoly/unpoly/blob/master/src/unpoly/classes/html_wrapper.js#L29) is replacing `<script>` tags with `'<meta name="script" value=....` on the given HTML - even if the script tag was only part of a JSON payload:

```js
  wrapMatch(match) {
    this.didWrap = true

    // Use a tag that may exist in both <head> and <body>.
    // If we wrap a <head>-contained <script> tag in a <div>, Chrome will
    // move that <div> to the <body>.
    return '<meta name="' + this.attrName + '" value="' + u.escapeHTML(match) + '">'
  }
```
 
The pitfall is not too apparent: The newly inserted double quotes can break DOM strings like these:

```html
<div data-json='{"html":"<script>alert(\\"I am valid unescaped HTML/JS\\");<script>"}'></div>
```

### Reproduction project

Link to a minimal Glitch project: https://spurious-tan-care.glitch.me/

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Open the console and confirm the error message

See also https://glitch.com/edit/#!/spurious-tan-care?path=scripts.js%3A1%3A0 for the code editor

### Expected behavior

I would expect `(new up.HTMLWrapper('script')).wrap(domString)` not to change the HTML snipped mentioned above.

### Browser version

 - OS: Linux
 - Browser Chrome
 - Version 110

**Comment by triskweline** [comment]
While this is now fixed, you should consider configuring your JSON encoder to it escapes angle brackets in its JSON output. Otherwise user input in a JSON string could potentially close `<script>` or `<noscript>` elements.
