### ISSUE TITLE
up.compiler batch throwing error

### ISSUE THREAD

**Issue by jakemake** [unpoly/unpoly#463]
### Bug description

up.compiler with batch set to true throwing error While compiling <a class=​"lightbox" data-fslightbox=​"gallery" href=​"/​images/​venicles/​cl5umsxcr009op2jl8vrpc5xb.jpg">​…​</a>​: TypeError: compiler.apply is not a function

My script is simple 
up.compiler('a.lightbox', function (element) {
  refreshFsLightbox()
}, true)

### Reproduction project

Link to a minimal [Glitch](https://glitch.com/) project or [CodePen](https://codepen.io) that reproduces the issue.

We recommend using our Glitch template that loads Unpoly for you:
https://glitch.com/edit/#!/empty-unpoly-project

### Steps to reproduce the behavior:

1. Create elements
2. apply class
3. add up.compiler('a.lightbox', function (element) {
  refreshFsLightbox()
}, true)
4. See error in console

### Expected behavior

applying function only once without error

### Browser version

 - OS: Mac os ventura
 - Browser: Brave (chromium)

**Comment by adam12** [comment]
I think you want to pass your options as the second argument.

```javascript
up.compiler('a.lightbox', { batch: true }, function (element) {
  refreshFsLightbox()
})
```
