### ISSUE TITLE
Allow ignoring the query parameters (search) for current links in navigation feedback

### ISSUE THREAD

**Issue by spapas** [unpoly/unpoly#465]
Hello friends, I've got a couple a `/foo/` view that dispalys a list of results and a `GET` form. The user can filter these results using the form so he'll get a URL similar to `/foo/?id=32`. The problem is that the navigation feedback works fine only when the url is `/foo`/ not when the url is `/foo/?id=32`. It seems that this is the intended behavior as seen from the docs https://unpoly.com/up-nav#when-is-a-link-current.

I could resolve that issue by adding an up-alias similar to `up-alias="/foo/?*"` in my url in the nav bar. However because I have a number of similar urls with this functionality and because I may add more in the future and forget adding the up-alias thingie I'd really prefer to make this behavior default, similar to how urls with hash `#` work  (see #284 ) . 

Is this possbile somehow ? I understand that there are situations where matching on the search parameters is not the intended behavior so maybe we could add some kind of configuration on `up.feedback.config` ? I.e `ignoreSearch` with a default value of false to keep the current behavior ? 

If it ain't possible I guess I'd bite the bullet and add the `up-alias` aliases.

Kind regards,
Serafeim

**Comment by triskweline** [comment]
You could use a macro to set those aliases automatically:

```js
up.macro('nav a[href]', (link) => {
  link.setAttribute('up-alias', link.href + '?*')
})
```

I'm leaning into not additing additional configuration for this, as query params usually influence the page response and we have aliases for the remaining cases.
