### ISSUE TITLE
`a[up-accept-location]` Attribute Not Working

### ISSUE THREAD

**Issue by nikitazdvijkov** [unpoly/unpoly#467]
I created a repo to document this issue. Here is a link: <https://github.com/nikitazdvijkov/unpoly-issue>

I am pasting the README below:

---

# Unpoly Problem: `a[up-accept-location]` Attribute Not Working

This repo documents a problem I am having with [Unpoly](https://unpoly.com) that I am asking for help with.

I cannot replicate the behavior of the "new company" button in the Unpoly demo app on the ["all companies" page](https://demo.unpoly.com/companies).

## Desired Behavior

1. I navigate to the "companies" page.
2. I click on the "add company" button.
3. The "new company" form pops up in a modal.
4. I submit a valid form.
5. The modal is "accepted" (using the terminology of the Unpoly documentation) and goes away. I am returned to the underlying "companies" page, where the "list of companies" is updated. Only the "list of companies" element (an unordered list with ID `#companies-list`), should be updated. The random number in the footer should not change.

All of the above steps except #5 work as desired.

## Actual Behavior

Instead, this is what happens:

Steps 1 through 4 same as above, then I am redirected to the "example company" page.

## Getting Started

Node version: 18

Browser: Chromium 108

Recommended (optional) VSCode extensions for template string syntax highlighting (pick one):

- ["Comment tagged templates" by Matt Bierner](https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates) (~16k installs) (preferred)
- ["es6-string-html" by Tobermory](https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html) (~270k installs)

## Endpoints

This is a very simple demo app. These are all of its endpoints:

| Method | Path           | Purpose                                   |
| ------ | -------------- | ----------------------------------------- |
| GET    | /              | Home                                      |
| GET    | /companies     | Companies list                            |
| POST   | /companies     | Add company                               |
| GET    | /companies/new | Form for adding companies                 |
| GET    | /companies/:id | Individual company (dummy implementation) |

## Modal Launch

The "add company" button (from `views.js`):

```html
<a
  href="/companies/new"
  up-layer="new"
  up-accept-location="/companies/$id"
  up-on-accepted="up.reload('#companies-list'); alert('...');"
>
  <button>+ Add company</button>
</a>
```

**The `[up-accept-location]` attribute doesn't appear to be working.**

## Successful Form Submission

On successful submission, the "new company" form redirects to `/companies/<id>`, where the `<id>` is randomly generated on the fly, and is meant to be a placeholder for demonstration purposes. This can be seen here (from `main.js`):

```js
// Redirect status code 302
res.redirect(`/companies/${views.randomNumber()}`);
```

**This should cause the modal to close, but it doesn't.**

## Manually Reload Companies List

On the "companies" page, there is a button to manually reload the `#companies-list` element. It works. You will notice that the companies list changes while the random number in the footer remains the same. This button's `[onclick]` attribute is the same as the "new company" button's `[up-on-accepted]` attribute.

## Form Validation

Form validation via Unpoly works flawlessly. This is not an issue. From `views.js`:

```html
<form method="post" action="/companies" up-validate>...</form>
```

**Comment by nikitazdvijkov** [comment]
Never mind, I think I got it--was missing an `[up-submit]` attribute on the form element

Will confirm later

**Comment by nikitazdvijkov** [comment]
Adding the `[up-submit]` attribute to the form fixed the issue in the above demo app.

However, that alone didn't fix the issue in my proprietary closed-source app. There turned out to be a second issue:

Context: very similar setup. On successful form submit (e.g. `POST /companies`), the response redirects to the newly created resource (e.g. `/companies/acme-incorporated`). **The problem was that the newly created resource page did not have a `<main>` tag / [main target](https://unpoly.com/up.fragment.config#config.mainTargets)!**

(`up.log.enable()` was helpful for figuring this out.)

You can consider this issue closed as far as I am concerned. I'll leave that up to maintainers.

Might be worth adding a note about this peculiarity to the documentation. I consider it peculiar because I didn't consider the newly created resource's page's main target to be relevant in this case since it's not getting rendered. I don't yet have a clear enough mental model of how Unpoly works to contribute that piece of documentation myself.

Thank you for Unpoly!

**Comment by adam12** [comment]
Thanks for reporting back. Let's see what @triskweline thinks about whether this needs further documentation or not.

Do you happen to remember the error? I'd presume Unpoly to just fall back to `<body>` in this case.
