### ISSUE TITLE
Demo App: scroll positions

### ISSUE THREAD

**Issue by fabien** [unpoly/unpoly#47]
I'm playing with the enhanced version of the demo at http://demo.unpoly.com/ but unlike the text on this slide http://triskweline.de/unpoly-rugb/#/21 claims, I don't see the scrollbar position being maintained when switching back and forth from the 'Edit' view.

Is this supposed to work? What should I be seeing?

**Comment by triskweline** [comment]
Hi @fabien. The demo was using an ancient version version of Unpoly, I just updated it.

Unpoly restored previous scroll positions when you use the back button. This mimics standard browser behavior for non-JS page changes. You should be able to observe it by opening http://demo.unpoly.com, scrolling down the left pane, then press "Edit". When you now go back, the left pane should be at the position you scrolled it to.

Unpoly doesn't by default restore scroll position when clicking links (like the "Cancel" link on the form). Again we're trying to emulate standard browser behavior. If you *do* explicitely want a link to restore a previous scroll position, you can give the link an `[up-restore-scroll]` attribute.

**Comment by fabien** [comment]
Thanks for the heads-up! Do you have the source of the demo app (or any other) available online?

**Comment by triskweline** [comment]
The source for demo.unpoly.com is here: https://github.com/makandra/upjs-demo
This was built for a presentation to a small group of people, so I'm afraid it's not well documented.

It would be great if we had some sample apps with minimal setup to help people get started.
