### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isConnected')  

### ISSUE THREAD

**Issue by adam12** [unpoly/unpoly#476]
### Bug description

Targeting an element with `up-validate` that uses `up-id` raises an uncaught exception.

### Reproduction project

https://glitch.com/edit/#!/laced-elegant-shaker?path=index.html%3A20%3A17

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Change select box one (select box two is a no-op)
3. Observe error in console
4. Change `up-id` to `id` in HTML markup
5. Repeat
6. Observe no error in console

### Browser version

 - OS: MacOS
 - Browser Chrome
 - Version 112

### Additional context

Worked on Unpoly v1. I've skipped v2, going direct to v3 with unpoly-migrate. No warnings from up-migrate.

**Comment by adam12** [comment]
> You would need to target it like this:

Your solution works for me.

> I think the issue here is that Unpoly should print a more helpful error when a validation target selector cannot be matched with an element.

I agree. Perhaps we should throw somewhere around here? https://github.com/unpoly/unpoly/blob/a69e47ac26769028412ab2f006e1f2acc393373a/src/unpoly/classes/form_validator.js#L74

**Comment by triskweline** [comment]
That was the right place.

It revealed some nasty edge cases that are now also fixed.

**Comment by adam12** [comment]
Cool. Thanks for the fix.
