### ISSUE TITLE
Respond speed on mid-tier and Low-tied mobile

### ISSUE THREAD

**Issue by proyb6** [unpoly/unpoly#48]
How fast can Unpoly render?

**Comment by triskweline** [comment]
Unpoly does not render on the client. It swaps out HTML fragments that have been rendered on the server. Hence it should be very friendly to low-end mobile devices, as long as they have a network connection.

**Comment by proyb6** [comment]
Each time you tried to open the side bar that slide out after burger menu is clicked on 3G network is perceived as slow that last 1 second or more compare to the traditional responsive navbar.

**Comment by OvermindDL1** [comment]
> Each time you tried to open the side bar that slide out after burger menu is clicked on 3G network is perceived as slow that last 1 second or more compare to the traditional responsive navbar.

Well, that's because it is making a network request, have it display a loading indicator or so (which unpoly has support for), after all unpoly can't display any faster than the server response gets there.  ;-)
