### ISSUE TITLE
CSP blocking `up.reload` even with `unsafe-eval`

### ISSUE THREAD

**Issue by alexandremjacques** [unpoly/unpoly#493]
### Bug description

Whenever my links opens a new layer and uses the `up-on-accepted` directive, I'm receiving an error saying that CSP is not allowed to execute scripts:

```
Error: Your Content Security Policy disallows inline JavaScript (up.reload('#tasks-list')). See https://unpoly.com/csp for solutions.
 ```

I've set my server-side (Django app) to respond with headers specified in the [docs](https://unpoly.com/csp#solution-3-relax-your-csp):

<img width="1058" alt="SCR-20230517-hotu" src="https://github.com/unpoly/unpoly/assets/1953298/5bffaa1e-7153-431b-9220-a6fa4449e6f0">

### Reproduction project

Can't reproduce in glitch.

### Steps to reproduce the behavior:

1. Create a link to a new layer with a `up-on-accepted` directive that reload contents:
```
<a href="<url>"
   up-layer="new"
   up-size="large"
   up-accept-location="/trips/*/details"
   up-on-accepted="up.reload('#trip-details')">
    <i class="ti ti-history icon"></i>
</a>
```
2. Layer may contain a form that when submitted redirects user to the specified URL on `up-accept-location`
3. Console shows the mentioned error.

### Expected behavior

Should not throw error since CSP headers are set.

### Browser version

 - OS: macOS
 - Browser Chrome

### Additional context

I'm seeing this after upgrading from 2.7.7 to 3.1.1 (and an update to Django Framework)

**Comment by triskweline** [comment]
When you're seeing the error, what is the value of `up.browser.canEval()`?

**Comment by alexandremjacques** [comment]
It states `false`.

<img width="1102" alt="image" src="https://github.com/unpoly/unpoly/assets/1953298/ef4cb038-679f-46e3-8459-6c6c4ee56bab">

Same request:
<img width="1064" alt="image" src="https://github.com/unpoly/unpoly/assets/1953298/2f10defb-25bf-4160-abb0-eb1e3351880f">

**Comment by triskweline** [comment]
That's curious. The function just tests if we can use `eval()` without an exception: https://github.com/unpoly/unpoly/blob/78b1dc0d5729d083e7cb9dfcb73272451c0a48a8/src/unpoly/browser.js#L63-L72

**Comment by alexandremjacques** [comment]
I'll leave my solution for reference:
I had an unnoticed `<meta>` tag configured on my base template. Apparently, browsers give precedence to what is in the there over from what is comming in the CSP headers.
