### ISSUE TITLE
Clarification / Example for docs

### ISSUE THREAD

**Issue by seanculver** [unpoly/unpoly#50]
I was hoping that you could provide some clarification and possibly a dummy example of this line in the Modal Dialog docs.

"By default the dialog automatically closes when a link inside a modal changes a fragment behind the modal. This is useful to have the dialog interact with the page that opened it, e.g. by updating parts of a larger form."

Specifically I'm interested in the e.g. "By updated parts of a larger form". 

I'm using a modal to bring up a form, of which I want the resulting save to update the form underneath the modal. Just a note, i'm using "up-target" on the form so that in the modal when there are validation errors it will display them inside the modal.  

How can I update the underlying form the most idiomatic way?

Thanks!

**Comment by adam12** [comment]
Is your `up-target` outside of the modal object? If you're returning the proper status codes on failure (400 or 422), Unpoly will default to using the `<form>` element as a fail target. You can of course override this with `up-fail-target`.

So:

1. Modal form has an `up-target` of the main form, or an element inside that form.
2. The route that handles the modal form submit must return status 400 or 422 if invalid.
3. During posting to the modal form action, on success, re-render the main form, or just the `up-target` selector.
4. On post failure, re-render modal content. Unpoly will extract the form the `up-target` was attached to originally.

**Comment by triskweline** [comment]
Exactly as @adam12 says.

If you want to see an example of this:

- Got to http://demo.unpoly.com
- Click "Start enhanced"
- Edit a card
- Observe how the form appears. Feel free to make some unsaved changes to the form.
- Select *Change pattern* to open a modal
- Selecting a modal will change the underlying page

**Comment by seanculver** [comment]
@adam12 Hey I wanted just to respond, that it did answer my question. And thank you for your quick response!

@triskweline  I didn't even realize there was a demo page! It might be worth putting as a top level nav link on your site.

Still loving using Unpoly, thanks for the great OSS!

Cheers,
Sean
