### ISSUE TITLE
Browser history not updating after form post to ASP.NET Core backend.

### ISSUE THREAD

**Issue by sturatcliffe** [unpoly/unpoly#52]
Hey,

I have a standard HTML form tag:

```
<form method="post" up-target="body" action="/login">
 ...
</form>
```

And an ASP.NET Core backend controller that processes the request and redirects to the homepage (GET request):

```
public async Task<IActionResult> Login(Login.Command command)
{
    Log.ForContext<AuthenticationController>().Information($"Attempting login: {command.Email}");
    await _mediator.Send(command);
    return Redirect("/");
}
```

As expected the form is submitted via AJAX, and the body content is replaced with the home page on successful login. However, the browser history doesn't update, i.e. the URL remains on "/login".

According to the docs, this should just work based on the redirection to a GET request. Dev tools is showing what I'd expect it to see:

![image](https://user-images.githubusercontent.com/17248652/35851492-2059d10e-0b20-11e8-8144-c444222d8834.png)

I also followed the server protocols section of the docs and added a middleware to add the recommended headers on 302 redirects:

```
app.Use(next =>
{
    return async context =>
    {
        await next(context);

        if (context.Response.StatusCode == StatusCodes.Status302Found)
        {
            context.Response.Headers.Add("X-Up-Method", "GET");
            context.Response.Headers.Add("X-Up-Location", context.Response.Headers["Location"]);
        }
    };
});
```
Which sets the headers appropriately:

![image](https://user-images.githubusercontent.com/17248652/35851681-a2724284-0b20-11e8-8291-8d361b2521eb.png)

But still no history updates! 

I've tried using different Redirect methods on the server in case it made a difference, i.e. straight "Redirect("/")" as well as ASP.NET Core helpers for redirecting to actions - "RedirectToAction("Login")". Everything else is working fine, page fragment updates from links, opening pages in modals etc etc.

Any suggestions on what I'm doing wrong?

Cheers!

**Comment by triskweline** [comment]
Although I'm not familiar with .NET, it looks like you're doing everything correctly.

Is your app accessible on a testing server where I can take a closer look?

**Comment by sturatcliffe** [comment]
It's not, but I've just replicated the issue in a barebones project and pushed it to Azure here:

http://unpoly.azurewebsites.net/

No need to enter anything in the text boxes, just hit login and the redirect happens with no URL change.

**Comment by adam12** [comment]
One difference I noted between my Rack implementation is that I send a full URL in `X-Up-Location`, where you only send a path. I wonder if that could be the culprit?

**Comment by sturatcliffe** [comment]
Just tried forcing the full URL through and still no dice! :(

**Comment by adam12** [comment]
Can you try removing the conditional in your middleware, and ALWAYS send the headers?

**Comment by triskweline** [comment]
Last comment by @adam12 made me realize where the error was: You need to send the `X-Up-Location` with the response for the redirect target, not the response that is doing the redirect.

**Comment by triskweline** [comment]
Good thing about this issue: It made me realize that modern browsers have [`XMLHttpRequest.responseURL`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL).

It's not currently supported by IE11, but it looks like we can detect redirects without `X-Up-Location` :)

**Comment by sturatcliffe** [comment]
If it helps anybody in future, working middleware is:

```
app.Use(next =>
{
    return async context =>
    {
        if (context.Request.Method == "GET")
        {
            context.Response.Headers.Add("X-Up-Method", "GET");
            context.Response.Headers.Add("X-Up-Location", context.Request.Path.ToString());
        }

        await next(context);
    };
});
```

Thanks for your help @adam12 @triskweline!
