### ISSUE TITLE
Unpoly 0.53.0 raises `Uncaught (in promise)`

### ISSUE THREAD

**Issue by denzelem** [unpoly/unpoly#53]
I upgraded unpoly from `0.50.2` to `0.53.0`. Now I see the following exception when having a POST request with status code `422`:

```
// this is a normal console log
POST http://localhost:300/new 422 (Unprocessable Entity)

// this is the new exception
Uncaught (in promise) new:1
```

**Comment by denzelem** [comment]
Sorry, this was not an issue with unpoly. The behaviour didn't changed in 0.53.0.

**Comment by triskweline** [comment]
Reproduction steps and expected behavior or I cannot help.

**Comment by triskweline** [comment]
Unpoly 0.53.2 silcences this warning in its own event handlers.
