### ISSUE TITLE
Using up.on with the passive option set to true raises an unexpected error

### ISSUE THREAD

**Issue by denzelem** [unpoly/unpoly#531]
### Bug description

Using [up.on](https://unpoly.com/up.on) with the [passive](https://unpoly.com/up.on#options.passive) option set to `true` raises an unexpected error.

### Reproduction project

```html
<div data-scollable></div>
<p>Some line</p>
<p>Some line</p>
<p>Some line</p>
<p>Some line</p>
<p>Some line</p>
<p>Some line</p>
<p>Some line</p>
<p>And many more...</p>
```

```js
up.compiler('[data-scollable]', (element) => {
  function onScroll() {
    console.log('scroll')
  }

  up.on('scroll', onScroll, { passive: true })
  
  return () => {
    up.off('scroll', onScroll)
  }
})
```

- Working: `up.on('scroll', onScroll)`
- Not working: `up.on('scroll', onScroll, { passive: true })`

https://jsfiddle.net/0pdhk6vb/

### Steps to reproduce the behavior:

1. Scroll down
2. See error `Uncaught TypeError: element.closest is not a function`

![image](https://github.com/unpoly/unpoly/assets/12035693/5f0b63dc-23bf-4f77-b96e-9789e7e77c6b)

- element: `document`
- event `scroll`

### Expected behavior

Listening to `scroll` with the passive flag should not raise an error.

### Browser version

 - OS: `Ubuntu`
 - Browser: `Google Chrome 116.0.5845.187 `
 - Unpoly: `3.3.0`

### Additional context

This error occurred after an Upgrade from `Unpoly 2.7.1` to `Unpoly 3.3.0`.

**Comment by niklas-hasselmeyer** [comment]
It seems that argument order is important now.
```
up.on('scroll', onScroll, { passive: true }) # this raises an error
up.on('scroll', { passive: true }, onScroll) # this works
```

**Comment by triskweline** [comment]
The options always needed to go before the handler function. If it happend to work differently before then that wasn't documented behavior.
