### ISSUE TITLE
unpoly.min.js (29.2 KB) seems not to be true

### ISSUE THREAD

**Issue by papakay** [unpoly/unpoly#54]
The information that unpoly.min.js is 29.2 KB seems not to be true. I downloaded the latest version and found out the file size is 104KB.

<img width="720" alt="screen shot 2018-03-04 at 2 36 42 am" src="https://user-images.githubusercontent.com/5013738/36941158-0b081394-1f55-11e8-85a3-7e4a7efd33b3.png">

**Comment by adam12** [comment]
It's likely using the gzip'd value, which is near accurate (only a few bytes off):

`-rw-r--r--@ 1 adam12  staff  29936  3 Mar 15:25 unpoly.min.js.gz`

**Comment by triskweline** [comment]
I updated unpoly.com to explain that these are gzipped values.

Sorry about the confusion.
