### ISSUE TITLE
up-alias not matching URL query string with asterix after shash

### ISSUE THREAD

**Issue by marc-mabe** [unpoly/unpoly#542]
### Bug description

I have a nav link with up-alias `/campaign/*` to match all URLs starting with `/campaign/`.
This works fine for URLs like `/campaign/new` but as soon as using query parameter (like `campaign/?test`) it's not matching anymore.

Interestingly it works with `/campaign*` but I do need the leading slash. 

### Reproduction project

https://glitch.com/edit/#!/stream-salt-woodpecker

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Click on 'click here'
3. See test link misses class `up-current`

### Expected behavior

Aliases like `/test/*` should match `/test/?whatever` as well.

### Browser version

 - OS: Linux
 - Browser Firefox
 - Version 118

**Comment by marc-mabe** [comment]
Is there any update on this?

**Comment by adam12** [comment]
Could you confirm the Glitch URL still works? I'm unable to get it working on my side.
