### ISSUE TITLE
nested up-hungry removes inner hungry elements

### ISSUE THREAD

**Issue by mfazekas** [unpoly/unpoly#545]
### Bug description

Nesting up-hungry doesn't seems to work with 3.3

### Reproduction project

https://difficult-green-sunshine.glitch.me/base.html

### Steps to reproduce the behavior:

1. open https://difficult-green-sunshine.glitch.me/base.html
2. press link.html
3. pink counters are removed

   ![image](https://github.com/unpoly/unpoly/assets/52435/023c2449-f83f-459d-a33e-5daf536f1db1)

### Expected behavior

See https://difficult-green-sunshine.glitch.me/base2.html for unpoly2 behaviour, counters replaced correctly. 3.2 also works fine:

https://difficult-green-sunshine.glitch.me/base3.html

   ![image](https://github.com/unpoly/unpoly/assets/52435/72df5b03-68c0-4348-8d6d-e9201a4c289e)

 
### Browser version

 - OS: MacOS 13.6 
 - Browser: Safari
 - Version: 16.6

**Comment by triskweline** [comment]
This should be fixed in 3.5.0.

I generally recommend not to over-use the hungry mechanism and prefer explicit targets where possible.
