### ISSUE TITLE
up-transition speed example

### ISSUE THREAD

**Issue by bichonnages** [unpoly/unpoly#56]
Hi!

Thanks for this great framework. It is very easy to use and extremely functional!

As a beginner in JS, I would like to know if you could provide an example for setting the speed/duration of a predefined up-transition (I am using "move-up").
Also, it would be amazing if you could give us more example for integrating JS custom scripts. It seems that the up.compiler function needs a selector. I might be wrong, but some custom scripts do not always use a selector, no?

Hope I am not asking too much!

All the best,
MB

**Comment by triskweline** [comment]
Hi @bichonnages !

> As a beginner in JS, I would like to know if you could provide an example for setting the speed/duration of a predefined up-transition (I am using "move-up").

I saw that this is missing from the docs currently -- I will add that soon.

If you use the unobtrusive `[up-animation]` attribute, you can set the duration like so:

```html
<a up-target=".target" up-transition="move-up" up-duration="200" >
```

If you're using the JavaScript API, you can set the duration like so:

```javascript
up.follow($link, { duration: 200 })
```

> Also, it would be amazing if you could give us more example for integrating JS custom scripts. It seems that the up.compiler function needs a selector. I might be wrong, but some custom scripts do not always use a selector, no?

We're always attaching behavior to the elements that need them. E.g. a date picker popup should be activated when focusing `input.date-picker`, a lightbox plugin should be activated when clicking on an `a.lightbox-opener`. This way it is clear what code becomes active when an element enters the DOM, and what we need to clean up when an element leaves the DOM.

All JS code that I'm using at my work pertains to an element in some way, and can be activated with a compiler. Do you have an example for custom code that is giving you trouble?

**Comment by bichonnages** [comment]
Thanks for the reply!

About JS, I actually checked some of my code: I was wrong—obviously—all my custom scripts have a selector/DOM element.

I will do some testing on my own in order to learn more!

**Comment by triskweline** [comment]
:)
