### ISSUE TITLE
Incorrect docs: Event target for 'up:form:submit' is not always the form

### ISSUE THREAD

**Issue by panda-madness** [unpoly/unpoly#578]
### Bug description

According to the [docs](https://unpoly.com/up:form:submit) `event.target` for this event (as well as the handler's second parameter) should be the submitting form. However, currently both are set to the submitter button instead of the form.

### Reproduction project

The issue can be reproduced by going to the unpoly [demo](https://demo.unpoly.com/tasks), opening the dev console, running the following code: 

```js
up.on('up:form:submit', (event, form) => console.log(event.target, form));
```
and creating/editing a task on that page. You will notice that an `input[type=submit]` gets logged twice.

**Comment by triskweline** [comment]
The docs are outdated here. The `event.target` is the interaction origin, which is either a focused element within the form, the pressed submit button, or the form if nothing more specific is known.

**Comment by panda-madness** [comment]
I ended up solving my use case by adding a delegation selector like so:

```js
up.on('up:form:submit', 'form', (event, form) => console.log(event.target, form));
```

I could also just query the submitting form via `event.target.closest('form')`, though this would not handle the (edge) case where the submitter is outside the form. I sadly cannot getch the form via `button.form` because my submitter is a web component button (Shoelace's `sl-button`) and not a regular one, and they have not yet implemented the Form Internals API yet.

In any case, thanks for clarifying!

**Comment by triskweline** [comment]
Reopening because we need to fix the docs.

**Comment by triskweline** [comment]
> I sadly cannot fetch the form via button.form because my submitter is a web component button (Shoelace's sl-button) and not a regular one

Maybe this can help with a library like Shoelace:

- You can make Unpoly aware of custom submit buttons by pushing a selector to [`up.form.config.submitButtonSelectors`](https://unpoly.com/up.form.config#config.submitButtonSelectors).
- You can make Unpoly aware of custom input fields by pushing a selector to [`up.form.config.fieldSelectors`](https://unpoly.com/up.form.config#config.fieldSelectors).

**Comment by panda-madness** [comment]
I've already added all the form inputs I need to `fieldSelectors`. What does `submitButtonSelectors` do exactly?
