### ISSUE TITLE
Is up-disable broken?

### ISSUE THREAD

**Issue by uweschmitt** [unpoly/unpoly#581]
### Bug description

I'm just learning unpoly and follow the tutorials from the website. In my case the `up-disable` attribute does not appear to have any effect.

### Full code

I wrapped the code from https://unpoly.com/disabling-forms:

```
<!DOCTYPE html>
  <html>
   <head>
      <link rel="stylesheet" href="unpoly.css" />
      <script src="unpoly.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/unpoly@3.7.3/unpoly.min.js"></script>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/unpoly@3.7.3/unpoly.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/unpoly@3.7.3/unpoly-bootstrap5.min.css">
    </head>
    <body>
        <main>
         <form up-disable="button" action="/">
          <input type="text" name="email">         <!-- will NOT be disabled -->
          <input type="password" name="password">  <!-- will NOT be disabled -->
          <button type="submit">Sign in</button>   <!-- will be disabled -->
          <button type="reset">Clear form</button> <!-- will be disabled -->
          </form>
        </main>

    </body>
  </html>
```
### Steps to reproduce the behavior:

When I load this page (tested on Firefox and Safari), the form shows but  the buttons are not disabled.

### Browser version

 - OS: Mac OS 14.2.1
 - Browser 1: Firefox  121.0.1 
 - Browser 2: Safari Version 17.2.1

**Comment by triskweline** [comment]
`[up-disable]` will only be used for forms that are handled by Unpoly. You need to give the form an `[up-submit]` attribute or configure Unpoly to [handle all forms](https://unpoly.com/handling-everything#handling-all-forms).

I fixed the example.

**Comment by uweschmitt** [comment]
@triskweline  Thanks!
