### ISSUE TITLE
Browser does not loose it's zoom state between page navigations on smartphones

### ISSUE THREAD

**Issue by Aiderlei** [unpoly/unpoly#608]
### Bug description

When I zoom in with two fingers in a smartphone with iOS (I tested iPhone SE22 in Safari) and then navigate to the next page, the page stays in a zoomed in state. I may potentially even see a port of the page with no readable text or interesting content. 

### Reproduction project
[Reproduction project](https://zesty-bubbly-samba.glitch.me/)

### Steps to reproduce the behavior:

1. Go to reproduction project linked above on iOS
2. Zoom into the page, such that a vertical and horizontal scrollbar appear.
3. Click on 'Link to other page'
4. See the next page in a zoomed in state. 

### Expected behavior

I would expect that the next page is the opened "in the normal zoom state", i.e. it resets the zoom in from the last page. This is at least the browsers default most other pages. 

### Browser version

 - OS: iOS
 - Browser Safai 
 - Version 17.3.1

**Comment by hpvd** [comment]
I can reproduce it with mobile FF on Android.

But github has the same behavior:
zoom on here and navigate to:
https://github.com/unpoly/unpoly

In contrast, on other sites it zoom state is reset e.g see
https://www.heise.de/news/WLAN-Attacke-SSID-Verwechslungs-Angriff-macht-Nutzer-verwundbar-9720818.html
zoom and then click on the head logo for home

**Comment by triskweline** [comment]
I think that resetting zoom is a shortcoming of multi-page applications. It's a good thing SPAs (or SPA-like experiences as is Unpoly) keep the user's zoom choice.

If you do need to reset zoom choice when navigating, you could probably do something like this (untested):

```js
up.on('up:location:changed', function(event) {
  let viewportMeta = document.head.querySelector('meta[name=viewport]')
  if (viewportMeta) {
    viewportMeta.remove()
    document.head.append(viewportMeta)
  }
})
```
