### ISSUE TITLE
HTML lang attribute is not updated on link follow

### ISSUE THREAD

**Issue by alexandrerbb** [unpoly/unpoly#614]
### Bug description

From the docs [here](https://unpoly.com/up-meta) and [here](https://unpoly.com/a-up-follow#up-meta-tags), meta tags are beeing extracted and updated on link follow. 

I assume there are good reasons to update meta tags on the client side.

During my tests, I noticed that the HTML `lang` attribute is not beeing updated on link follow.

Is there any way to achieve that ?

### Expected behavior

Update of the `lang` attribut on page visit.

### Additional context

I tried adding a `[up-meta]` attribute to `<html>` element, as well as the following code line:

```js
up.history.config.metaTagSelectors = ["html"]
```

**Comment by triskweline** [comment]
Fixed in `master`, will release in 3.8.
