### ISSUE TITLE
Visiting URL with #hash-anchor and ?utm-query-params throws an exception

### ISSUE THREAD

**Issue by jakedowns** [unpoly/unpoly#62]
I'll work on putting together a reduced test case.

(using unpoly 0.37)

but the gist is:

- visiting a url with a ?queryParam=value1&someOtherParam=value2#hash-anchor
- throws: 
-- `Found origin reference (&) in selector [id='icgeun?utm_source=test&utm_medium=test&utm_campaign=test'], a[name='icgeun?utm_source=test&utm_medium=test&utm_campaign=test'], but no origin was given`
-- `commons.js?id=93bc878b821cd1108ebf:8955 Uncaught Error: Found origin reference ("&") in selector "[id='icgeun?utm_source=test&utm_medium=test&utm_campaign=test'], a[name='icgeun?utm_source=test&utm_medium=test&utm_campaign=test']", but no origin was given`

Which traces back to the `revealHash` method of the library

any ideas? is this something that can be disabled?

- if i visit with JUST the hash-anchor, or JUST the query params, everything works fine. it only breaks when BOTH are present

**UPDATE** issue remains after an upgrade to `0.56.4` https://cl.ly/2J0r1R1B3H1f

**Comment by triskweline** [comment]
Hi @jakedowns .

What is the actual string for the `#hash-anchor`?

Do you actually have `id` or `name` attributes with ampersands in them?

A reduced test case would be helpful. I recommend using Glitch for that. Here is a sample Glitch project that already loads Unpoly via CDN: https://glitch.com/edit/#!/bead-payment?path=index.html:1:0

**Comment by jakedowns** [comment]
thaks for the quick response @triskweline 

still trying to track this down... i feel like it may be some other dependency in my codebase conflicting, but, here's the exact querystring/hash-anchor:

`https://bead-payment.glitch.me/?utm_source=test&utm_medium=test&utm_campaign=test#icgeun`

one odd bit, is that in Chrome & Safari, once the page loads, the url becomes:
`https://bead-payment.glitch.me/#icgeun?utm_source=test&utm_medium=test&utm_campaign=test`

which then breaks in `resolveSelector` (at least on my codebase)

for some reason, resolveSelector isn't throwing an error when this reversal happens in this reduced test case. 🤔

even with a properly ID'd div present: https://precious-dust.glitch.me/?utm_source=test&utm_medium=test&utm_campaign=test#icgeun

is there some chance that Unpoly is flipping these values somehow?

**Comment by triskweline** [comment]
Thanks for the reproduction case, that helped a lot. I found that Unpoly would actually flip hash fragment and query string if both were present.

This has been fixed in 0.56.5.
