### ISSUE TITLE
Polling and / or SSE

### ISSUE THREAD

**Issue by g5becks** [unpoly/unpoly#63]
Hi, i'm keen on using unpoly in an upcoming project of mine . I have also been looking at intercoolerjs for this, and while unpoly seems to be more feature rich in some aspects, the polling and even more so SSE features of intercooler are pretty great. Any plans on adding anything similar to unpoly anytime soon?

If not, do you reckon i'd run into issues using both libraries together in the same app? Thanks..

**Comment by triskweline** [comment]
Thank you for considering Unpoly for your project. I'm sure you'll find it up to the task.

An `[up-poll]` attribute is planned for the future. What we have right now is [`[up-hungry]`](https://unpoly.com/up-hungry) which updates an element whenever a response happens to include it (but does not trigger requests on its own).

Note that you can often extend Unpoly with additional behavior. For instance, the [compiler](https://unpoly.com/up.compiler) below provides basic polling functionality:

```
up.compiler('[poll]', function($element) {
  var interval = parseInt($element.attr('poll') || 5000);
  var timer = setInterval(function() { up.reload($element) }, interval);
  return function() { clearInterval(timer) } // stop polling when element is removed
});
```

I have no plans to support SSE since (in my work) such use cases have always been solved by Web Sockets or similar, and I want to draw from my experience when extending Unpoly's API.

**Comment by adam12** [comment]
> up.compiler('[poll]', function($element) {
>   var interval = parseInt($element.attr('poll') || 5000);
>   var timer = setInterval(function() { up.reload($element) }, interval);
>   return function() { clearInterval(timer) } // stop polling when element is removed
> });

I use this technique on _many_ of my projects with much success (albeit, without the elegance of `up.reload()` - borrowing this one).

**Comment by Gee5ive** [comment]
Hi, thanks for the response. I think that the compiler that you guys mentioned will do the trick. Thanks.

**Comment by triskweline** [comment]
For production use I would probably also check [`document.hidden`](https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden) before reloading :)

**Comment by stevebauman** [comment]
+1 for this feature! Would really love for this to be included by default. Planning on using Unpoly for my next project, so the snippet will definitely do, thanks!

**Comment by stevebauman** [comment]
Had to update this example with the newest Unpoly with jQuery removed:

```js
up.compiler('[poll]', (element) => {
    let interval = parseInt(element.getAttribute('poll') || 5000);
    
    let timer = setInterval(() => {
        // Don't reload when document is hidden.
        if (! document.hidden) {
            up.reload(element);
        }
    }, interval);

    return function() {
        clearInterval(timer);
    };
});
```

Am absolutely loving Unpoly, what a gem this library is!

**Comment by triskweline** [comment]
Re-opening this now I've seen the use for this in the wild a number of time. I think `[up-poll]` would be a great addition to the `up.radio` package.

**Comment by jpic** [comment]
It works but can we *not* have the navigation feedback for this kind of "background" reloads?

**Comment by triskweline** [comment]
> It works but can we not have the navigation feedback for this kind of "background" reloads?

The `[up-poll]` attribute in [Unpoly 2](https://groups.google.com/g/unpoly/c/o82LsO89GZE) does not apply navigation feedback.

For the homebrew compiler above you may have success by removing the `.up-active` class manually:

```
up.reload(element)
up.util.microtask(() => element.classList.remove('up-active'))
```

I didn't test this.

**Comment by jpic** [comment]
Thank you for the heads up! Another problem I have with v1 is that if the user clicks a link that navigates them away before a poll visit is done, then they will navigate to the new URL as expected, but when the poll is done it will make them visit back to the first page that started the poll.

Is there any workaround in v1 and has this been taken care of in v2?

Thank you :tophat:

**Comment by adam12** [comment]
> has this been taken care of in v2?

This is solved in v2. Here's [the relevant slide](http://triskweline.de/unpoly2-slides/#101) from Henning's v2 presentation deck.

**Comment by triskweline** [comment]
This is fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0), which was released today.

**Comment by jpic** [comment]
> This is fixed in Unpoly 2, which was released today.

Oh my .... Such WOW!! All my respect :+1:

Congrats :tophat:
