### ISSUE TITLE
Is there an API for immediately prefetching links?

### ISSUE THREAD

**Issue by dgmcguire** [unpoly/unpoly#64]
I'm working on a library that aims to make web development use real-time updates as the default.  As such it would be highly advantageous if I could prefetch all annotated links on a page as soon as they enter the DOM.  I can understand why most websites wouldn't want this feature because the page might easily become out of sync with the data on the back-end.  However, since page updates happen in real-time with my library get all updates pushed to them over a websocket, it would be really cool to prefetch the fully rendered page and cache it so that it will instantly load on link clicks.  Is that possible?

For more info about my library if you're curious, check out https://gitlab.com/dgmcguire/texas

**Comment by triskweline** [comment]
Hi @dgmcguire! Thanks for your work on Texas.

You can preload a single link programmatically using [`up.proxy.preload(link)`](https://unpoly.com/up.proxy.preload).

After preloading the destination will load instantly if the link is [followed through Unpoly](https://unpoly.com/a-up-follow). We don't cache rendered DOM-trees though, only the response object with its HTML. While/after preloading you can also retrieve a promise for the preloaded [`up.Request`](https://unpoly.com/up.proxy.get) instance through [`up.proxy.get()`](https://unpoly.com/up.proxy.get).

To preload all links with an annotation like you can use a [compiler](https://unpoly.com/up.compiler). In the example below I'm preloading all links with an (arbitrarily chosen) `[app-preload-now]` attribute:

```javascript
up.compiler('a[href][app-preload-now]', function(link) {
  up.proxy.preload(link)
})
```
