### ISSUE TITLE
Inconsistent restore scroll behavior

### ISSUE THREAD

**Issue by makeitrein** [unpoly/unpoly#65]
Hey unpoly team - many thx for the wonderful library, makes by website https://ficdb.com butter smooth.

The one issue I'm running into is restoring scroll on back button. 

I've tested in the latest versions of Chrome, Safari, and Firefox.
**Chrome**: Go to home page > click fanfic > click back button = scroll not restored. But if you repeat the process, scroll is restored!
**Safari & Firefox**: Scroll is not restored on back button, even on repeated tries.

From the documentation, it looks like scroll-restore should work automatically - any suggestions on what I can do to get it working?

**Comment by triskweline** [comment]
Yes, it should work automatically.

This is probably a bug in Unpoly. I'm going to look into this.

**Comment by makeitrein** [comment]
Cool, I've swapped over to my own home-brewed modals for the time being, thx for checking it out.

**Comment by triskweline** [comment]
This issues might be related:
https://github.com/zeit/next.js/issues/3303

Might be fixed by setting `history.scrollRestoration = 'manual':
https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration
https://github.com/bfred-it/scroll-restoration-polyfill/blob/master/index.js

**Comment by makeitrein** [comment]
Thx for following up...

My solution was to add this polyfill: https://github.com/brigade/delayed-scroll-restoration-polyfill

There was also some strange Javascript being called on scroll by https://getuikit.com/ - once I removed that library, things worked more smoothly.

No clear cut answer here, but it's working again!
