### ISSUE TITLE
3.8 up-defer shouldn't requires click

### ISSUE THREAD

**Issue by marc-mabe** [unpoly/unpoly#651]
### Bug description

As described, the new `up-defer` lazy loading functionality should make an immediate request to load the content ...

> When the [[up-defer]](https://unpoly.com/up-defer) placeholder is rendered, it will immediately make a request to fetch its content from /menu:

but instead users have to click on the element to get loaded.

Additionally, using `up-href` is problematic as it will render `cursor: pointer;` which is not needed for the functionality (only if used within clickable items).

### Expected behavior

The content should be loaded immediately, as described in the docs with the following exceptions:

* up-defer="reveal" : Load immediately only if the element becomes visible
* up-defer="manual" : Manual loading implementation
* up-defer="interact" : This could be the current behavior of clicking described as: load immediately on user interaction (click)

Instead of using `up-href`, which is used to follow something, the attribute `up-source` should be used instead as the source of the content (like on polling).

### Additional Context

Thanks anyway for this new feature, even if not perfect yet.
For now I can replace my custom logic with a simple:
```js
up.compiler('[up-defer]', (el) => {
        const url = el.getAttribute('up-source');
        up.deferred.load(el, { url });
    });
```

**Comment by triskweline** [comment]
I cannot reproduce this. `[up-defer]` loads immediately for me, no click required:

https://glitch.com/edit/#!/band-heliotrope-trout
https://band-heliotrope-trout.glitch.me/

**Comment by marc-mabe** [comment]
Hi @triskweline,

OK, I see now it's working in a simple version.

Here an example (my use case) where it doesn't load immediatly:
https://glitch.com/edit/#!/marsh-honeysuckle-headlight
https://marsh-honeysuckle-headlight.glitch.me/

plus the wired `cursor: pointer`.

Sorry to not send the example in the first place, but I got the assumption that the click requirement was the standard undocumented behavior.

**Comment by marc-mabe** [comment]
Ahhhhhhhh damn I have missed the `#` in `up-target` - Indeed it's loading immediatly - Sorry my fault :exploding_head: 

But the wired `cursor: pointer` is still a thing. Can this be done via `up-source` instead?

**Comment by triskweline** [comment]
> But the wired `cursor: pointer` is still a thing.

The pointer cursor is a CSS rule in `unpoly.css`. We can change the rule to select on `[up-href]:not([up-defer])` instead.

> Can this be done via `up-source` instead?

It could. But I'd rather change `[up-poll]` to also use `[up-href]` so it's consistent everywhere.

The `[up-source]` attribute contains the URL a fragment is loaded from, and is set by Unpoly automatically. Seeing the confusion in this issue I'm thinking it should probably not be set by the user.

**Comment by marc-mabe** [comment]
Hi @triskweline,

I was under the impression that `up-href` is for navigating (following) a link (by the user) as described here https://unpoly.com/up-href. It basically implies a user interaction to navigate to.

Not tested, but I would guess, an element defined as `up-defer up-href="..."` would be clickable (no matter if styled with mouse pointer or not) and if it gets clicks it would probably dispatch an `up:link:follow` as well - not tested.

On the other hand, I understood `up-source` more like the source of the content without any navigation implications. (no matter if it has been loaded already or not)

**Comment by triskweline** [comment]
Also thinking about requiring to pair `[up-href]` with `[up-follow]` to make non-interactive elements behave like a link. This would be a breaking change though.
