### ISSUE TITLE
Form with up-target gets attribute role equal to "button"

### ISSUE THREAD

**Issue by pdudits** [unpoly/unpoly#668]
### Bug description

Since 3.9.0 `<form up-target="">` will get modified by unpoly to `<form up-layer="" tabindex="0" role="button" up-clickable="">`

This is wrong because form is obviously not a button (and breaks CSS libraries that style based on role).

Workaround is to set `role` attribute on form manually to `form`.

The bug was not present in 3.8.0.

### Reproduction project

https://glitch.com/edit/#!/alder-snow-drill

### Expected behavior

`role` attributes should not be changed on any elements unless explicitly asked for.

### Browser version

 - OS: Tested Windows and Android
 - Browser: Tested Firefox, Edge

**Comment by triskweline** [comment]
Fixed in 3.9.1. Thanks for the Glitch!
