### ISSUE TITLE
Relative links are (sometimes) resolved twice during revalidation

### ISSUE THREAD

**Issue by pdudits** [unpoly/unpoly#669]
### Bug description

When relative links are used in `<a up-follow>` they might get resolved against wrong base when revalidating -- sometimes link to `/sub/` will end up requesting `/sub/sub/` or link to `../` will request `../../`.

Workaround

### Reproduction project

https://glitch.com/edit/#!/political-plant-aardvark

Click start here, at let it run for a while and it eventually ends up back in root or in double-nested page.

I tried also with 3.5.0, so this is an old issue. With the reproducer I seem to hit it quite consistently on first revalidation.

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Click on 'Start here'
3. Randomly click 'Go Deeper', 'Go back', waiting some time. Actually I made it automatically click after cache expiration
5. When you land on root page, or at page 'This is the error', you've seen the error

### Expected behavior

Relative links should be always resolved against source URI of the fragment that was cached.

### Browser version

 - OS: Windows
 - Browser: Firefox, Edge
 - Version latest

**Comment by triskweline** [comment]
Thanks for the reproduction!
