### ISSUE TITLE
up-delay not working

### ISSUE THREAD

**Issue by miskolc** [unpoly/unpoly#7]
I'm coding a search form for one of my websites using `unpoly`. The search input looks like this:

`<input up-autosubmit="up-autosubmit" up-delay="200" class="form-control js-search" id="shop_name" name="shop_name" placeholder="Shop Name Here..." type="search" value="">`

The problem is that `up-delay` doesn't seem to work, or at least not as I think it should. I thought that `up-delay="200"` means `wait 200 miliseconds and the send the form again`, or something like this. The problem is that it is still sending too many requests to the server. I've gave it different values like 100, 200, 5000, 10000, 20000 and in all cases it behaved mostly the same way. Actually `up-delay="20000"` should have waited 20 seconds until submiting the form but it did not, it send the request immediately, actually it sent multiple requests. 

If I typed `amazon` in the input it would send requests with `a`, `am`, `amaz`, `amazon` as parameters. I don't think it should work like this.

**Comment by henning-koch** [comment]
Fixed in version 0.30.1.
