### ISSUE TITLE
[up-close] with [up-target] does not close modal dialog

### ISSUE THREAD

**Issue by foobear** [unpoly/unpoly#70]
An `[up-close]` link that also has an `[up-target]` currently opens the target URL inside the modal while it should close the modal dialog. Could be an issue with order of event handlers.

Example: https://codepen.io/foobear/project/editor/DQKzxr

**Comment by triskweline** [comment]
This is fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0), which was released today.
