### ISSUE TITLE
Broken link to “up-drawer” on the website’s home page

### ISSUE THREAD

**Issue by roryokane** [unpoly/unpoly#73]
The website for this library, https://unpoly.com/, has this text near the top:

> ### Branch off into layers
>
> Branch off interactions into [modals](https://unpoly.com/up.modal), [popups](https://unpoly.com/up.popup) or [drawers](https://unpoly.com/up-drawer). Return to the main page when you're done.

The link “drawers” within that leads to a missing page:

> ## Not Found
>
> The requested URL /up.drawer was not found on this server.

That link should be fixed or removed. I don’t know this library, so I don’t know whether the drawer functionality has been renamed or deleted.

The link’s URL `/up-drawer` contains a hyphen while the other links contain a period, so I thought that could be the problem, but the URL [`/up.drawer`](https://unpoly.com/up.drawer) doesn’t work either.

**Comment by triskweline** [comment]
Thanks for letting me know! The link is fixed now.

The URL should have been <https://unpoly.com/a-up-drawer>.
