### ISSUE TITLE
Submitting forms with up-target does not honor the formaction attribute

### ISSUE THREAD

**Issue by sturatcliffe** [unpoly/unpoly#74]
Hey,

I'm trying to submit the same form to multiple actions using multiple submit buttons with a formaction attribute on.

Simply adding up-target to the form seems to always post to the action set on the form element rather than the action set on the submit button. Am I missing something or is this just not supported out of the box? If not I assume I'll just need a custom compiler function?

Cheers, 
Stu

**Comment by triskweline** [comment]
Unfortunately that is not supported yet.

You should be able to work around it with a compiler like this:

```
up.compiler('button[formaction], input[formaction]', (button) => {
  var form = button.closest('form')
  var buttonAction = button.readAttribute('formaction')
  button.on('click', () => form.setAttribute('action', buttonAction))
})
```

**Comment by sturatcliffe** [comment]
Cool, thanks. Just wanted to check I wasn't missing something!

**Comment by mtarnovan** [comment]
Sorry for the necromancy, but are there any plans to support this directly? (And maybe also `formmethod` if it makes sense).

Thanks!

**Comment by triskweline** [comment]
This will be supported in the upcoming 1.0 release.
