### ISSUE TITLE
up-fail-layer="modal" doesn't open the modal

### ISSUE THREAD

**Issue by igormisha** [unpoly/unpoly#75]
I have a page structure like this

```
<div class="first">
    <a href="/first-page" up-target=".first" up-history="false" up-fail-layer="modal">First</a>
</div>

<div class="second">
    <a href="/second-page" up-target=".second" up-history="false" up-fail-layer="modal">First</a>
</div>
```

I gave the links on the page layer up-fail-layer="modal" because if I don't and the backend responds with error page (it may happen sometimes) which doesn't have a div of class like "first" or "second" unpoly replaces the whole body of my page. I wanted the error to popup in the modal but it doesn't work, giving me error: 

Could not find failure target in current modal (tried ["body"])

I suspect this is because the modal is not opened. I want when the link is provided with up-fail-layer="modal" and there is no currently opened modal to open it first and try to place the error page's body into it.

**Comment by triskweline** [comment]
As you suspected, `[up-layer]` can only target a layer that is already open. Unpoly 0.60 cannot open a new layer when submitting forms.

This happens to be one of the major changes in the next version of Unpoly that is currently under development.

**Comment by igormisha** [comment]
Ok, so the way to handle such kind of situations is to provide such links with [up-fail-target='.errors'] and put this <div class="errors"></div> somewhere on the page or even make it hidden for now?

**Comment by triskweline** [comment]
Sorry, I didn't understand your question.

**Comment by igormisha** [comment]
I mean that as unpoly can't open the modal for us when the request fails then if I don't want the error page to replace the whole body of my page (because the error page has no element corresponding the up-target attribute of the clicked link), I should provide the link with [up-fail-target=".errors"] attribute and add such element to the page layer.

**Comment by triskweline** [comment]
Yes, that would be a good solution. You can hide the errors container with a CSS rule like `.errors:empty { display: none }`.
