### ISSUE TITLE
up-switch and up-show-for don't work with select options containing spaces

### ISSUE THREAD

**Issue by igormisha** [unpoly/unpoly#78]
I have a select which I wanted to set attribute up-switch to. This select has options which contain spaces in their values. Other selects have up-show-for attribute to depend on the selected in that select value, but it doesn't work. The error which shows up is:
`Could not find [up-switch] field for ...`

**Comment by adam12** [comment]
[Still relevant](https://glitch.com/edit/#!/dolomite-chipped-license) with 2.2.1.

I'm not sure there's a great fix here. Maybe we could accept a JSON array? Test if value starts with `[` then `JSON.parse`?

**Comment by triskweline** [comment]
There is no established convention for escaping spaces in a space-separated list. Some use backslashes, some quote individual values. Each solution needs to provide more rules for encoding the escape character verbatim.

A benefit of using JSON would be that it is well-defined and most users already have a built-in function to convert an array of strings to JSON.

Is it a real or imagined concern that existing code is somewhere using the space-separated encoding and has the first option value begin with a square bracket? I know it's not for my team, but we've never had a space in our values either.
