### ISSUE TITLE
[up-modal][up-instant] links do not work reliably inside a drawer

### ISSUE THREAD

**Issue by kratob** [unpoly/unpoly#79]
I have user menu that lives inside a drawer. The menu contains an "Edit profile" link. This links is `[up-instant]` and opens a modal.

![unpoly-issue](https://user-images.githubusercontent.com/115590/56361165-eee70280-61e6-11e9-838b-0c7b984cc21b.png)

However, that modal will not open consistently. Depending on the length of the click, sometimes the drawer will close, but the modal will never appear.

There is obviously the easy workaround of not using `[up-instant]`, so this is not a very serious issue for me.

**Comment by kratob** [comment]
I believe the problematic code is this one:

https://github.com/unpoly/unpoly/blob/34197932fccd2ed87f1e40762cc4dda3a13baa18/lib/assets/javascripts/unpoly/modal.coffee.erb#L703-L710

I'm not a 100%, but I think what happens is this:
- `mousedown` is fired
- the drawer instantly starts to close
- `click` is fired
- however, since the drawer has already moved, the click will not fire on the link, but on the backdrop
- `closeAsap` is called, which somehow prevents the new modal from opening

**Comment by thinkwelltwd** [comment]
Could this get merged into a new release? I have some bootstrap4 dropdowns where link is to open a modal. And the modal opens correctly if I visit the page via up.visit(url), but on normal browser loads, the modal doesn't open. 

Came here to see if there where any similar experiences and found this issue, which seems to describe what I'm experiencing. Would be glad if there could be a fix, and willing to help test.

**Comment by triskweline** [comment]
> I have some bootstrap4 dropdowns where link is to open a modal.

I don't think you're seeing the same issue as @kratob . This issue #79 is about one Unpoly modal opening a second Unpoly modal using an `[up-instant]` link.

> And the modal opens correctly if I visit the page via up.visit(url), but on normal browser loads, the modal doesn't open.

That's a behavior I've never seen before. You should investigate what's causing this.

Try enabling Unpoly logs with `up.log.enable()`, then click on the dead modal link. Check if you're seeing `up:modal:open` events. If those are missing, something might cancel the click event before Unpoly can process it. A `click` event for the `a[up-modal]` links needs to bubble up to the `document` or Unpoly cannot process it.

Cannot say more without a reproduction case with minimal code, sorry.

**Comment by thinkwelltwd** [comment]
>  If those are missing, something might cancel the click event before Unpoly can process it. A click event for the a[up-modal] links needs to bubble up to the document or Unpoly cannot process it.

You are indeed correct../ I had some code that called `stopPropagation` on dropdown-menus. That was my problem.

Thanks a million!

**Comment by triskweline** [comment]
This is fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0), which was released today.
