### ISSUE TITLE
The "autosubmit" attribute doesn't work for form fields

### ISSUE THREAD

**Issue by miskolc** [unpoly/unpoly#8]
According to the [documentation](http://unpoly.com/up-autosubmit)

`<input autosubmit>`

should work for form fields. It doestn't.

On the other hand

`<input up-autosubmit>`

Works like a charm.

**Comment by henning-koch** [comment]
That's a mistake in the documentation. We only support `up-autosubmit`.

**Comment by miskolc** [comment]
Good to know!

**Comment by henning-koch** [comment]
Thanks @miskolc !

This is now fixed in the docs.
