### ISSUE TITLE
Append new content into target element instead of replacing already existed content

### ISSUE THREAD

**Issue by igormisha** [unpoly/unpoly#80]
I'm trying to implement the button "More" at the bottom of the list of elements with unpoly. 
And for example, I'd like to add responsive styling to the presentation of the list with the help of css grid using it's 
`grid-template-columns: repeat(content-fit, minmax(250px, 1fr))` 

If I want my list to look pretty on all devices when new elements are added I need them to be added to the same grid container to allow the css grid system to make it's work done.

I haven't found the way to append new elements to already existent with unpoly.

**Comment by adam12** [comment]
You likely want the `:after` [pseudo selector](https://unpoly.com/a-up-target).

```
<ul class="list"></ul>
<a href="" up-target=".list:after">More</a>
```

**Comment by igormisha** [comment]
I don't think :after can help in my case because it will fill the :after pseudo element and I need it to add elements to the list container itself because otherwise css grid won't be able to group them with already existant elements (there will be empty space on some screen sizes depending on how many elements are in the last row).
Besides, my "More" button should load additional search results not once but many times.

I'd like to have an attribute named something like `up-append` to make unpoly to append new results to the previously existant.

**Comment by triskweline** [comment]
`:after` was badly named. Targeting `.list:after` does not actually replace your `:after` pseudoelement, it appends a new child to `.list`.

This feature will probably be named to `:beforeend` to be in line with the standard [`Element.insertAdjacentElement()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement).

You may also look at the [Unpoly demo app](http://demo.unpoly.com/) to see a list with a "More" button. Scroll down the pane on the left.
