### ISSUE TITLE
.footer should not be included in up.viewport.config.anchoredRight

### ISSUE THREAD

**Issue by foobear** [unpoly/unpoly#81]
A non-fixed footer that uses `position: relative` itself (because of "internal" styling of the application) is moved to the left too far when a modal opens: by the padding added to `body` and by receiving a `right` style.

IMHO, a fixed footer should have a `up-fixed="bottom"` attribute, which is already included in `up.viewport.config.anchoredRight`, and Unpoly should not include `.footer` by default.

If you agree, I'm happy to open a PR.

**Comment by triskweline** [comment]
Are you using the bootstrap3 integration? This will be removed from the project in the near future.

**Comment by foobear** [comment]
We actually are. Sorry, wasn't aware of that.

The project is using Bootstrap 4 and I am pretty sure we applied Unpoly's attributes (almost?) everywhere already. Since it's not a 100% fit and will be removed anyway, we will try removing `unpoly-bootstrap3` from our application.
