### ISSUE TITLE
Google Group does not exist

### ISSUE THREAD

**Issue by Bogdanp** [unpoly/unpoly#83]
I was trying to look at the messages on the Google Group at https://groups.google.com/forum/#!forum/unpoly (found on the website at https://unpoly.com/community) today and it appears it doesn't exist. I'm not sure if this is a Google issue, or if the group has been made private or deleted, but I wanted to give you a heads-up!

**Comment by adam12** [comment]
The Google Group loads fine for me, tho it shows as "shared privately" and I wonder if that means it's delisted or members only?

![image](https://user-images.githubusercontent.com/17083/57701533-361bb400-762a-11e9-9697-336d40a3935e.png)

**Comment by triskweline** [comment]
Apparently Google decided to randomly change the group's settings :(

I re-opened the group to the public. Thanks for the hint @Bogdanp .
