### ISSUE TITLE
up-validate breaks focus

### ISSUE THREAD

**Issue by mordae** [unpoly/unpoly#84]
Using `up-validate` on form inputs seems to break focus in at least two common situations:

1. With `up.form.config.validateTargets = ['form &']`, moving from first field to the next using <kbd>↹ Tab</kbd> will switch focus and then lose it once the validation results arrive. Can be worked around by using a more narrow target.

2. Regardless of validation target, pressing <kbd>↓</kbd> (down) on a `<select>` will switch to the next option and then lose focus once the validation results arrive. I have no idea how to work around this.

Both issues manifest themselves at least in Firefox and Chromium on current Fedora.

**Comment by mordae** [comment]
There must be a better way to do this, but at the first glance this seems to work around the issue.

```javascript
/*
 * Work around form validation input focus loss.
 */
(function () {
  var activeId = null;

  function beforeInsert() {
    if (document.activeElement && document.activeElement.id) {
      activeId = document.activeElement.id;
    } else { 
      activeId = null;
    }
  }

  function afterInsert() {
    if (!activeId) {
      return;
    }

    document.getElementById(activeId).focus({
      'preventScroll': true,
    });
  }

  document.addEventListener('up:proxy:loaded', beforeInsert);
  document.addEventListener('up:fragment:inserted', afterInsert);
})();
```

**Comment by mordae** [comment]
By the way, this happens because old input is moved out of the DOM and the cloned one is not refocused. I am rather poor JS programmer to brave the patch, though.

**Comment by triskweline** [comment]
I will try to roll this into the next major release.

I think a good implementation needs a bit more complex than the workaround above since we would also need to restore scroll positions and text selection range (in addition to re-setting focus).

**Comment by naturallymitchell** [comment]
Thank you.

**Comment by okliv** [comment]
i've tweaked @mordae's workaround to position caret in text inputs right in place it have been before refresh (and it somehow works for form `up-autosubmit` too)

````
/*
 * Work around form validation input focus loss.
 */
function setCaretPosition(elem, caretPos) {
    var range;

    if (elem.createTextRange) {
        range = elem.createTextRange();
        range.move('character', caretPos);
        range.select();
    } else {
        elem.focus();
        if (elem.selectionStart !== undefined) {
            elem.setSelectionRange(caretPos, caretPos);
        }
    }
}

(function () {
    var activeId = null, currentPosition = 0;

    function beforeInsert() {
        if (document.activeElement && document.activeElement.id) {
            activeId = document.activeElement.id;
            currentPosition = document.activeElement.selectionStart;
        } else {
            activeId = null; currentPosition = 0
        }
    }

    function afterInsert() {
        if (!activeId) {
            return;
        }
        setCaretPosition(document.getElementById(activeId), currentPosition);
    }

    document.addEventListener('up:proxy:loaded', beforeInsert);
    document.addEventListener('up:fragment:inserted', afterInsert);
})();
````

**Comment by stefanfisk** [comment]
`up-validate` also messes up radio focus for me, essentially breaking keyboard input :/

**Comment by triskweline** [comment]
This is fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0), which was released today.
