### ISSUE TITLE
up-autosubmit doesn't honor form attribute on input fields

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [unpoly/unpoly#85]
Greetings,
Whenever an input field with the [form attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#form) is used, I'd expect `up-autosubmit` to behave the same for out-of-the-form input fields.
So, if a field out of the form but with form attribute set changes, I'd expect the form to autosubmit (or an `up-validate` to trigger a validation).

From my understanding, the framework doesn't consider these type of fields at all.

**Comment by etrokal** [comment]
I'm having the same problem. I'll stick to using a compiler for now.

**Comment by triskweline** [comment]
Related question and workaround: https://groups.google.com/forum/#!topic/unpoly/FeLFw-4iAR0

**Comment by triskweline** [comment]
Fixed in 0.61.1.
