### ISSUE TITLE
Simple AJAX example? 

### ISSUE THREAD

**Issue by aviv-or** [unpoly/unpoly#86]
Hey, 
Thank you so much for making this library, absolutely love it.
The documentation is crystal clear, though, the only thing i can't really understand is how to make AJAX requests with it and fetch the response:
https://unpoly.com/up.request

Do you mind sharing a small example? 

I also wonder if its possible to make requests like with intercooler.js (for example this inline row removal https://intercoolerjs.org/examples/deleterow.html).

Thanks again

**Comment by OvermindDL1** [comment]
> The documentation is crystal clear, though, the only thing i can't really understand is how to make AJAX requests with it and fetch the response:

What issue are you having with AJAX requests?  The example in the docs:
```javascript
up.request('/search', { params: { query: 'sunshine' } }).then(function(response) {
  console.log('The response text is %o', response.text)
}).catch(function() {
  console.error('The request failed')
})
```
Seems fairly simple, what do you need clarified with that?

> I also wonder if its possible to make requests like with intercooler.js (for example this inline row removal intercoolerjs.org/examples/deleterow.html).

Yeah those are pretty simple?  I do those kinds of things excessively in my projects, that's the basics of how Unpoly works.  Like literally I have a table that looks almost exactly like that intercooler example where I have a delete button (in a dropdown but still) on the right side of a row that causes that row to be deleted on the server, and the server confirms that updates the table and unpoly updates it based on that response.  :-)

**Comment by aviv-or** [comment]
Awesome, good to know that its possible with unpoly! :)
I feel really stupid now, because i was looking at the wrong page (https://unpoly.com/up.Request) which has no example... I even posted the link to the right page but missed it. Yeah its pretty simple, thanks you for your help.

**Comment by adam12** [comment]
> I also wonder if its possible to make requests like with intercooler.js (for example this inline row removal https://intercoolerjs.org/examples/deleterow.html).

A solution here would be to set the `up-target` on the button that deletes the row to the ID of the containing `table` , and then redirect to the page that contains the table. You're not deleting the individual row from the HTML, but re-rendering the table and replacing it.

The benefit of this method being, if Javascript isn't working, the form would submit as usual with a redirect.

**Comment by aviv-or** [comment]
Thank you guys for helping, i'm really looking forward to trying this out!
