### ISSUE TITLE
up-hungry doesn't appear to be working

### ISSUE THREAD

**Issue by sturatcliffe** [unpoly/unpoly#88]
I might be doing something wrong, so this may be more of a question around how up-hungry is supposed to work, but I can't get it working!

So I have an empty div element at the bottom of my body with the [up-hungry] attribute set:

```
<html>
<body>
    <div class=".body-content">
        ...
    </div>

    ...

    <div up-hungry class="toast-container"></div>
</body>
</html>
```

After a successful form post with `up-target=".body-content"`, the server issues a 302 redirect which is successful, and the `.body-content` div is replaced as expected with the new page content. 

However, even though the response also contains a change to the `<div up-hungry class="toast-container"></div>` element, the contents aren't updated and my toast messages are therefore not displayed. 

The content returned from the server looks like this:

```
<div up-hungry class="toast-container">
    <div class="toast-message" data-toast-type="success" data-toast-message="Success message!"></div>
</div>
```

I then have a compiler function which looks for the `.toast-message` class and invokes toastr with the values from the data attributes:

```
up.compiler('.toast-message', function ($element) {
    var toastType = $element.data('toast-type');
    var toastMessage = $element.data('toast-message');

    if (toastType && toastMessage) {
        toastr[toastType](toastMessage);
    }
});
```

Thanks in advance!

**EDIT forgot to mention we're still on version 0.51.1 due to an issue with form submit query params in the latest version.

**Comment by sturatcliffe** [comment]
Apologies, just found the changelog and realised passive updates wasn't introduced until 0.53.0. Normally the docs mentions the version new features are added so I'd assumed this was an older feature, sorry!

**Comment by triskweline** [comment]
No problem. Thanks for taking the time to check the changelog.
