### ISSUE TITLE
Cancelling [up-confirm] dialog doesn't remove .up-active class

### ISSUE THREAD

**Issue by alexbndk** [unpoly/unpoly#89]
I have the following link:

```
<a href="/resource/id" up-follow="true" up-method="delete" up-confirm="Are you sure?">
  Delete
</a>
```

When cancelling the resulting dialog the `up-active` class doesn't get removed. I would expect it to be removed (or not added at all) since no requests are actually made and the link isn't "active".

I have a global style that adds a spinner to any link with the class name, which in this case results in a pretty confusing UI.

PS. Thanks for your work on unpoly. We've used it for the past few months and it's been a refreshing experience as most things "just work" how I expect, without even having to reference the docs.

**Comment by triskweline** [comment]
Fixed in 0.60.1.

> PS. Thanks for your work on unpoly. We've used it for the past few months and it's been a refreshing experience as most things "just work" how I expect, without even having to reference the docs.

Thanks for the kind words!
