### ISSUE TITLE
Deprecate .css.scss and .css.sass extensions in sass-rails 5.x

### ISSUE THREAD

**Issue by neonmate** [unpoly/unpoly#9]
`DEPRECATION WARNING: Extra .css in SASS file is unnecessary. Rename unpoly-rails-0.29.0/lib/assets/stylesheets/unpoly.css.sass to unpoly-rails-0.29.0/lib/assets/stylesheets/unpoly.sass.`

`DEPRECATION WARNING: Extra .css in SASS file is unnecessary. Rename unpoly-rails-0.29.0/lib/assets/stylesheets/unpoly-bootstrap3.css.sass to unpoly-rails-0.29.0/lib/assets/stylesheets/unpoly-bootstrap3.sass.`

https://github.com/rails/sass-rails/blob/5-0-stable/lib/sass/rails/importer.rb#L123

**Comment by henning-koch** [comment]
Fixed in `master`.
