### ISSUE TITLE
Optimizing responses on tables

### ISSUE THREAD

**Issue by thinkwelltwd** [unpoly/unpoly#91]
In the Server Protocol docs, under [Optimizing responses](https://unpoly.com/up.protocol#optimizing-responses), it says that:

> Server-side code is free to optimize its response by only returning HTML that matches the selector. For example, you might prefer to not render an expensive sidebar if the sidebar is not targeted.

I have large tables where I need to swap out table rows; each `tr` tag has an ID. The server response includes only the `tr` tag, so the entire response contents match the ID selector. However, unpoly can't find the ID in the response and updates the body instead of the table row.

If the server returns the entire table, then unpoly correctly updates the table. I also tried having the server return the `tbody` tag of the table, but unpoly couldn't extract the table row.

Then also tried assigning the ID to the `tbody` tag, and same result as `tr` - the content loads in the `body` tag. 

The only way that I've encountered to get a `tbody` or `tr` tag swapped is to send the entire table from the server.  That's still more efficient than the entire page, but it seems like a bug to me.

**Comment by adam12** [comment]
Have you tried rendering a minimal `table` with only that `tr`? Then using the `id` selector as you were.

I can't find a source to back this up right now, but I feel like there are certain tags that just can't exist on their own, and browser react indeterminately when they see them. My guess is `tr`, `td`, and a few others (`tbody`?) will just parse oddly without a parent `table`.

**Comment by triskweline** [comment]
Like @adam12 said, wrap your `<tr>` in a `<table>` and it will work.

Unpoly uses your browser to parse the server response. The response always needs to be a valid HTML fragment, or the browser will consider it tag soup and silently rewrite your HTML:

![dom_parser](https://user-images.githubusercontent.com/89953/62516460-718ede80-b825-11e9-91c0-b87bcb16f8d1.png)

**Comment by thinkwelltwd** [comment]
> Have you tried rendering a minimal table with only that tr? Then using the id selector as you were.

Yes, that's what I meant by "If the server returns the entire table, then unpoly correctly updates the table."

> Unpoly uses your browser to parse the server response. The response always needs to be a valid HTML fragment.

Ok, thanks for the explanation. I don't know if there'd be a way to clarify the [Optimizing responses](https://unpoly.com/up.protocol#optimizing-responses) section or not; something like:

Server-side code is free to optimize its response by only returning valid, browser-parseable HTML that matches the selector. 

I'm switching from [IntercoolerJS](http://intercoolerjs.org/) where the response consisting only of `tr` tag worked fine. I was using [ic-replace-target](http://intercoolerjs.org/attributes/ic-replace-target.html), which inserts the entire response - apparently with no browser parsing of the HTML.

Sorry for the bother on this ticket.

**Comment by triskweline** [comment]
Unpoly 3.12.0-rc6 can process table rows without an enclosing `<table>`.

**Comment by thinkwelltwd** [comment]
Many thanks, @triskweline! What a nice enhancement. 💯
