### ISSUE TITLE
Is there a way to save cache in localstorage?

### ISSUE THREAD

**Issue by frederikhors** [unpoly/unpoly#95]
Is there a way to cache fragments, locations (pages) in localstorage to re-hydratate immmediately and fetch in background the same pages when I go back to my website?

**Comment by triskweline** [comment]
The cache is held in memory and hence cleared after a page load.

You can manually set cache entries using [`up.cache.set()`](https://unpoly.com/up.proxy.set) or implement custom caching logic in a service worker.

**Comment by frederikhors** [comment]
Is there a way to persist cache in Localstorage or IndexedDB today? @triskweline ?

Some code anywhere?

**Comment by triskweline** [comment]
Nothing has changed since my previous answer.

**Comment by frederikhors** [comment]
Ok. But maybe something has changed because https://unpoly.com/up.proxy.set it is not reachable.

To be clearer: unpoly's cache is wonderful: it does just what everyone expects and I think unpoly is amazing also because of this.

But what I would like to achieve is:

1. the user navigates with the mobile phone, opens modals, makes changes and the item lists are updated, good

1. the user leaves work and takes the ferry to go home

1. while waiting to arrive, he reopens the website/app and looks for the data he had seen a minute before and - since there is no internet on the ferry (or under the tunnel or in the countryside) (and there won't be for the next few minutes) he does not see nothing because that cache is not persisted in the browser he used a few minutes before

1. the user is angry

This of course can be mitigated with service-workers, but I don't know how (that's why I'm asking) because if I cache page calls in browser cache storage with (let's say) the stale-while-revalidate pattern then the service-worker is givinig me back that cached page (which when internet is back) maybe not be the fresh one anymore.

Can you please assist me in this reasoning?

1. ONLINE: GET /list (v1)

1. SW CACHE EMPTY: /list cached (v1)

1. UNPOLY gets /list (v1)

1. CLOSE BROWSER

1. Someone updates /list (to v2)

1. ONLINE: GET /list (v1)

1. SW CACHE FULLFILLED FROM BEFORE gives unpoly /list (v1)

1. UNPOLY gets /list (v1) from SW immediately fullfilling it's cache

1. UNPOLY ask server (through SW) for updates on /list (v1)

1. SW cache /list (v2)

1. UNPOLY re-render for /list (v2)

1. CLOSE BROWSER

1. OFFLINE: GET /list (v2) comes from SW cache (maybe with some indicator that is stale content)

**What do you think?**

**Comment by frederikhors** [comment]
@triskweline any news on this as of today?

Can we persist cache somewhere other than in memory?
