### ISSUE TITLE
up-autosubmit does not seem to work with radio buttons

### ISSUE THREAD

**Issue by 1player** [unpoly/unpoly#96]
```
<div>
    <input id="order_ranking" name="order" type="radio" up-observe="alert('ranking')" value="ranking" up-autosubmit=""> ranking
    <input id="order_expiration_date" name="order" type="radio" up-observe="alert('expiration')" value="expiration_date" up-autosubmit=""> expiration date
</div>
```

`up-autosubmit` is firing only when I first click each radio button, then it stops firing altogether when I click to a previously selected button. Same issue with that `up-observe` attribute, which AFAIK is the same mechanism autosubmit uses underneath.

**Comment by triskweline** [comment]
Multiple radio buttons with the same `[name]` (a radio button group) produce a single value for the form.

To auto-submit radio buttons group, use the `[up-submit]` attribute on an element that contains all radio button elements with a given name:

    <div up-autosubmit>
      <input type="radio" name="format" value="html"> HTML format
      <input type="radio" name="format" value="pdf"> PDF format
      <input type="radio" name="format" value="txt"> Text format
    </div>

I also added this to the docs.

**Comment by licht1stein** [comment]
Is it the same with `up-validate`? Because I seem to experience only the first radio button submitting a validation request, even if I set `up-validate` on the parent `div`.

**Comment by triskweline** [comment]
> Is it the same with up-validate? 

`[up-validate]` [should also be set](https://unpoly.com/up-validate#validating-radio-buttons) on a container of radio buttons.

> Because I seem to experience only the first radio button submitting a validation request, even if I set up-validate on the parent div.

If you can reproduce this, please open an issue.
