### ISSUE TITLE
Add hot reloading devtool

### ISSUE THREAD

**Issue by stefanfisk** [unpoly/unpoly#97]
I've just started using Unpoly for a project, and a few weeks into it everything feels great as far as the client experience goes! I do however miss hot reloading like you have in React and others. I've been reading the API docs to figure out how to implement the browser side of it all, but so far I'm not quite getting if/how it could be done. Any pointers as to proceed would be much appreciated!

Here are two questions that I have on the top of my head:

1. Is it possible to request a reload of everything, even the body, in a coordinated manner?
2. Does Unpoly handle changes to `<head>` at all?

**Comment by triskweline** [comment]
I'm afraid I'm not familiar with how hot relading works in React. Can you elaborate how this would behave?

At work we're using the webpack dev server, which automatically reloads the entire page when an asset changes. Are you looking for something like that?

Regarding your questions:

> Is it possible to request a reload of everything, even the body, in a coordinated manner?

Like [`location.reload()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload)?

> Does Unpoly handle changes to <head> at all?

Only when you target something in the `<head>`. Note that while you can swap our stylesheets that way, scripts often have side effects (like event listeners) that will not be undone by swapping the `<script>` tag.

**Comment by stefanfisk** [comment]
Hot reloading essentially means reloading the page content without losing state. So in React there's a hot reload server which pushes recompiled modules to the client, and then the client swaps out components whose code has been modified while still maintaining their state. The effect is that you can edit your components and see the changes live without any page reload. What I'm looking for is a similar dev experience with Unpoly, where I can edit my markup and see the DOM changes live in the browser.

`up.reload()` seems like it could be a start for reloading the DOM, but the documentation is a bit too sparse for me to quite understand if it could be used. Could it be used for reloading all fragments? What happens if fragments are nested, like if `body` was replaced by `up-follow`, and it contains a form in some validation state?

**Comment by triskweline** [comment]
Unfortunately I'm still not sure how to do something like this. Unlike React, Unpoly does not track the client-side state of a component, and hence cannot restore it after a reload.

I'm closing this for now.
