### ISSUE TITLE
File size with webpack

### ISSUE THREAD

**Issue by keyurshah** [unpoly/unpoly#98]
When I use webpack (via laravel mix) to include unpoly, the file size seems to be way bigger than the CDN version.

I'm getting from the stats, a gzipped size of 114.42 KB through webpack.

And from the CDN its 33.2 KB.

Any reason why this could be?

This is how i include it in my app.js 

```
import 'unpoly';
import 'unpoly/dist/unpoly.css';
```

and in package.json i have it as the following dependency

```
"unpoly": "^0.60.3"
```

**Comment by triskweline** [comment]
I'm not familiar with Laravel Mix, but are you minifying your JavaScript bundle? 114 KB is about the gzipped size of the unminified Unpoly sources. The CDN version is minified.

**Comment by keyurshah** [comment]
let me close this until i can get more stats on this and reproduce it. i think webpack analyzer is reporting minified results and not gzipped results.

thank you.
