### ISSUE TITLE
Disable on mobile?

### ISSUE THREAD

**Issue by bichonnages** [unpoly/unpoly#99]
Sorry for the silly question - unpoly works great, thanks!
I'd like to know if there was any easy way to disable unpoly on mobile?

**Comment by triskweline** [comment]
Have you considered not including `<script>` tags on mobile?

**Comment by bichonnages** [comment]
Well, I was thinking more about :

`if (window.matchMedia("(min-width: 600px)").matches) {
  /* enable unpoly */
} else {
  /* disable unpoly */
}`

From that, I have been doing researches on enabling up-modal links through jQuery (instead of using directly up-modal=".lightbox" on a link): 

`$( ".up-modal-link" ).each(function(upModalLinks) {
     $(this).on("click", function(){
         up.modal.follow(this);
     });
});`

But I cannot make it work since I don't understand how to add the target element in  up.modal.follow(this);

`up.modal.follow(this, {options:{target: '.lightbox'}});` does not work

**Comment by triskweline** [comment]
You can try this:

```
if (window.matchMedia("(min-width: 600px)").matches) {
  document.write('<script type="text/javascript" src="unpoly.js"></script>')
}
```

Regarding the other issue, `{ target }` is a direct option to `up.modal.follow()`, there is no `{ options }` key:

```
$('.up-modal-link').each(function() {
  up.modal.follow(this, { target: '.lightbox') })
})
```

**Comment by bichonnages** [comment]
Thanks for the reply!

```
$('.up-modal-link').each(function() {
  up.modal.follow(this, { target: '.lightbox') })
})
```
Does not work if I turn it into this : 

```
$('.up-modal-link').each(function() {
  $(this).click(function(){
    up.modal.follow(this, { target: '.lightbox'})
  });
});
```

**Comment by bichonnages** [comment]
well, I ended doing this : 

```
<a href="/something/" up-modal=".lightbox" class="up-modal-link">

</a>
```

```
if (matchMedia) {
				const mq = window.matchMedia("(min-width: 900px)");
				mq.addListener(WidthChange);
				WidthChange(mq);
			}
			
			function WidthChange(mq) {
				
				if (mq.matches) {
					
					$('.up-modal-link').each(function(){
						
						if($(this).attr('up-modal')){
							
						} else {
							
							$('.up-modal-link').attr('up-modal', '.lightbox');
							
						}
						
					});
									
				} else {
					
					$('.up-modal-link').each(function(){
						
						$(this).removeAttr("up-modal");
						
						
					});
					
				}
			
			}
```
